Working Memory: com.gtfp.workingmemory.google.googleAPI Class Reference
com.gtfp.workingmemory.google.googleAPI Class Reference
Created by Drawn on 2016-01-22.
Classes
class ApiClientAsyncTask
An AsyncTask that maintains a connected client.
interface ApiClientTask
interface crud
class RetrieveDriveFileContentsAsyncTask
Public Member Functions
googleAPI (Context context)
googleAPI addGoogleDriveAPI ()
googleAPI addGoogleSignInAPI ()
googleAPI addConnectionCallbacks (GoogleApiClient.ConnectionCallbacks callObj)
googleAPI addOnConnectionFailedListener (GoogleApiClient.OnConnectionFailedListener listenerObj)
GoogleApiClient build ()
googleAPI setResultCallback (googleAPI.crud resultCallback)
GoogleApiClient getGoogleApiClient ()
GoogleApiClient buildGoogleApiClient ()
GoogleApiClient.Builder getBuilder ()
void queryDrive (Query query)
void queryDrive (Query query, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
void createFile (String name, String type)
void createFolder (String title)
DriveId createFolder (File file)
void getFile (String title, String type, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
void trashFile (String title, String type)
DriveId getFolderID (File file, GoogleApiClient googleAPI)
DriveId getID (DriveId parentId, String title, String type, GoogleApiClient googleAPI)
void fetchDriveFile (DriveId id, final ApiClientTask obj)
DriveId createFolderID (DriveId parentId, String title)
DriveId getFolderID (DriveId parentId, String title)
DriveId getFolderID (DriveId parentId, String title, GoogleApiClient googleAPI)
Query getFolderQuery (DriveId parentId, String title)
DriveId getFolderID (Query qry, GoogleApiClient googleAPI)
void getFolderID (DriveId parentId, String title, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
void getFolderID (DriveId parentId, String title, GoogleApiClient googleAPI, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
void getFolderID (Query qry, GoogleApiClient googleAPI, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
DriveFolder createFolder (DriveId parentId, String title)
DriveFolder getAppFolder ()
DriveFolder getAppFolder (GoogleApiClient googleApiClient)
void onDestroy ()
RetrieveDriveFileContentsAsyncTask getApiClientTask (ApiClientTask obj)
Protected Member Functions
void createFile (String title, String fileType, DriveContents driveContents)
Package Attributes
ResultCallback< DriveApi.MetadataBufferResult > mTrashCallback
ResultCallback< Status > mTrashResultCallback
Private Attributes
Context mContext
GoogleApiClient.Builder mBuilder
GoogleApiClient mGoogleApiClient
googleAPI.crud mCRUDapi
File mFile
DriveFolder mAppFolder
boolean buildDrive = false
boolean buildSignIn = false
Static Private Attributes
static final String MIME_TYPE_FOLDER = "application/vnd.google-apps.folder"
static final String MIME_TYPE_PLAINTEXT = "text/plain"
Detailed Description
Created by Drawn on 2016-01-22.
Definition at line 41 of file googleAPI.java.
Constructor & Destructor Documentation
googleAPI()
com.gtfp.workingmemory.google.googleAPI.googleAPI (Context context)
Definition at line 66 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder.
Referenced by com.gtfp.workingmemory.google.googleAPI.getFolderID().
Member Function Documentation
addGoogleDriveAPI()
googleAPI com.gtfp.workingmemory.google.googleAPI.addGoogleDriveAPI ()
Definition at line 74 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder.
addGoogleSignInAPI()
googleAPI com.gtfp.workingmemory.google.googleAPI.addGoogleSignInAPI ()
Definition at line 89 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.build(), and com.gtfp.workingmemory.google.googleAPI.mBuilder.
addConnectionCallbacks()
googleAPI com.gtfp.workingmemory.google.googleAPI.addConnectionCallbacks (GoogleApiClient.ConnectionCallbacks callObj)
Definition at line 110 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder.
addOnConnectionFailedListener()
googleAPI com.gtfp.workingmemory.google.googleAPI.addOnConnectionFailedListener (GoogleApiClient.OnConnectionFailedListener listenerObj)
Definition at line 118 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder.
build()
GoogleApiClient com.gtfp.workingmemory.google.googleAPI.build ()
Definition at line 127 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder, and com.gtfp.workingmemory.google.googleAPI.mGoogleApiClient.
Referenced by com.gtfp.workingmemory.google.googleAPI.addGoogleSignInAPI().
setResultCallback()
googleAPI com.gtfp.workingmemory.google.googleAPI.setResultCallback (googleAPI.crud resultCallback)
Definition at line 138 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mCRUDapi.
getGoogleApiClient()
GoogleApiClient com.gtfp.workingmemory.google.googleAPI.getGoogleApiClient ()
Definition at line 146 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mGoogleApiClient.
buildGoogleApiClient()
GoogleApiClient com.gtfp.workingmemory.google.googleAPI.buildGoogleApiClient ()
Definition at line 152 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder.
Referenced by com.gtfp.workingmemory.google.googleAPI.fetchDriveFile(), and com.gtfp.workingmemory.google.googleAPI.getApiClientTask().
getBuilder()
GoogleApiClient.Builder com.gtfp.workingmemory.google.googleAPI.getBuilder ()
Definition at line 158 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder.
queryDrive() [1/2]
void com.gtfp.workingmemory.google.googleAPI.queryDrive (Query query)
Definition at line 176 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mCRUDapi.
queryDrive() [2/2]
void com.gtfp.workingmemory.google.googleAPI.queryDrive (Query query, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
Definition at line 192 of file googleAPI.java.
createFile() [1/2]
void com.gtfp.workingmemory.google.googleAPI.createFile (String name, String type)
Definition at line 201 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mCRUDapi.
createFolder() [1/3]
void com.gtfp.workingmemory.google.googleAPI.createFolder (String title)
Definition at line 241 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mCRUDapi.
Referenced by com.gtfp.workingmemory.google.googleAPI.createFile(), com.gtfp.workingmemory.google.googleAPI.createFolder(), and com.gtfp.workingmemory.google.googleAPI.createFolderID().
createFile() [2/2]
void com.gtfp.workingmemory.google.googleAPI.createFile (String title, String fileType, DriveContents driveContents) protected
Definition at line 266 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.createFolder(), and com.gtfp.workingmemory.google.googleAPI.mCRUDapi.
createFolder() [2/3]
DriveId com.gtfp.workingmemory.google.googleAPI.createFolder (File file)
Definition at line 300 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.createFolder(), com.gtfp.workingmemory.google.googleAPI.createFolderID(), and com.gtfp.workingmemory.google.googleAPI.getAppFolder().
getFile()
void com.gtfp.workingmemory.google.googleAPI.getFile (String title, String type, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
Definition at line 324 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getFolderID(), and com.gtfp.workingmemory.google.googleAPI.mGoogleApiClient.
Referenced by com.gtfp.workingmemory.google.googleAPI.trashFile().
trashFile()
void com.gtfp.workingmemory.google.googleAPI.trashFile (String title, String type)
Definition at line 372 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getFile(), and com.gtfp.workingmemory.google.googleAPI.mTrashCallback.
getFolderID() [1/7]
DriveId com.gtfp.workingmemory.google.googleAPI.getFolderID (File file, GoogleApiClient googleAPI)
Definition at line 455 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getAppFolder(), and com.gtfp.workingmemory.google.googleAPI.googleAPI().
Referenced by com.gtfp.workingmemory.google.googleAPI.createFolderID(), com.gtfp.workingmemory.google.googleAPI.getFile(), and com.gtfp.workingmemory.google.googleAPI.getFolderID().
getID()
DriveId com.gtfp.workingmemory.google.googleAPI.getID (DriveId parentId, String title, String type, GoogleApiClient googleAPI)
Definition at line 478 of file googleAPI.java.
References com.gtfp.workingmemory.app.App.PackageName().
fetchDriveFile()
void com.gtfp.workingmemory.google.googleAPI.fetchDriveFile (DriveId id, final ApiClientTask obj)
Definition at line 516 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.buildGoogleApiClient().
createFolderID()
DriveId com.gtfp.workingmemory.google.googleAPI.createFolderID (DriveId parentId, String title)
Definition at line 542 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.createFolder(), and com.gtfp.workingmemory.google.googleAPI.getFolderID().
Referenced by com.gtfp.workingmemory.google.googleAPI.createFolder().
getFolderID() [2/7]
DriveId com.gtfp.workingmemory.google.googleAPI.getFolderID (DriveId parentId, String title)
Definition at line 565 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getFolderID().
getFolderID() [3/7]
DriveId com.gtfp.workingmemory.google.googleAPI.getFolderID (DriveId parentId, String title, GoogleApiClient googleAPI)
Definition at line 571 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getFolderID(), and com.gtfp.workingmemory.google.googleAPI.getFolderQuery().
getFolderQuery()
Query com.gtfp.workingmemory.google.googleAPI.getFolderQuery (DriveId parentId, String title)
Definition at line 579 of file googleAPI.java.
References com.gtfp.workingmemory.app.App.PackageName().
Referenced by com.gtfp.workingmemory.google.googleAPI.getFolderID().
getFolderID() [4/7]
DriveId com.gtfp.workingmemory.google.googleAPI.getFolderID (Query qry, GoogleApiClient googleAPI)
Definition at line 600 of file googleAPI.java.
getFolderID() [5/7]
void com.gtfp.workingmemory.google.googleAPI.getFolderID (DriveId parentId, String title, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
Definition at line 626 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getFolderID().
getFolderID() [6/7]
void com.gtfp.workingmemory.google.googleAPI.getFolderID (DriveId parentId, String title, GoogleApiClient googleAPI, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
Definition at line 633 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.getFolderID(), and com.gtfp.workingmemory.google.googleAPI.getFolderQuery().
getFolderID() [7/7]
void com.gtfp.workingmemory.google.googleAPI.getFolderID (Query qry, GoogleApiClient googleAPI, ResultCallback< DriveApi.MetadataBufferResult > onQueryResult)
Definition at line 642 of file googleAPI.java.
createFolder() [3/3]
DriveFolder com.gtfp.workingmemory.google.googleAPI.createFolder (DriveId parentId, String title)
Definition at line 649 of file googleAPI.java.
getAppFolder() [1/2]
DriveFolder com.gtfp.workingmemory.google.googleAPI.getAppFolder ()
Definition at line 662 of file googleAPI.java.
Referenced by com.gtfp.workingmemory.google.googleAPI.createFolder(), and com.gtfp.workingmemory.google.googleAPI.getFolderID().
getAppFolder() [2/2]
DriveFolder com.gtfp.workingmemory.google.googleAPI.getAppFolder (GoogleApiClient googleApiClient)
Definition at line 669 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mAppFolder.
onDestroy()
void com.gtfp.workingmemory.google.googleAPI.onDestroy ()
Definition at line 685 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.mBuilder, and com.gtfp.workingmemory.google.googleAPI.mCRUDapi.
getApiClientTask()
RetrieveDriveFileContentsAsyncTask com.gtfp.workingmemory.google.googleAPI.getApiClientTask (ApiClientTask obj)
Definition at line 706 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.buildGoogleApiClient().
Member Data Documentation
mContext
Context com.gtfp.workingmemory.google.googleAPI.mContext private
Definition at line 43 of file googleAPI.java.
MIME_TYPE_FOLDER
final String com.gtfp.workingmemory.google.googleAPI.MIME_TYPE_FOLDER = "application/vnd.google-apps.folder" static private
Definition at line 45 of file googleAPI.java.
MIME_TYPE_PLAINTEXT
final String com.gtfp.workingmemory.google.googleAPI.MIME_TYPE_PLAINTEXT = "text/plain" static private
Definition at line 47 of file googleAPI.java.
mBuilder
GoogleApiClient.Builder com.gtfp.workingmemory.google.googleAPI.mBuilder private
Definition at line 50 of file googleAPI.java.
Referenced by com.gtfp.workingmemory.google.googleAPI.addConnectionCallbacks(), com.gtfp.workingmemory.google.googleAPI.addGoogleDriveAPI(), com.gtfp.workingmemory.google.googleAPI.addGoogleSignInAPI(), com.gtfp.workingmemory.google.googleAPI.addOnConnectionFailedListener(), com.gtfp.workingmemory.google.googleAPI.build(), com.gtfp.workingmemory.google.googleAPI.buildGoogleApiClient(), com.gtfp.workingmemory.google.googleAPI.getBuilder(), com.gtfp.workingmemory.google.googleAPI.googleAPI(), and com.gtfp.workingmemory.google.googleAPI.onDestroy().
mGoogleApiClient
GoogleApiClient com.gtfp.workingmemory.google.googleAPI.mGoogleApiClient private
Definition at line 52 of file googleAPI.java.
Referenced by com.gtfp.workingmemory.google.googleAPI.build(), com.gtfp.workingmemory.google.googleAPI.getFile(), and com.gtfp.workingmemory.google.googleAPI.getGoogleApiClient().
mCRUDapi
googleAPI.crud com.gtfp.workingmemory.google.googleAPI.mCRUDapi private
Definition at line 54 of file googleAPI.java.
Referenced by com.gtfp.workingmemory.google.googleAPI.createFile(), com.gtfp.workingmemory.google.googleAPI.createFolder(), com.gtfp.workingmemory.google.googleAPI.onDestroy(), com.gtfp.workingmemory.google.googleAPI.queryDrive(), and com.gtfp.workingmemory.google.googleAPI.setResultCallback().
mFile
File com.gtfp.workingmemory.google.googleAPI.mFile private
Definition at line 56 of file googleAPI.java.
mAppFolder
DriveFolder com.gtfp.workingmemory.google.googleAPI.mAppFolder private
Definition at line 58 of file googleAPI.java.
Referenced by com.gtfp.workingmemory.google.googleAPI.getAppFolder().
buildDrive
boolean com.gtfp.workingmemory.google.googleAPI.buildDrive = false private
Definition at line 60 of file googleAPI.java.
buildSignIn
boolean com.gtfp.workingmemory.google.googleAPI.buildSignIn = false private
Definition at line 62 of file googleAPI.java.
mTrashCallback
ResultCallback<DriveApi.MetadataBufferResult> com.gtfp.workingmemory.google.googleAPI.mTrashCallback package
Definition at line 378 of file googleAPI.java.
Referenced by com.gtfp.workingmemory.google.googleAPI.trashFile().
mTrashResultCallback
ResultCallback<Status> com.gtfp.workingmemory.google.googleAPI.mTrashResultCallback package
Initial value:
= new ResultCallback<Status>() {
        @Override
        public void onResult(Status result) {
            if (result == null) {
                return;
            }
            if (result.isSuccess()) {
                App.getView().restoreSync();
            }
        }
    }
Definition at line 430 of file googleAPI.java.