Working Memory: com.gtfp.workingmemory.utils.Devices Class Reference
com.gtfp.workingmemory.utils.Devices Class Reference
Helper class to get the consumer friendly device name.
Static Public Member Functions
static String getDeviceName ()
Returns the consumer friendly device name.
static String getDeviceName (final String device)
Returns the consumer friendly device name based on the value of Build#DEVICE.
Private Member Functions
Devices ()
Static Private Member Functions
static final String capitalize (final String str)
Static Private Attributes
static final String [] SUPPORTED_DEVICES
This array is using the list of supported devices on Google Play.
static String sDeviceName
Detailed Description
Helper class to get the consumer friendly device name.
String device = Devices.getDeviceName();
The above code will get the device name as specified in the supported device list that is maintained by Google.
See: https://support.google.com/googleplay/answer/1727131
Author
Jared Rummler jared.nosp@m..rum.nosp@m.mler@.nosp@m.gmai.nosp@m.l.com
Definition at line 35 of file Devices.java.
Constructor & Destructor Documentation
Devices()
com.gtfp.workingmemory.utils.Devices.Devices () private
Definition at line 3663 of file Devices.java.
Member Function Documentation
getDeviceName() [1/2]
static String com.gtfp.workingmemory.utils.Devices.getDeviceName () static
Returns the consumer friendly device name.
Definition at line 3580 of file Devices.java.
References com.gtfp.workingmemory.utils.Devices.capitalize(), and com.gtfp.workingmemory.utils.Devices.sDeviceName.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.hidePreferences().
getDeviceName() [2/2]
static String com.gtfp.workingmemory.utils.Devices.getDeviceName (final String device) static
Returns the consumer friendly device name based on the value of Build#DEVICE.
Definition at line 3611 of file Devices.java.
capitalize()
static final String com.gtfp.workingmemory.utils.Devices.capitalize (final String str) static private
Capitalizes all the whitespace separated words in a String. Only the first letter of each word is changed. To convert the rest of each word to lowercase at the same time, use capitalizeFully(String).
Whitespace is defined by Character#isWhitespace(char).
Parameters
str the String to capitalize
Returns
capitalized The capitalized String
Definition at line 3643 of file Devices.java.
Referenced by com.gtfp.workingmemory.utils.Devices.getDeviceName().
Member Data Documentation
SUPPORTED_DEVICES
final String [] com.gtfp.workingmemory.utils.Devices.SUPPORTED_DEVICES static private
This array is using the list of supported devices on Google Play.
Any device that does not have both the retail name and marketing name is not included.
See the following URL for the PDF that this list was derived from: https://support.google.com/googleplay/answer/1727131
Each String uses a vertical line to separate the manufacturer, name, device, and model:
"Retail Branding|Marketing Name|Device|Model"
Last updated: 2/5/2015
Definition at line 53 of file Devices.java.
sDeviceName
String com.gtfp.workingmemory.utils.Devices.sDeviceName static private
Definition at line 3577 of file Devices.java.
Referenced by com.gtfp.workingmemory.utils.Devices.getDeviceName().