Working Memory: com.gtfp.workingmemory.colorPicker.colorPickerView Class Reference
com.gtfp.workingmemory.colorPicker.colorPickerView Class Reference
Created by Drawn on 2015-03-25.
Classes
interface OnColorChangedListener
Public Member Functions
colorPickerView (Context context, AttributeSet attrs)
boolean onTouchEvent (MotionEvent event)
Static Public Member Functions
static void init (OnColorChangedListener listener, int color)
static OnColorChangedListener setOnColorChangedListener (OnColorChangedListener listener)
static void setColor (int color)
Protected Member Functions
void onDraw (Canvas canvas)
void onMeasure (int widthMeasureSpec, int heightMeasureSpec)
Private Member Functions
void setupColorPicker ()
void setupSize ()
int floatToByte (float x)
int pinToByte (int n)
int ave (int s, int d, float p)
int interpColor (int colors[], float unit)
int rotateColor (int color, float rad)
void setContextListener ()
Private Attributes
Paint mPaint
Paint mCenterPaint
boolean mTrackingCenter
boolean mHighlightCenter
final int [] mColors
int CENTER_X
int CENTER_Y
int CENTER_RADIUS
Static Private Attributes
static int mColour = 0
static final float PI = 3.1415926f
static OnColorChangedListener mListener
static OnColorChangedListener mContextListener
Detailed Description
Created by Drawn on 2015-03-25.
// introduce this view to an activity, a dialog, etc. setContentView(new ColorPickerView(getContext(), l, mInitialColor));
public class MainActivity implements colorPickerView.OnColorChangedListener
// In this quick example, a custom class, ColorPanelView, is assigned colours mNewColor = (ColorPanelView) layout.findViewById(R.id.new_color_panel);
Definition at line 32 of file colorPickerView.java.
Constructor & Destructor Documentation
colorPickerView()
com.gtfp.workingmemory.colorPicker.colorPickerView.colorPickerView (Context context, AttributeSet attrs)
Definition at line 56 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.setupColorPicker().
Member Function Documentation
setupColorPicker()
void com.gtfp.workingmemory.colorPicker.colorPickerView.setupColorPicker () private
Definition at line 67 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.setContextListener(), and com.gtfp.workingmemory.colorPicker.colorPickerView.setupSize().
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.colorPickerView().
setupSize()
void com.gtfp.workingmemory.colorPicker.colorPickerView.setupSize () private
Definition at line 94 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.setupColorPicker().
onDraw()
void com.gtfp.workingmemory.colorPicker.colorPickerView.onDraw (Canvas canvas) protected
Definition at line 117 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.mCenterPaint.
onMeasure()
void com.gtfp.workingmemory.colorPicker.colorPickerView.onMeasure (int widthMeasureSpec, int heightMeasureSpec) protected
Definition at line 149 of file colorPickerView.java.
floatToByte()
int com.gtfp.workingmemory.colorPicker.colorPickerView.floatToByte (float x) private
Definition at line 153 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.rotateColor().
pinToByte()
int com.gtfp.workingmemory.colorPicker.colorPickerView.pinToByte (int n) private
Definition at line 158 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.rotateColor().
ave()
int com.gtfp.workingmemory.colorPicker.colorPickerView.ave (int s, int d, float p) private
Definition at line 167 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.interpColor().
interpColor()
int com.gtfp.workingmemory.colorPicker.colorPickerView.interpColor (int colors[], float unit) private
Definition at line 171 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.ave().
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent().
rotateColor()
int com.gtfp.workingmemory.colorPicker.colorPickerView.rotateColor (int color, float rad) private
Definition at line 194 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.floatToByte(), and com.gtfp.workingmemory.colorPicker.colorPickerView.pinToByte().
onTouchEvent()
boolean com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent (MotionEvent event)
Definition at line 222 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.CENTER_RADIUS, com.gtfp.workingmemory.colorPicker.colorPickerView.CENTER_X, com.gtfp.workingmemory.colorPicker.colorPickerView.CENTER_Y, com.gtfp.workingmemory.colorPicker.colorPickerView.OnColorChangedListener.colorChanged(), com.gtfp.workingmemory.colorPicker.colorPickerView.interpColor(), com.gtfp.workingmemory.colorPicker.colorPickerView.mContextListener, com.gtfp.workingmemory.colorPicker.colorPickerView.mListener, and com.gtfp.workingmemory.colorPicker.colorPickerView.PI.
init()
static void com.gtfp.workingmemory.colorPicker.colorPickerView.init (OnColorChangedListener listener, int color) static
Definition at line 276 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.setColor(), and com.gtfp.workingmemory.colorPicker.colorPickerView.setOnColorChangedListener().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorWheel().
setOnColorChangedListener()
static OnColorChangedListener com.gtfp.workingmemory.colorPicker.colorPickerView.setOnColorChangedListener (OnColorChangedListener listener) static
Definition at line 284 of file colorPickerView.java.
References com.gtfp.workingmemory.colorPicker.colorPickerView.mListener.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.init(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Manager().
setColor()
static void com.gtfp.workingmemory.colorPicker.colorPickerView.setColor (int color) static
Definition at line 293 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.init(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick().
setContextListener()
void com.gtfp.workingmemory.colorPicker.colorPickerView.setContextListener () private
Definition at line 299 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.setupColorPicker().
Member Data Documentation
mPaint
Paint com.gtfp.workingmemory.colorPicker.colorPickerView.mPaint private
Definition at line 34 of file colorPickerView.java.
mCenterPaint
Paint com.gtfp.workingmemory.colorPicker.colorPickerView.mCenterPaint private
Definition at line 36 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onDraw().
mTrackingCenter
boolean com.gtfp.workingmemory.colorPicker.colorPickerView.mTrackingCenter private
Definition at line 38 of file colorPickerView.java.
mHighlightCenter
boolean com.gtfp.workingmemory.colorPicker.colorPickerView.mHighlightCenter private
Definition at line 40 of file colorPickerView.java.
mColors
final int [] com.gtfp.workingmemory.colorPicker.colorPickerView.mColors private
Initial value:
= new int[]{
            0xFFFF0000, 0xFFFF00FF, 0xFF0000FF, 0xFF00FFFF, 0xFF00FF00,
            0xFFFFFF00, 0xFFFF0000
    }
Definition at line 42 of file colorPickerView.java.
CENTER_X
int com.gtfp.workingmemory.colorPicker.colorPickerView.CENTER_X private
Definition at line 47 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent().
CENTER_Y
int com.gtfp.workingmemory.colorPicker.colorPickerView.CENTER_Y private
Definition at line 49 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent().
CENTER_RADIUS
int com.gtfp.workingmemory.colorPicker.colorPickerView.CENTER_RADIUS private
Definition at line 51 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent().
mColour
int com.gtfp.workingmemory.colorPicker.colorPickerView.mColour = 0 static private
Definition at line 53 of file colorPickerView.java.
PI
final float com.gtfp.workingmemory.colorPicker.colorPickerView.PI = 3.1415926f static private
Definition at line 219 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent().
mListener
OnColorChangedListener com.gtfp.workingmemory.colorPicker.colorPickerView.mListener static private
Definition at line 270 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent(), and com.gtfp.workingmemory.colorPicker.colorPickerView.setOnColorChangedListener().
mContextListener
OnColorChangedListener com.gtfp.workingmemory.colorPicker.colorPickerView.mContextListener static private
Definition at line 272 of file colorPickerView.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerView.onTouchEvent().