Working Memory: com.gtfp.workingmemory.db.Semaphore Class Reference
com.gtfp.workingmemory.db.Semaphore Class Reference
Created by Drawn on 5/4/2017.
Static Public Member Functions
static void write ()
Static Package Functions
static boolean got ()
static boolean got (DataSnapshot snapshot)
Static Private Member Functions
static DatabaseReference DBRef ()
Static Private Attributes
static long mStamp
static long mTimeStamp
Detailed Description
Created by Drawn on 5/4/2017.
Definition at line 13 of file Semaphore.java.
Member Function Documentation
got() [1/2]
static boolean com.gtfp.workingmemory.db.Semaphore.got () static package
Definition at line 22 of file Semaphore.java.
References com.gtfp.workingmemory.db.Semaphore.mTimeStamp.
Referenced by com.gtfp.workingmemory.db.dbFireBase.createCurrentRecs(), com.gtfp.workingmemory.db.Semaphore.got(), com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
got() [2/2]
static boolean com.gtfp.workingmemory.db.Semaphore.got (DataSnapshot snapshot) static package
Definition at line 30 of file Semaphore.java.
References com.gtfp.workingmemory.db.Semaphore.got().
write()
static void com.gtfp.workingmemory.db.Semaphore.write () static
Definition at line 51 of file Semaphore.java.
References com.gtfp.workingmemory.db.Semaphore.DBRef().
Referenced by com.gtfp.workingmemory.db.dbFireBase.markRec(), and com.gtfp.workingmemory.db.dbFireBase.save().
DBRef()
static DatabaseReference com.gtfp.workingmemory.db.Semaphore.DBRef () static private
Definition at line 61 of file Semaphore.java.
References com.gtfp.workingmemory.Auth.Auth.getUid().
Referenced by com.gtfp.workingmemory.db.Semaphore.write().
Member Data Documentation
mStamp
long com.gtfp.workingmemory.db.Semaphore.mStamp static private
Definition at line 15 of file Semaphore.java.
mTimeStamp
long com.gtfp.workingmemory.db.Semaphore.mTimeStamp static private
Definition at line 17 of file Semaphore.java.
Referenced by com.gtfp.workingmemory.db.Semaphore.got().