Working Memory: com.gtfp.workingmemory.Auth.Auth Class Reference
com.gtfp.workingmemory.Auth.Auth Class Reference
Created by Drawn on 9/26/2016.
Classes
class appAuthListener
Static Public Member Functions
static void onCreate (Activity activity)
static void onCreate (FirebaseAuth auth)
static void onCreate (FirebaseAuth.AuthStateListener listener)
static void onCreate (FirebaseAuth auth, FirebaseAuth.AuthStateListener listener)
static void onStart (OnFailureListener listener)
static void onStart (OnSuccessListener< AuthResult > listener)
static void onStart ()
static void onResume (Activity activity)
static void onStop ()
static void addAuthStateListener (FirebaseAuth.AuthStateListener listener)
static void removeAuthStateListener (FirebaseAuth.AuthStateListener listener)
static void signIn ()
static void signIn (OnSuccessListener< AuthResult > listener)
static void signIn (OnFailureListener listener)
static boolean isSignedIn ()
static boolean isLoggedIn ()
static void signOut ()
static void linkAccount ()
static String getUid ()
static String getPrevUid ()
static FirebaseUser getUser ()
static FirebaseUser getPrevUser ()
static String userProfile (String type)
static String userProfile (FirebaseUser user, String type)
static String userProvider ()
static String userEmail ()
static String userName ()
static Uri userPhoto ()
static void onDestroy ()
Static Private Member Functions
static OnCompleteListener< AuthResult > getCompleteListener ()
static void userProfile ()
Static Private Attributes
static Activity mActivity
static FirebaseAuth mAuth
static Task< AuthResult > mAuthResult
static FirebaseUser mUser
static String mUserId
static FirebaseUser mPrevUser
static String mPrevUserId = ""
static String mToken
static String mProviderId
static String mUserName
static String mUserEmail
static Uri mPhotoUrl
static FirebaseAuth.AuthStateListener mAuthListener = new appAuthListener()
Detailed Description
Created by Drawn on 9/26/2016.
Definition at line 22 of file Auth.java.
Member Function Documentation
onCreate() [1/4]
static void com.gtfp.workingmemory.Auth.Auth.onCreate (Activity activity) static
Definition at line 52 of file Auth.java.
Referenced by com.gtfp.workingmemory.app.appController.onCreate(), and com.gtfp.workingmemory.Auth.Auth.onCreate().
onCreate() [2/4]
static void com.gtfp.workingmemory.Auth.Auth.onCreate (FirebaseAuth auth) static
Definition at line 61 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.onCreate().
onCreate() [3/4]
static void com.gtfp.workingmemory.Auth.Auth.onCreate (FirebaseAuth.AuthStateListener listener) static
Definition at line 68 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.onCreate().
onCreate() [4/4]
static void com.gtfp.workingmemory.Auth.Auth.onCreate (FirebaseAuth auth, FirebaseAuth.AuthStateListener listener) static
Definition at line 75 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.addAuthStateListener().
onStart() [1/3]
static void com.gtfp.workingmemory.Auth.Auth.onStart (OnFailureListener listener) static
Definition at line 94 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.onStart(), and com.gtfp.workingmemory.Auth.Auth.signIn().
Referenced by com.gtfp.workingmemory.Auth.Auth.onStart(), and com.gtfp.workingmemory.app.appModel.onStart().
onStart() [2/3]
static void com.gtfp.workingmemory.Auth.Auth.onStart (OnSuccessListener< AuthResult > listener) static
Definition at line 103 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.onStart(), and com.gtfp.workingmemory.Auth.Auth.signIn().
onStart() [3/3]
static void com.gtfp.workingmemory.Auth.Auth.onStart () static
Definition at line 112 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mAuthListener.
onResume()
static void com.gtfp.workingmemory.Auth.Auth.onResume (Activity activity) static
Definition at line 125 of file Auth.java.
onStop()
static void com.gtfp.workingmemory.Auth.Auth.onStop () static
Definition at line 131 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mAuthListener.
Referenced by com.gtfp.workingmemory.Auth.Auth.onDestroy(), and com.gtfp.workingmemory.app.appModel.onStop().
addAuthStateListener()
static void com.gtfp.workingmemory.Auth.Auth.addAuthStateListener (FirebaseAuth.AuthStateListener listener) static
Definition at line 142 of file Auth.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.onLogin.addAuthStateListener(), com.gtfp.workingmemory.db.dbFireBase.dbFireBase(), com.gtfp.workingmemory.Auth.Auth.onCreate(), com.gtfp.workingmemory.app.appView.onOptionsItemSelected(), and com.gtfp.workingmemory.app.appController.onStart().
removeAuthStateListener()
static void com.gtfp.workingmemory.Auth.Auth.removeAuthStateListener (FirebaseAuth.AuthStateListener listener) static
Definition at line 155 of file Auth.java.
Referenced by com.gtfp.workingmemory.app.appController.onStop(), and com.gtfp.workingmemory.db.dbCloud.onLogin.removeAuthStateListener().
signIn() [1/3]
static void com.gtfp.workingmemory.Auth.Auth.signIn () static
Definition at line 166 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.getCompleteListener().
Referenced by com.gtfp.workingmemory.Auth.Auth.onStart(), and com.gtfp.workingmemory.Auth.Auth.signOut().
signIn() [2/3]
static void com.gtfp.workingmemory.Auth.Auth.signIn (OnSuccessListener< AuthResult > listener) static
Definition at line 177 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.getCompleteListener().
signIn() [3/3]
static void com.gtfp.workingmemory.Auth.Auth.signIn (OnFailureListener listener) static
Definition at line 189 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.getCompleteListener().
getCompleteListener()
static OnCompleteListener<AuthResult> com.gtfp.workingmemory.Auth.Auth.getCompleteListener () static private
Definition at line 201 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.signIn().
isSignedIn()
static boolean com.gtfp.workingmemory.Auth.Auth.isSignedIn () static
Definition at line 223 of file Auth.java.
Referenced by com.gtfp.workingmemory.app.appModel.onStart().
isLoggedIn()
static boolean com.gtfp.workingmemory.Auth.Auth.isLoggedIn () static
Definition at line 230 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.userProfile().
Referenced by com.gtfp.workingmemory.db.dbCloud.onLogin.onAuthStateChanged(), and com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu().
signOut()
static void com.gtfp.workingmemory.Auth.Auth.signOut () static
Definition at line 239 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.signIn().
Referenced by com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
linkAccount()
static void com.gtfp.workingmemory.Auth.Auth.linkAccount () static
Definition at line 248 of file Auth.java.
getUid()
static String com.gtfp.workingmemory.Auth.Auth.getUid () static
Definition at line 254 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.getUser().
Referenced by com.gtfp.workingmemory.db.Semaphore.DBRef(), com.gtfp.workingmemory.db.dbCloud.DataSync.deviceDirectory(), com.gtfp.workingmemory.db.dbCloud.DataSync.insert(), com.gtfp.workingmemory.db.dbCloud.DataSync.replace(), com.gtfp.workingmemory.db.dbCloud.DataSync.sync(), com.gtfp.workingmemory.db.dbCloud.DataSync.syncData(), and com.gtfp.workingmemory.db.dbFireBase.tasksRef().
getPrevUid()
static String com.gtfp.workingmemory.Auth.Auth.getPrevUid () static
Definition at line 284 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mPrevUserId.
Referenced by com.gtfp.workingmemory.db.dbFireBase.prevUserIdDBRef(), and com.gtfp.workingmemory.db.dbCloud.reSave().
getUser()
static FirebaseUser com.gtfp.workingmemory.Auth.Auth.getUser () static
Definition at line 291 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.getUid().
getPrevUser()
static FirebaseUser com.gtfp.workingmemory.Auth.Auth.getPrevUser () static
Definition at line 319 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mPrevUser.
userProfile() [1/3]
static String com.gtfp.workingmemory.Auth.Auth.userProfile (String type) static
Definition at line 326 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.userProfile().
Referenced by com.gtfp.workingmemory.db.dbCloud.onLogin.onAuthStateChanged(), and com.gtfp.workingmemory.google.SignInActivity.setupSignInFields().
userProfile() [2/3]
static String com.gtfp.workingmemory.Auth.Auth.userProfile (FirebaseUser user, String type) static
Definition at line 333 of file Auth.java.
userProfile() [3/3]
static void com.gtfp.workingmemory.Auth.Auth.userProfile () static private
Definition at line 394 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.isLoggedIn(), com.gtfp.workingmemory.Auth.Auth.userEmail(), com.gtfp.workingmemory.Auth.Auth.userName(), com.gtfp.workingmemory.Auth.Auth.userPhoto(), com.gtfp.workingmemory.Auth.Auth.userProfile(), and com.gtfp.workingmemory.Auth.Auth.userProvider().
userProvider()
static String com.gtfp.workingmemory.Auth.Auth.userProvider () static
Definition at line 416 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mProviderId, and com.gtfp.workingmemory.Auth.Auth.userProfile().
userEmail()
static String com.gtfp.workingmemory.Auth.Auth.userEmail () static
Definition at line 425 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mUserEmail, and com.gtfp.workingmemory.Auth.Auth.userProfile().
userName()
static String com.gtfp.workingmemory.Auth.Auth.userName () static
Definition at line 434 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mUserName, and com.gtfp.workingmemory.Auth.Auth.userProfile().
userPhoto()
static Uri com.gtfp.workingmemory.Auth.Auth.userPhoto () static
Definition at line 443 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mPhotoUrl, and com.gtfp.workingmemory.Auth.Auth.userProfile().
onDestroy()
static void com.gtfp.workingmemory.Auth.Auth.onDestroy () static
Definition at line 452 of file Auth.java.
References com.gtfp.workingmemory.Auth.Auth.mAuthListener, and com.gtfp.workingmemory.Auth.Auth.onStop().
Referenced by com.gtfp.workingmemory.app.appModel.onDestroy().
Member Data Documentation
mActivity
Activity com.gtfp.workingmemory.Auth.Auth.mActivity static private
Definition at line 24 of file Auth.java.
mAuth
FirebaseAuth com.gtfp.workingmemory.Auth.Auth.mAuth static private
Definition at line 26 of file Auth.java.
mAuthResult
Task<AuthResult> com.gtfp.workingmemory.Auth.Auth.mAuthResult static private
Definition at line 28 of file Auth.java.
mUser
FirebaseUser com.gtfp.workingmemory.Auth.Auth.mUser static private
Definition at line 30 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.appAuthListener.onAuthStateChanged().
mUserId
String com.gtfp.workingmemory.Auth.Auth.mUserId static private
Definition at line 32 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.appAuthListener.onAuthStateChanged().
mPrevUser
FirebaseUser com.gtfp.workingmemory.Auth.Auth.mPrevUser static private
Definition at line 34 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.getPrevUser().
mPrevUserId
String com.gtfp.workingmemory.Auth.Auth.mPrevUserId = "" static private
Definition at line 36 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.getPrevUid().
mToken
String com.gtfp.workingmemory.Auth.Auth.mToken static private
Definition at line 38 of file Auth.java.
mProviderId
String com.gtfp.workingmemory.Auth.Auth.mProviderId static private
Definition at line 40 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.userProvider().
mUserName
String com.gtfp.workingmemory.Auth.Auth.mUserName static private
Definition at line 42 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.userName().
mUserEmail
String com.gtfp.workingmemory.Auth.Auth.mUserEmail static private
Definition at line 44 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.userEmail().
mPhotoUrl
Uri com.gtfp.workingmemory.Auth.Auth.mPhotoUrl static private
Definition at line 46 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.userPhoto().
mAuthListener
FirebaseAuth.AuthStateListener com.gtfp.workingmemory.Auth.Auth.mAuthListener = new appAuthListener() static private
Definition at line 49 of file Auth.java.
Referenced by com.gtfp.workingmemory.Auth.Auth.onDestroy(), com.gtfp.workingmemory.Auth.Auth.onStart(), and com.gtfp.workingmemory.Auth.Auth.onStop().