Working Memory: com.gtfp.workingmemory.todo.ToDoItemsList Class Reference
com.gtfp.workingmemory.todo.ToDoItemsList Class Reference
Classes
class CompareDueDate
interface ToDoIterator
Public Member Functions
void setItems (List< ToDoItem > list)
final List< ToDoItem > ToDoList ()
ToDoItem newToDoItem ()
ToDoItem get (int index)
long getId (int index)
int SelectItemId (ToDoItem itemToDo)
int getListId (ToDoItem itemToDo)
int getListId (long itemId)
int size ()
boolean add (ToDoItem item)
int update (ToDoItem item)
ToDoItem remove (int index)
void setItem (int index, ToDoItem item)
void set (int index, ToDoItem item)
void sortByDueDate ()
void setDueDate (int index, int year, int monthOfYear, int dayOfMonth)
Protected Member Functions
void onDestroy ()
Package Functions
ToDoItemsList (List< ToDoItem > list)
void iterateToDoItems ()
Static Package Functions
static ToDoIterator setIterator (ToDoIterator iterateObj)
Private Member Functions
ToDoItemsList ()
Private Attributes
ArrayList< ToDoItem > mToDoItems
boolean mDescending
Comparator mComparator
Static Private Attributes
static ToDoIterator mIterateObj
Detailed Description
Definition at line 13 of file ToDoItemsList.java.
Constructor & Destructor Documentation
ToDoItemsList() [1/2]
com.gtfp.workingmemory.todo.ToDoItemsList.ToDoItemsList () private
Definition at line 23 of file ToDoItemsList.java.
ToDoItemsList() [2/2]
com.gtfp.workingmemory.todo.ToDoItemsList.ToDoItemsList (List< ToDoItem > list) package
Definition at line 28 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.setItems(), and com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate().
Member Function Documentation
setItems()
void com.gtfp.workingmemory.todo.ToDoItemsList.setItems (List< ToDoItem > list)
Definition at line 37 of file ToDoItemsList.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.setItems(), com.gtfp.workingmemory.todo.ToDoItemsList.ToDoItemsList(), and com.gtfp.workingmemory.todo.ToDoListAdapter.ToDoListAdapter().
ToDoList()
final List<ToDoItem> com.gtfp.workingmemory.todo.ToDoItemsList.ToDoList ()
Definition at line 42 of file ToDoItemsList.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.ToDoList().
newToDoItem()
ToDoItem com.gtfp.workingmemory.todo.ToDoItemsList.newToDoItem ()
Definition at line 47 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch(), and com.gtfp.workingmemory.todo.ToDoItem.TodayInEpoch().
Referenced by com.gtfp.workingmemory.todo.ToDoItemsList.get(), and com.gtfp.workingmemory.todo.ToDoItemsList.remove().
get()
ToDoItem com.gtfp.workingmemory.todo.ToDoItemsList.get (int index)
Definition at line 61 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.newToDoItem().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getItem(), and com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
getId()
long com.gtfp.workingmemory.todo.ToDoItemsList.getId (int index)
Definition at line 83 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getItemId().
SelectItemId()
int com.gtfp.workingmemory.todo.ToDoItemsList.SelectItemId (ToDoItem itemToDo)
Definition at line 94 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.getListId().
getListId() [1/2]
int com.gtfp.workingmemory.todo.ToDoItemsList.getListId (ToDoItem itemToDo)
Definition at line 99 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getListId(), and com.gtfp.workingmemory.todo.ToDoItemsList.SelectItemId().
getListId() [2/2]
int com.gtfp.workingmemory.todo.ToDoItemsList.getListId (long itemId)
Definition at line 104 of file ToDoItemsList.java.
size()
int com.gtfp.workingmemory.todo.ToDoItemsList.size ()
Definition at line 119 of file ToDoItemsList.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.add(), com.gtfp.workingmemory.todo.ToDoListAdapter.remove(), com.gtfp.workingmemory.todo.ToDoListAdapter.setItems(), and com.gtfp.workingmemory.todo.ToDoListAdapter.ToDoListAdapter().
add()
boolean com.gtfp.workingmemory.todo.ToDoItemsList.add (ToDoItem item)
Definition at line 124 of file ToDoItemsList.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.add().
update()
int com.gtfp.workingmemory.todo.ToDoItemsList.update (ToDoItem item)
Definition at line 136 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItem.getListPosn().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.save(), and com.gtfp.workingmemory.todo.ToDoListAdapter.update().
remove()
ToDoItem com.gtfp.workingmemory.todo.ToDoItemsList.remove (int index)
Definition at line 155 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.newToDoItem().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.remove().
setItem()
void com.gtfp.workingmemory.todo.ToDoItemsList.setItem (int index, ToDoItem item)
Definition at line 171 of file ToDoItemsList.java.
set()
void com.gtfp.workingmemory.todo.ToDoItemsList.set (int index, ToDoItem item)
Definition at line 175 of file ToDoItemsList.java.
sortByDueDate()
void com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate ()
Definition at line 179 of file ToDoItemsList.java.
References com.gtfp.workingmemory.settings.appSettings.getBoolean().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.add(), com.gtfp.workingmemory.todo.ToDoListAdapter.save(), com.gtfp.workingmemory.todo.ToDoListAdapter.setItems(), com.gtfp.workingmemory.todo.ToDoListAdapter.sort(), and com.gtfp.workingmemory.todo.ToDoItemsList.ToDoItemsList().
setDueDate()
void com.gtfp.workingmemory.todo.ToDoItemsList.setDueDate (int index, int year, int monthOfYear, int dayOfMonth)
Definition at line 186 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), and com.gtfp.workingmemory.todo.ToDoItem.toString().
iterateToDoItems()
void com.gtfp.workingmemory.todo.ToDoItemsList.iterateToDoItems () package
Definition at line 207 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.ToDoIterator.Iterate().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.Iterate().
setIterator()
static ToDoIterator com.gtfp.workingmemory.todo.ToDoItemsList.setIterator (ToDoIterator iterateObj) static package
Definition at line 230 of file ToDoItemsList.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.mIterateObj.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.Iterate().
onDestroy()
void com.gtfp.workingmemory.todo.ToDoItemsList.onDestroy () protected
Definition at line 245 of file ToDoItemsList.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.onDestroy().
Member Data Documentation
mToDoItems
ArrayList<ToDoItem> com.gtfp.workingmemory.todo.ToDoItemsList.mToDoItems private
Definition at line 15 of file ToDoItemsList.java.
mDescending
boolean com.gtfp.workingmemory.todo.ToDoItemsList.mDescending private
Definition at line 17 of file ToDoItemsList.java.
mComparator
Comparator com.gtfp.workingmemory.todo.ToDoItemsList.mComparator private
Definition at line 19 of file ToDoItemsList.java.
mIterateObj
ToDoIterator com.gtfp.workingmemory.todo.ToDoItemsList.mIterateObj static private
Definition at line 21 of file ToDoItemsList.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItemsList.setIterator().