Working Memory: com.gtfp.workingmemory.todo.ToDoAlarm Class Reference
com.gtfp.workingmemory.todo.ToDoAlarm Class Reference
Created by Drawn on 2015-02-27.
Classes
class Manager
Public Member Functions
void onReceive (Context context, Intent intent)
Private Member Functions
void resetAlarms (Context context)
void showDialogue (Context context, Intent intent)
Static Private Attributes
static final String TAG = ToDoAlarm.class.getSimpleName()
static final String RESET_ALARMS = "android.intent.action.BOOT_COMPLETED"
static final String INTENT_ACTION = "ToDoAlarm"
static final String TODOITEM = "item"
static final String SHOW_POPUP = "showpopup"
static final String CLEAR_NOTIFY = "clear_notification"
static final String ALARM_ID = "id"
Detailed Description
Created by Drawn on 2015-02-27.
Definition at line 31 of file ToDoAlarm.java.
Member Function Documentation
onReceive()
void com.gtfp.workingmemory.todo.ToDoAlarm.onReceive (Context context, Intent intent)
Definition at line 48 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.todo.ToDoAlarm.resetAlarms(), and com.gtfp.workingmemory.todo.ToDoAlarm.showDialogue().
resetAlarms()
void com.gtfp.workingmemory.todo.ToDoAlarm.resetAlarms (Context context) private
Definition at line 75 of file ToDoAlarm.java.
References com.gtfp.workingmemory.app.appView.onDestroy(), com.gtfp.workingmemory.app.appView.open(), and com.gtfp.workingmemory.app.appView.resetAlarms().
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.onReceive().
showDialogue()
void com.gtfp.workingmemory.todo.ToDoAlarm.showDialogue (Context context, Intent intent) private
Definition at line 88 of file ToDoAlarm.java.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.onReceive().
Member Data Documentation
TAG
final String com.gtfp.workingmemory.todo.ToDoAlarm.TAG = ToDoAlarm.class.getSimpleName() static private
Definition at line 33 of file ToDoAlarm.java.
RESET_ALARMS
final String com.gtfp.workingmemory.todo.ToDoAlarm.RESET_ALARMS = "android.intent.action.BOOT_COMPLETED" static private
Definition at line 35 of file ToDoAlarm.java.
INTENT_ACTION
final String com.gtfp.workingmemory.todo.ToDoAlarm.INTENT_ACTION = "ToDoAlarm" static private
Definition at line 37 of file ToDoAlarm.java.
TODOITEM
final String com.gtfp.workingmemory.todo.ToDoAlarm.TODOITEM = "item" static private
Definition at line 39 of file ToDoAlarm.java.
SHOW_POPUP
final String com.gtfp.workingmemory.todo.ToDoAlarm.SHOW_POPUP = "showpopup" static private
Definition at line 41 of file ToDoAlarm.java.
CLEAR_NOTIFY
final String com.gtfp.workingmemory.todo.ToDoAlarm.CLEAR_NOTIFY = "clear_notification" static private
Definition at line 43 of file ToDoAlarm.java.
ALARM_ID
final String com.gtfp.workingmemory.todo.ToDoAlarm.ALARM_ID = "id" static private
Definition at line 45 of file ToDoAlarm.java.