Working Memory: com.gtfp.workingmemory.files.InstallFile Class Reference
com.gtfp.workingmemory.files.InstallFile Class Reference
Created by Drawn on 3/17/2017.
Static Public Member Functions
static synchronized String id (Activity activity)
static boolean justInstalled ()
Static Private Member Functions
static String readInstallationFile (File installFile) throws IOException
static String writeInstallationFile (File installFile, Activity activity) throws IOException
Static Private Attributes
static final String FILE_NAME = ".install"
static String sID = null
static boolean mJustInstalled = false
Detailed Description
Created by Drawn on 3/17/2017.
Definition at line 15 of file InstallFile.java.
Member Function Documentation
id()
static synchronized String com.gtfp.workingmemory.files.InstallFile.id (Activity activity) static
Definition at line 26 of file InstallFile.java.
References com.gtfp.workingmemory.files.InstallFile.FILE_NAME, com.gtfp.workingmemory.files.InstallFile.readInstallationFile(), com.gtfp.workingmemory.files.InstallFile.sID, and com.gtfp.workingmemory.files.InstallFile.writeInstallationFile().
Referenced by com.gtfp.workingmemory.app.appController.getInstallNum(), and com.gtfp.workingmemory.files.InstallFile.writeInstallationFile().
readInstallationFile()
static String com.gtfp.workingmemory.files.InstallFile.readInstallationFile (File installFile) throws IOException static private
Definition at line 55 of file InstallFile.java.
Referenced by com.gtfp.workingmemory.files.InstallFile.id().
writeInstallationFile()
static String com.gtfp.workingmemory.files.InstallFile.writeInstallationFile (File installFile, Activity activity) throws IOException static private
Definition at line 71 of file InstallFile.java.
References com.gtfp.workingmemory.files.InstallFile.id().
Referenced by com.gtfp.workingmemory.files.InstallFile.id().
justInstalled()
static boolean com.gtfp.workingmemory.files.InstallFile.justInstalled () static
Definition at line 92 of file InstallFile.java.
References com.gtfp.workingmemory.files.InstallFile.mJustInstalled.
Referenced by com.gtfp.workingmemory.app.appController.justInstalled().
Member Data Documentation
FILE_NAME
final String com.gtfp.workingmemory.files.InstallFile.FILE_NAME = ".install" static private
Definition at line 17 of file InstallFile.java.
Referenced by com.gtfp.workingmemory.files.InstallFile.id().
sID
String com.gtfp.workingmemory.files.InstallFile.sID = null static private
Definition at line 19 of file InstallFile.java.
Referenced by com.gtfp.workingmemory.files.InstallFile.id().
mJustInstalled
boolean com.gtfp.workingmemory.files.InstallFile.mJustInstalled = false static private
Definition at line 21 of file InstallFile.java.
Referenced by com.gtfp.workingmemory.files.InstallFile.justInstalled().