Working Memory: com.gtfp.workingmemory.app.appModel Class Reference
com.gtfp.workingmemory.app.appModel Class Reference
Created by Drawn on 2015-02-12.
Classes
class onDBSetup
Public Member Functions
appView getView ()
appController getController ()
long getLastRowID ()
boolean save (ToDoItem itemToDo)
boolean delete (ToDoItem itemToDo)
boolean delete (long id)
ArrayList< ToDoItem > ToDoList (Cursor recs)
ArrayList< ToDoItem > ToDoList (ArrayList< HashMap< String, String >> recs)
void onLogin ()
ArrayList< HashMap< String, String > > recArrayList (Cursor query)
Cursor getRecs (String whereClause)
Cursor getRecord (int rowId)
boolean insertIfNewRec ()
Protected Member Functions
void onStart ()
void onDestroy ()
Package Functions
appModel (appView mVc)
dbInterface resetDBHelper ()
boolean open ()
void close ()
boolean trueDelete (ToDoItem itemToDo)
boolean showDeleted ()
ArrayList< ToDoItem > ToDoList ()
Cursor getRecs ()
void importRec (String columnName, String value)
boolean importRec ()
boolean createEmptyTemp ()
boolean insertTempRec ()
Cursor getNewTempRecs ()
void onStop ()
void onRestart ()
Private Member Functions
dbInterface getDBHelper (appView mVc)
boolean showDeleted (boolean showDeleted)
void sync (ArrayList< HashMap< String, String >> dataArrayList)
Private Attributes
appView mAppView
dbInterface mDBHelper
dbInterface m2ndDB
long mLastRowID = 0
boolean mShowDeleted
Detailed Description
Created by Drawn on 2015-02-12.
Definition at line 24 of file appModel.java.
Constructor & Destructor Documentation
appModel()
com.gtfp.workingmemory.app.appModel.appModel (appView mVc) package
Definition at line 43 of file appModel.java.
References com.gtfp.workingmemory.db.dbCloud.addOnLoginListener(), com.gtfp.workingmemory.app.appView.getContext(), com.gtfp.workingmemory.db.dbFireBase.getInstance(), and com.gtfp.workingmemory.db.dbSQLlite.getInstance().
Member Function Documentation
getDBHelper()
dbInterface com.gtfp.workingmemory.app.appModel.getDBHelper (appView mVc) private
Definition at line 66 of file appModel.java.
References com.gtfp.workingmemory.app.appView.getContext(), and com.gtfp.workingmemory.db.dbSQLlite.getInstance().
Referenced by com.gtfp.workingmemory.app.appModel.resetDBHelper().
resetDBHelper()
dbInterface com.gtfp.workingmemory.app.appModel.resetDBHelper () package
Definition at line 73 of file appModel.java.
References com.gtfp.workingmemory.app.appModel.getDBHelper(), com.gtfp.workingmemory.app.appModel.mDBHelper, and com.gtfp.workingmemory.db.dbInterface.onDestroy().
Referenced by com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged().
open()
boolean com.gtfp.workingmemory.app.appModel.open () package
Definition at line 91 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.close(), com.gtfp.workingmemory.db.dbInterface.createCurrentRecs(), com.gtfp.workingmemory.db.dbInterface.isOpen(), and com.gtfp.workingmemory.db.dbInterface.open().
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick(), com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged(), com.gtfp.workingmemory.app.appModel.onStart(), and com.gtfp.workingmemory.app.appView.open().
getView()
appView com.gtfp.workingmemory.app.appModel.getView ()
Definition at line 110 of file appModel.java.
References com.gtfp.workingmemory.app.appModel.mAppView.
Referenced by com.gtfp.workingmemory.db.dbCloud.asyncData.onPostExecute().
getController()
appController com.gtfp.workingmemory.app.appModel.getController ()
Definition at line 117 of file appModel.java.
References com.gtfp.workingmemory.app.appView.getController().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.isOnline().
close()
void com.gtfp.workingmemory.app.appModel.close () package
Definition at line 124 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.close().
Referenced by com.gtfp.workingmemory.app.appView.close(), and com.gtfp.workingmemory.app.appModel.onStop().
getLastRowID()
long com.gtfp.workingmemory.app.appModel.getLastRowID ()
Definition at line 133 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.getLastRowID(), and com.gtfp.workingmemory.app.appModel.mLastRowID.
save()
boolean com.gtfp.workingmemory.app.appModel.save (ToDoItem itemToDo)
Definition at line 145 of file appModel.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getKey(), com.gtfp.workingmemory.db.dbCloud.insert(), com.gtfp.workingmemory.db.dbInterface.isOpen(), com.gtfp.workingmemory.todo.ToDoItem.newItem(), com.gtfp.workingmemory.db.dbInterface.save(), com.gtfp.workingmemory.db.dbCloud.save(), and com.gtfp.workingmemory.app.appModel.sync().
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave(), and com.gtfp.workingmemory.app.appView.save().
delete() [1/2]
boolean com.gtfp.workingmemory.app.appModel.delete (ToDoItem itemToDo)
Definition at line 183 of file appModel.java.
References com.gtfp.workingmemory.db.dbCloud.delete(), com.gtfp.workingmemory.db.dbCloud.insert(), and com.gtfp.workingmemory.db.dbInterface.isOpen().
Referenced by com.gtfp.workingmemory.edit.appCRUD.delete(), com.gtfp.workingmemory.app.appView.delete(), and com.gtfp.workingmemory.app.appView.onPreferenceClick().
delete() [2/2]
boolean com.gtfp.workingmemory.app.appModel.delete (long id)
Definition at line 211 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.markRec().
trueDelete()
boolean com.gtfp.workingmemory.app.appModel.trueDelete (ToDoItem itemToDo) package
Definition at line 218 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.deleteRec(), and com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.app.appView.delete(), and com.gtfp.workingmemory.app.appView.onPreferenceClick().
showDeleted() [1/2]
boolean com.gtfp.workingmemory.app.appModel.showDeleted () package
Definition at line 231 of file appModel.java.
References com.gtfp.workingmemory.app.appModel.mShowDeleted.
Referenced by com.gtfp.workingmemory.app.appModel.showDeleted(), com.gtfp.workingmemory.app.appView.showDeleted(), and com.gtfp.workingmemory.app.appModel.ToDoList().
showDeleted() [2/2]
boolean com.gtfp.workingmemory.app.appModel.showDeleted (boolean showDeleted) private
Definition at line 238 of file appModel.java.
References com.gtfp.workingmemory.app.appModel.mShowDeleted, and com.gtfp.workingmemory.app.appModel.showDeleted().
ToDoList() [1/3]
ArrayList<ToDoItem> com.gtfp.workingmemory.app.appModel.ToDoList () package
Definition at line 247 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.clearResultSet(), com.gtfp.workingmemory.db.dbInterface.getResultSet(), com.gtfp.workingmemory.db.dbInterface.showDeleted(), and com.gtfp.workingmemory.app.appModel.showDeleted().
Referenced by com.gtfp.workingmemory.app.appView.delete(), com.gtfp.workingmemory.app.appView.listToDos(), com.gtfp.workingmemory.app.appView.refreshList(), com.gtfp.workingmemory.app.appView.resetAlarms(), and com.gtfp.workingmemory.app.appView.ToDoList().
ToDoList() [2/3]
ArrayList<ToDoItem> com.gtfp.workingmemory.app.appModel.ToDoList (Cursor recs)
Definition at line 259 of file appModel.java.
References com.gtfp.workingmemory.app.appModel.recArrayList(), and com.gtfp.workingmemory.db.dbInterface.ToDoList().
ToDoList() [3/3]
ArrayList<ToDoItem> com.gtfp.workingmemory.app.appModel.ToDoList (ArrayList< HashMap< String, String >> recs)
Definition at line 266 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.ToDoList().
onLogin()
void com.gtfp.workingmemory.app.appModel.onLogin ()
Implements com.gtfp.workingmemory.db.dbCloud.onLoginListener.
Definition at line 275 of file appModel.java.
References com.gtfp.workingmemory.db.dbCloud.reSave().
recArrayList()
ArrayList<HashMap<String, String> > com.gtfp.workingmemory.app.appModel.recArrayList (Cursor query)
Definition at line 283 of file appModel.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData(), and com.gtfp.workingmemory.app.appModel.ToDoList().
getRecs() [1/2]
Cursor com.gtfp.workingmemory.app.appModel.getRecs () package
Definition at line 323 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.getRecs().
Referenced by com.gtfp.workingmemory.app.appView.createDataFile().
getRecs() [2/2]
Cursor com.gtfp.workingmemory.app.appModel.getRecs (String whereClause)
Definition at line 331 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.getRecs().
getRecord()
Cursor com.gtfp.workingmemory.app.appModel.getRecord (int rowId)
Definition at line 339 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.getRecord().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
importRec() [1/2]
void com.gtfp.workingmemory.app.appModel.importRec (String columnName, String value) package
Definition at line 347 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.bindRecValues().
Referenced by com.gtfp.workingmemory.app.appView.importData(), and com.gtfp.workingmemory.app.appView.importRec().
importRec() [2/2]
boolean com.gtfp.workingmemory.app.appModel.importRec () package
Definition at line 354 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.importRec().
createEmptyTemp()
boolean com.gtfp.workingmemory.app.appModel.createEmptyTemp () package
Definition at line 361 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.createEmptyTemp().
Referenced by com.gtfp.workingmemory.app.appView.createEmptyTemp().
insertTempRec()
boolean com.gtfp.workingmemory.app.appModel.insertTempRec () package
Definition at line 368 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.insertTempRec().
Referenced by com.gtfp.workingmemory.app.appView.insertTempRec().
getNewTempRecs()
Cursor com.gtfp.workingmemory.app.appModel.getNewTempRecs () package
Definition at line 375 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.getNewTempRecs().
Referenced by com.gtfp.workingmemory.app.appView.getNewTempRecs().
insertIfNewRec()
boolean com.gtfp.workingmemory.app.appModel.insertIfNewRec ()
Definition at line 382 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.ifNewRec(), and com.gtfp.workingmemory.db.dbInterface.importRec().
sync()
void com.gtfp.workingmemory.app.appModel.sync (ArrayList< HashMap< String, String >> dataArrayList) private
Definition at line 397 of file appModel.java.
References com.gtfp.workingmemory.db.dbCloud.sync().
Referenced by com.gtfp.workingmemory.app.appModel.onStart(), and com.gtfp.workingmemory.app.appModel.save().
onStart()
void com.gtfp.workingmemory.app.appModel.onStart () protected
Definition at line 415 of file appModel.java.
References com.gtfp.workingmemory.app.appView.getModel(), com.gtfp.workingmemory.Auth.Auth.isSignedIn(), com.gtfp.workingmemory.Auth.Auth.onStart(), com.gtfp.workingmemory.app.appModel.open(), and com.gtfp.workingmemory.app.appModel.sync().
Referenced by com.gtfp.workingmemory.app.appView.onStart().
onStop()
void com.gtfp.workingmemory.app.appModel.onStop () package
Definition at line 452 of file appModel.java.
References com.gtfp.workingmemory.app.appModel.close(), and com.gtfp.workingmemory.Auth.Auth.onStop().
Referenced by com.gtfp.workingmemory.app.appView.onStop().
onRestart()
void com.gtfp.workingmemory.app.appModel.onRestart () package
Definition at line 462 of file appModel.java.
Referenced by com.gtfp.workingmemory.app.appView.onRestart().
onDestroy()
void com.gtfp.workingmemory.app.appModel.onDestroy () protected
Definition at line 470 of file appModel.java.
References com.gtfp.workingmemory.db.dbInterface.onDestroy(), and com.gtfp.workingmemory.Auth.Auth.onDestroy().
Referenced by com.gtfp.workingmemory.app.appView.onDestroy().
Member Data Documentation
mAppView
appView com.gtfp.workingmemory.app.appModel.mAppView private
Definition at line 27 of file appModel.java.
Referenced by com.gtfp.workingmemory.app.appModel.getView().
mDBHelper
dbInterface com.gtfp.workingmemory.app.appModel.mDBHelper private
Definition at line 30 of file appModel.java.
Referenced by com.gtfp.workingmemory.app.appModel.resetDBHelper().
m2ndDB
dbInterface com.gtfp.workingmemory.app.appModel.m2ndDB private
Definition at line 32 of file appModel.java.
mLastRowID
long com.gtfp.workingmemory.app.appModel.mLastRowID = 0 private
Definition at line 35 of file appModel.java.
Referenced by com.gtfp.workingmemory.app.appModel.getLastRowID().
mShowDeleted
boolean com.gtfp.workingmemory.app.appModel.mShowDeleted private
Definition at line 37 of file appModel.java.
Referenced by com.gtfp.workingmemory.app.appModel.showDeleted().