Working Memory: com.gtfp.workingmemory.app.appController Class Reference
com.gtfp.workingmemory.app.appController Class Reference
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
boolean onPrepareOptionsMenu (Menu menu)
void onCreateContextMenu (ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo)
boolean onContextItemSelected (MenuItem item)
void onContentChanged ()
Method getPMmethod ()
void onRequestPermissionsResult (int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults)
Object getPM ()
int getSignature ()
Certificate [] GetApplicationCertifications ()
String getInstallNum ()
boolean justInstalled ()
String NoConnectivity ()
boolean inAirplaneMode ()
appView getView ()
appModel getModel ()
void onStart ()
Public Member Functions inherited from com.gtfp.workingmemory.frmwrk.frmwrkActivity
View onCreateView (String name, Context context, AttributeSet attrs)
final boolean DebugFlagSet ()
Static Public Attributes
static final int REQUEST_PERMISSION_CODE = 0x11
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onActivityResult (int requestCode, int resultCode, Intent data)
void onNewIntent (Intent intent)
void onSaveInstanceState (Bundle outState)
void onRestoreInstanceState (Bundle savedInstanceState)
void onResume ()
void onPause ()
void onStop ()
void onRestart ()
void onDestroy ()
Protected Member Functions inherited from com.gtfp.workingmemory.frmwrk.frmwrkActivity
void onCreate (Bundle savedInstanceState)
void onStart ()
void onResume ()
void onPause ()
Called when activity resume is complete (after onResume has been called).
void onRestart ()
void onStop ()
void onDestroy ()
void onSaveInstanceState (Bundle outState)
void onRestoreInstanceState (Bundle savedInstanceState)
void onPostCreate (Bundle savedInstanceState)
final Boolean justCreated ()
final Boolean wasStopped ()
final Boolean wasPaused ()
final Boolean wasRecreated ()
final Boolean wasCalledOutside ()
Static Package Attributes
static final String TAG = appController.class.getSimpleName()
Private Attributes
appView mAppView
Context mContext
Static Private Attributes
static ConnectivityManager mConnectMngr
Additional Inherited Members
Static Protected Attributes inherited from com.gtfp.workingmemory.frmwrk.frmwrkActivity
static String PACKAGE_NAME = ""
static String INTENT_PACKAGE_NAME = ""
Detailed Description
Definition at line 35 of file appController.java.
Member Function Documentation
onCreate()
void com.gtfp.workingmemory.app.appController.onCreate (Bundle savedInstanceState) protected
Definition at line 49 of file appController.java.
References com.gtfp.workingmemory.settings.appSettings.get(), com.gtfp.workingmemory.Auth.Auth.onCreate(), com.gtfp.workingmemory.db.dbCloud.onCreate(), and com.gtfp.workingmemory.app.appView.onCreate().
onCreateOptionsMenu()
boolean com.gtfp.workingmemory.app.appController.onCreateOptionsMenu (Menu menu)
Definition at line 68 of file appController.java.
References com.gtfp.workingmemory.app.appView.onCreateOptionsMenu().
onOptionsItemSelected()
boolean com.gtfp.workingmemory.app.appController.onOptionsItemSelected (MenuItem item)
Definition at line 75 of file appController.java.
References com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
onPrepareOptionsMenu()
boolean com.gtfp.workingmemory.app.appController.onPrepareOptionsMenu (Menu menu)
Definition at line 81 of file appController.java.
References com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu().
onCreateContextMenu()
void com.gtfp.workingmemory.app.appController.onCreateContextMenu (ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo)
Definition at line 94 of file appController.java.
References com.gtfp.workingmemory.app.appView.onCreateContextMenu().
onContextItemSelected()
boolean com.gtfp.workingmemory.app.appController.onContextItemSelected (MenuItem item)
Definition at line 101 of file appController.java.
References com.gtfp.workingmemory.app.appView.onContextItemSelected().
Referenced by com.gtfp.workingmemory.app.appView.onContextItemSelected().
onActivityResult()
void com.gtfp.workingmemory.app.appController.onActivityResult (int requestCode, int resultCode, Intent data) protected
Definition at line 115 of file appController.java.
References com.gtfp.workingmemory.app.appView.onActivityResult().
onNewIntent()
void com.gtfp.workingmemory.app.appController.onNewIntent (Intent intent) protected
Definition at line 124 of file appController.java.
References com.gtfp.workingmemory.app.appView.onNewIntent().
onSaveInstanceState()
void com.gtfp.workingmemory.app.appController.onSaveInstanceState (Bundle outState) protected
Definition at line 131 of file appController.java.
References com.gtfp.workingmemory.app.appView.onSaveInstanceState().
onRestoreInstanceState()
void com.gtfp.workingmemory.app.appController.onRestoreInstanceState (Bundle savedInstanceState) protected
Definition at line 141 of file appController.java.
References com.gtfp.workingmemory.app.appView.onRestoreInstanceState().
onContentChanged()
void com.gtfp.workingmemory.app.appController.onContentChanged ()
Definition at line 150 of file appController.java.
getPMmethod()
Method com.gtfp.workingmemory.app.appController.getPMmethod ()
Definition at line 154 of file appController.java.
References com.gtfp.workingmemory.app.App.getPM().
Referenced by com.gtfp.workingmemory.app.appController.getPM().
onRequestPermissionsResult()
void com.gtfp.workingmemory.app.appController.onRequestPermissionsResult (int requestCode, @NonNull String [] permissions, @NonNull int [] grantResults)
Definition at line 170 of file appController.java.
getPM()
Object com.gtfp.workingmemory.app.appController.getPM ()
Definition at line 189 of file appController.java.
References com.gtfp.workingmemory.app.appController.getPMmethod().
Referenced by com.gtfp.workingmemory.app.appView.getPI(), and com.gtfp.workingmemory.app.appView.getPImethod().
getSignature()
int com.gtfp.workingmemory.app.appController.getSignature ()
Definition at line 205 of file appController.java.
References com.gtfp.workingmemory.app.appView.getPI().
Referenced by com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu().
GetApplicationCertifications()
Certificate [] com.gtfp.workingmemory.app.appController.GetApplicationCertifications ()
Definition at line 211 of file appController.java.
getInstallNum()
String com.gtfp.workingmemory.app.appController.getInstallNum ()
Definition at line 236 of file appController.java.
References com.gtfp.workingmemory.files.InstallFile.id().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.onCreate().
justInstalled()
boolean com.gtfp.workingmemory.app.appController.justInstalled ()
Definition at line 244 of file appController.java.
References com.gtfp.workingmemory.files.InstallFile.justInstalled().
NoConnectivity()
String com.gtfp.workingmemory.app.appController.NoConnectivity ()
Definition at line 252 of file appController.java.
References com.gtfp.workingmemory.app.appController.inAirplaneMode().
Referenced by com.gtfp.workingmemory.db.dbFireBase.isOnline(), com.gtfp.workingmemory.db.dbCloud.DataSync.isOnline(), com.gtfp.workingmemory.app.appView.onAuthStateChanged(), and com.gtfp.workingmemory.app.appView.signInApp.onAuthStateChanged().
inAirplaneMode()
boolean com.gtfp.workingmemory.app.appController.inAirplaneMode ()
Definition at line 296 of file appController.java.
Referenced by com.gtfp.workingmemory.app.appController.NoConnectivity().
getView()
appView com.gtfp.workingmemory.app.appController.getView ()
Definition at line 313 of file appController.java.
References com.gtfp.workingmemory.app.appController.mAppView.
getModel()
appModel com.gtfp.workingmemory.app.appController.getModel ()
Definition at line 321 of file appController.java.
References com.gtfp.workingmemory.app.appView.getModel(), and com.gtfp.workingmemory.app.appController.mAppView.
Referenced by com.gtfp.workingmemory.db.dbCloud.dbCloud(), and com.gtfp.workingmemory.db.dbCloud.DataSync.onCreate().
onStart()
void com.gtfp.workingmemory.app.appController.onStart ()
Definition at line 330 of file appController.java.
References com.gtfp.workingmemory.Auth.Auth.addAuthStateListener(), com.gtfp.workingmemory.app.appController.mAppView, com.gtfp.workingmemory.db.dbCloud.onStart(), and com.gtfp.workingmemory.app.appView.onStart().
onResume()
void com.gtfp.workingmemory.app.appController.onResume () protected
Definition at line 341 of file appController.java.
onPause()
void com.gtfp.workingmemory.app.appController.onPause () protected
Definition at line 346 of file appController.java.
References com.gtfp.workingmemory.app.appController.mAppView, and com.gtfp.workingmemory.app.appView.onPause().
onStop()
void com.gtfp.workingmemory.app.appController.onStop () protected
Definition at line 353 of file appController.java.
References com.gtfp.workingmemory.app.appController.mAppView, com.gtfp.workingmemory.db.dbCloud.onStop(), com.gtfp.workingmemory.app.appView.onStop(), and com.gtfp.workingmemory.Auth.Auth.removeAuthStateListener().
onRestart()
void com.gtfp.workingmemory.app.appController.onRestart () protected
Definition at line 364 of file appController.java.
References com.gtfp.workingmemory.app.appController.mAppView, and com.gtfp.workingmemory.app.appView.onRestart().
onDestroy()
void com.gtfp.workingmemory.app.appController.onDestroy () protected
Definition at line 371 of file appController.java.
References com.gtfp.workingmemory.app.appController.mAppView, com.gtfp.workingmemory.app.appController.mConnectMngr, com.gtfp.workingmemory.app.appController.mContext, com.gtfp.workingmemory.db.dbCloud.onDestroy(), and com.gtfp.workingmemory.app.appView.onDestroy().
Member Data Documentation
TAG
final String com.gtfp.workingmemory.app.appController.TAG = appController.class.getSimpleName() static package
Definition at line 37 of file appController.java.
mAppView
appView com.gtfp.workingmemory.app.appController.mAppView private
Definition at line 39 of file appController.java.
Referenced by com.gtfp.workingmemory.app.appController.getModel(), com.gtfp.workingmemory.app.appController.getView(), com.gtfp.workingmemory.app.appController.onDestroy(), com.gtfp.workingmemory.app.appController.onPause(), com.gtfp.workingmemory.app.appController.onRestart(), com.gtfp.workingmemory.app.appController.onStart(), and com.gtfp.workingmemory.app.appController.onStop().
REQUEST_PERMISSION_CODE
final int com.gtfp.workingmemory.app.appController.REQUEST_PERMISSION_CODE = 0x11 static
Definition at line 41 of file appController.java.
mContext
Context com.gtfp.workingmemory.app.appController.mContext private
Definition at line 43 of file appController.java.
Referenced by com.gtfp.workingmemory.app.appController.onDestroy().
mConnectMngr
ConnectivityManager com.gtfp.workingmemory.app.appController.mConnectMngr static private
Definition at line 45 of file appController.java.
Referenced by com.gtfp.workingmemory.app.appController.onDestroy().