Working Memory: com.gtfp.workingmemory.db.dbFireBase.dbTasksData Class Reference
com.gtfp.workingmemory.db.dbFireBase.dbTasksData Class Reference
Public Member Functions
void onDataChange (DataSnapshot snapshot)
void onCancelled (DatabaseError databaseError)
Detailed Description
Definition at line 1219 of file dbFireBase.java.
Member Function Documentation
onDataChange()
void com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange (DataSnapshot snapshot)
Definition at line 1222 of file dbFireBase.java.
References com.gtfp.workingmemory.db.Semaphore.got(), com.gtfp.workingmemory.db.dbFireBase.mAppView, com.gtfp.workingmemory.db.dbFireBase.mDataArrayList, com.gtfp.workingmemory.db.dbFireBase.mOnDataListeners, com.gtfp.workingmemory.db.dbFireBase.mShowDeleted, com.gtfp.workingmemory.app.appView.onDataChange(), and com.gtfp.workingmemory.db.dbFireBase.recArrayList().
onCancelled()
void com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onCancelled (DatabaseError databaseError)
Definition at line 1252 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.mAppView, and com.gtfp.workingmemory.app.appView.onCancelled().