Working Memory: com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper Class Reference
com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper Class Reference
Inner Class.
Public Member Functions
void onCreate (SQLiteDatabase db)
void onConfigure (SQLiteDatabase db)
void onOpen (SQLiteDatabase db)
int update (ContentValues recValues, long id)
long insert (ContentValues recValues)
int delete (Long rowID)
int delete (Integer rowID)
int delete (String rowID)
long getRowID (long recId)
void onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion)
boolean currentRecs ()
SQLHelper open ()
boolean isOpen ()
boolean drop ()
boolean drop (SQLiteDatabase db)
void close ()
SQLiteDatabase getDatabase ()
Cursor runQuery (String sqlStmt)
Package Functions
SQLHelper (Context context)
Private Member Functions
void setTheGrade (SQLiteDatabase db, int oldVersion, int newVersion)
void execSqlFile (String sqlFile, SQLiteDatabase db) throws SQLException, IOException
Private Attributes
AssetManager mAssetManager
Detailed Description
Inner Class.
Definition at line 248 of file SQLiteHelper.java.
Constructor & Destructor Documentation
SQLHelper()
com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.SQLHelper (Context context) package
Definition at line 255 of file SQLiteHelper.java.
Member Function Documentation
onCreate()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.onCreate (SQLiteDatabase db)
Definition at line 266 of file SQLiteHelper.java.
onConfigure()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.onConfigure (SQLiteDatabase db)
Definition at line 282 of file SQLiteHelper.java.
onOpen()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.onOpen (SQLiteDatabase db)
Definition at line 297 of file SQLiteHelper.java.
update()
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.update (ContentValues recValues, long id)
Definition at line 311 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.update().
insert()
long com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.insert (ContentValues recValues)
Definition at line 333 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.insert().
delete() [1/3]
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.delete (Long rowID)
Definition at line 352 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.delete().
delete() [2/3]
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.delete (Integer rowID)
Definition at line 360 of file SQLiteHelper.java.
delete() [3/3]
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.delete (String rowID)
Definition at line 368 of file SQLiteHelper.java.
getRowID()
long com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.getRowID (long recId)
Definition at line 387 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery().
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getRowID().
onUpgrade()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion)
Definition at line 419 of file SQLiteHelper.java.
currentRecs()
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.currentRecs ()
Definition at line 427 of file SQLiteHelper.java.
open()
SQLHelper com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.open ()
Definition at line 444 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.isOpen().
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.open().
isOpen()
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.isOpen ()
Definition at line 472 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.isOpen().
drop() [1/2]
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.drop ()
Definition at line 480 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.drop().
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.drop().
drop() [2/2]
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.drop (SQLiteDatabase db)
Definition at line 488 of file SQLiteHelper.java.
close()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.close ()
Definition at line 511 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.close().
getDatabase()
SQLiteDatabase com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.getDatabase ()
Definition at line 539 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mDB.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getDatabase().
runQuery()
Cursor com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.runQuery (String sqlStmt)
Definition at line 547 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery().
setTheGrade()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.setTheGrade (SQLiteDatabase db, int oldVersion, int newVersion) private
Definition at line 567 of file SQLiteHelper.java.
References com.gtfp.workingmemory.db.dbSQLParser.list().
execSqlFile()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.execSqlFile (String sqlFile, SQLiteDatabase db) throws SQLException, IOException private
Definition at line 601 of file SQLiteHelper.java.
Member Data Documentation
mAssetManager
AssetManager com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.mAssetManager private
Definition at line 251 of file SQLiteHelper.java.