Working Memory: com.gtfp.workingmemory.frmwrk.db.SQLiteHelper Class Reference
com.gtfp.workingmemory.frmwrk.db.SQLiteHelper Class Reference
Created by Drawn on 3/5/2017.
Classes
interface OnConfigureListener
interface OnOpenListener
class SQLHelper
Inner Class.
Public Member Functions
SQLiteHelper (@NonNull Context context, @NonNull String dbName, @NonNull int dbVersion, @NonNull String tableDef)
SQLiteHelper open ()
boolean isOpen ()
SQLiteDatabase getDatabase ()
SQLiteHelper close ()
String getName ()
int getVersion ()
long insert (ContentValues recValues)
int update (ContentValues recValues, long rowId)
int delete (Long rowID)
int delete (Integer rowID)
int delete (String rowID)
long getRowID (long recId)
Cursor runQuery (String sqlStmt)
boolean drop ()
boolean drop (SQLiteDatabase db)
void setOnOpenListener (OnOpenListener listener)
void setOnConfigureListener (OnConfigureListener listener)
Private Attributes
final String mDBName
final String mSchema
int mDBVersion
SQLiteDatabase mDB
Cursor mResultSet
SQLHelper mSQLHelper
Set< OnOpenListener > mOnOpenListeners = new HashSet<>()
Set< OnConfigureListener > mOnConfigureListeners = new HashSet<>()
Static Private Attributes
static final String SQL_DIR = "sql"
static final String UPGRADEFILE_PREFIX = "upgrade-"
static final String UPGRADEFILE_SUFFIX = ".sql"
static final String DBKEY_FIELD = "rowid"
Detailed Description
Created by Drawn on 3/5/2017.
Definition at line 24 of file SQLiteHelper.java.
Constructor & Destructor Documentation
SQLiteHelper()
com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLiteHelper (@NonNull Context context, @NonNull String dbName, @NonNull int dbVersion, @NonNull String tableDef)
Definition at line 55 of file SQLiteHelper.java.
Member Function Documentation
open()
SQLiteHelper com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.open ()
Definition at line 88 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.open().
Referenced by com.gtfp.workingmemory.db.dbCloud.open(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery().
isOpen()
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.isOpen ()
Definition at line 98 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.isOpen().
Referenced by com.gtfp.workingmemory.db.dbCloud.open(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.open().
getDatabase()
SQLiteDatabase com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getDatabase ()
Definition at line 106 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.getDatabase().
close()
SQLiteHelper com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.close ()
Definition at line 114 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.close().
Referenced by com.gtfp.workingmemory.db.dbCloud.onDestroy().
getName()
String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getName ()
Definition at line 124 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mDBName.
getVersion()
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getVersion ()
Definition at line 132 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mDBVersion.
insert()
long com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.insert (ContentValues recValues)
Definition at line 140 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.insert().
Referenced by com.gtfp.workingmemory.db.dbCloud.insertNew(), and com.gtfp.workingmemory.db.dbCloud.update().
update()
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.update (ContentValues recValues, long rowId)
Definition at line 148 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.update().
Referenced by com.gtfp.workingmemory.db.dbCloud.update().
delete() [1/3]
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.delete (Long rowID)
Definition at line 156 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.delete().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData(), and com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
delete() [2/3]
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.delete (Integer rowID)
Definition at line 164 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.delete().
delete() [3/3]
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.delete (String rowID)
Definition at line 172 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.delete().
getRowID()
long com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getRowID (long recId)
Definition at line 178 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.getRowID().
Referenced by com.gtfp.workingmemory.db.dbCloud.insertNew(), and com.gtfp.workingmemory.db.dbCloud.update().
runQuery()
Cursor com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery (String sqlStmt)
Definition at line 188 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.open(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.runQuery().
Referenced by com.gtfp.workingmemory.db.dbCloud.getAction(), com.gtfp.workingmemory.db.dbCloud.getRec(), com.gtfp.workingmemory.db.dbCloud.getRecs(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.getRowID().
drop() [1/2]
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.drop ()
Definition at line 198 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.drop().
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.drop(), and com.gtfp.workingmemory.db.dbCloud.recreate().
drop() [2/2]
boolean com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.drop (SQLiteDatabase db)
Definition at line 206 of file SQLiteHelper.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.drop().
setOnOpenListener()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.setOnOpenListener (OnOpenListener listener)
Definition at line 214 of file SQLiteHelper.java.
setOnConfigureListener()
void com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.setOnConfigureListener (OnConfigureListener listener)
Definition at line 222 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.recreate().
Member Data Documentation
SQL_DIR
final String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQL_DIR = "sql" static private
Definition at line 27 of file SQLiteHelper.java.
UPGRADEFILE_PREFIX
final String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.UPGRADEFILE_PREFIX = "upgrade-" static private
Definition at line 29 of file SQLiteHelper.java.
UPGRADEFILE_SUFFIX
final String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.UPGRADEFILE_SUFFIX = ".sql" static private
Definition at line 31 of file SQLiteHelper.java.
DBKEY_FIELD
final String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.DBKEY_FIELD = "rowid" static private
Definition at line 34 of file SQLiteHelper.java.
mDBName
final String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mDBName private
Definition at line 36 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getName().
mSchema
final String com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mSchema private
Definition at line 38 of file SQLiteHelper.java.
mDBVersion
int com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mDBVersion private
Definition at line 40 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getVersion().
mDB
SQLiteDatabase com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mDB private
Definition at line 42 of file SQLiteHelper.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.getDatabase().
mResultSet
Cursor com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mResultSet private
Definition at line 44 of file SQLiteHelper.java.
mSQLHelper
SQLHelper com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mSQLHelper private
Definition at line 46 of file SQLiteHelper.java.
mOnOpenListeners
Set<OnOpenListener> com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mOnOpenListeners = new HashSet<>() private
Definition at line 48 of file SQLiteHelper.java.
mOnConfigureListeners
Set<OnConfigureListener> com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.mOnConfigureListeners = new HashSet<>() private
Definition at line 50 of file SQLiteHelper.java.