Working Memory: com.gtfp.workingmemory.app.App Class Reference
com.gtfp.workingmemory.app.App Class Reference
Created by Drawn on 2016-03-09.
Public Member Functions
void onCreate ()
Static Public Member Functions
static String setPackageName (Activity activity)
static String PackageName ()
static File getFilesDir (Context context)
static File FilesDir ()
static String setLabel (Context pContext)
static String getLabel (Context pContext)
static String getLabel ()
static void setView (appView view)
static appView getView () throws NullPointerException
static void setModel (appModel model)
static appModel getModel () throws NullPointerException
static String getPM ()
static String getPI ()
static boolean inDebugger ()
static void waitForDebugger ()
static void onDestroy ()
Protected Member Functions
void attachBaseContext (Context base)
Static Private Attributes
static String PACKAGE_NAME = "package.name.unknown"
static File FILES_DIR
static String LABEL
static appView VIEW
static appModel MODEL
static String PM = new String(Base64.decode("Z2V0UGFja2FnZU1hbmFnZXI=\n", 0))
static String PI = new String(Base64.decode("Z2V0UGFja2FnZUluZm8=\n", 0))
Detailed Description
Created by Drawn on 2016-03-09.
Definition at line 34 of file App.java.
Member Function Documentation
onCreate()
void com.gtfp.workingmemory.app.App.onCreate ()
Definition at line 50 of file App.java.
attachBaseContext()
void com.gtfp.workingmemory.app.App.attachBaseContext (Context base) protected
Definition at line 59 of file App.java.
setPackageName()
static String com.gtfp.workingmemory.app.App.setPackageName (Activity activity) static
Definition at line 69 of file App.java.
References com.gtfp.workingmemory.app.App.PACKAGE_NAME.
Referenced by com.gtfp.workingmemory.app.appView.getPackageName().
PackageName()
static String com.gtfp.workingmemory.app.App.PackageName () static
Definition at line 80 of file App.java.
References com.gtfp.workingmemory.app.App.PACKAGE_NAME.
Referenced by com.gtfp.workingmemory.google.googleAPI.getFolderQuery(), and com.gtfp.workingmemory.google.googleAPI.getID().
getFilesDir()
static File com.gtfp.workingmemory.app.App.getFilesDir (Context context) static
Definition at line 86 of file App.java.
References com.gtfp.workingmemory.app.App.FILES_DIR.
Referenced by com.gtfp.workingmemory.app.appView.appDir().
FilesDir()
static File com.gtfp.workingmemory.app.App.FilesDir () static
Definition at line 97 of file App.java.
References com.gtfp.workingmemory.app.App.FILES_DIR.
setLabel()
static String com.gtfp.workingmemory.app.App.setLabel (Context pContext) static
Definition at line 109 of file App.java.
References com.gtfp.workingmemory.app.App.LABEL.
Referenced by com.gtfp.workingmemory.app.appView.appView(), and com.gtfp.workingmemory.app.App.getLabel().
getLabel() [1/2]
static String com.gtfp.workingmemory.app.App.getLabel (Context pContext) static
Definition at line 130 of file App.java.
References com.gtfp.workingmemory.app.App.LABEL, and com.gtfp.workingmemory.app.App.setLabel().
getLabel() [2/2]
static String com.gtfp.workingmemory.app.App.getLabel () static
Definition at line 141 of file App.java.
References com.gtfp.workingmemory.app.App.LABEL.
setView()
static void com.gtfp.workingmemory.app.App.setView (appView view) static
Definition at line 152 of file App.java.
Referenced by com.gtfp.workingmemory.app.appView.appView().
getView()
static appView com.gtfp.workingmemory.app.App.getView () throws NullPointerException static
Definition at line 161 of file App.java.
References com.gtfp.workingmemory.app.App.VIEW.
setModel()
static void com.gtfp.workingmemory.app.App.setModel (appModel model) static
Definition at line 172 of file App.java.
Referenced by com.gtfp.workingmemory.app.appView.appView().
getModel()
static appModel com.gtfp.workingmemory.app.App.getModel () throws NullPointerException static
Definition at line 181 of file App.java.
References com.gtfp.workingmemory.app.App.MODEL.
getPM()
static String com.gtfp.workingmemory.app.App.getPM () static
Definition at line 192 of file App.java.
References com.gtfp.workingmemory.app.App.PM.
Referenced by com.gtfp.workingmemory.app.appController.getPMmethod().
getPI()
static String com.gtfp.workingmemory.app.App.getPI () static
Definition at line 198 of file App.java.
References com.gtfp.workingmemory.app.App.PI.
Referenced by com.gtfp.workingmemory.app.appView.getPImethod().
inDebugger()
static boolean com.gtfp.workingmemory.app.App.inDebugger () static
Definition at line 207 of file App.java.
Referenced by com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu(), com.gtfp.workingmemory.app.appView.onThrowError(), and com.gtfp.workingmemory.app.App.waitForDebugger().
waitForDebugger()
static void com.gtfp.workingmemory.app.App.waitForDebugger () static
Definition at line 218 of file App.java.
References com.gtfp.workingmemory.app.App.inDebugger().
onDestroy()
static void com.gtfp.workingmemory.app.App.onDestroy () static
Definition at line 229 of file App.java.
Referenced by com.gtfp.workingmemory.app.appView.onDestroy().
Member Data Documentation
PACKAGE_NAME
String com.gtfp.workingmemory.app.App.PACKAGE_NAME = "package.name.unknown" static private
Definition at line 36 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.PackageName(), and com.gtfp.workingmemory.app.App.setPackageName().
FILES_DIR
File com.gtfp.workingmemory.app.App.FILES_DIR static private
Definition at line 38 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.FilesDir(), and com.gtfp.workingmemory.app.App.getFilesDir().
LABEL
String com.gtfp.workingmemory.app.App.LABEL static private
Definition at line 40 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.getLabel(), and com.gtfp.workingmemory.app.App.setLabel().
VIEW
appView com.gtfp.workingmemory.app.App.VIEW static private
Definition at line 42 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.getView().
MODEL
appModel com.gtfp.workingmemory.app.App.MODEL static private
Definition at line 44 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.getModel().
PM
String com.gtfp.workingmemory.app.App.PM = new String(Base64.decode("Z2V0UGFja2FnZU1hbmFnZXI=\n", 0)) static private
Definition at line 238 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.getPM().
PI
String com.gtfp.workingmemory.app.App.PI = new String(Base64.decode("Z2V0UGFja2FnZUluZm8=\n", 0)) static private
Definition at line 240 of file App.java.
Referenced by com.gtfp.workingmemory.app.App.getPI().