Working Memory: com.gtfp.workingmemory.colorPicker.colorPickerActivity Class Reference
com.gtfp.workingmemory.colorPicker.colorPickerActivity Class Reference
Created by Drawn on 2015-03-25.
Public Member Functions
void colorChanged (int colour)
void onItemSelected (AdapterView<?> parent, View view, int pos, long id)
void onNothingSelected (AdapterView<?> parent)
Static Public Member Functions
static Intent getLEDRates ()
static void OnActivityResult (Intent data, SharedPreferences.Editor editor)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void setLEDSettings ()
Private Attributes
Spinner mLedOnMs
Spinner mLedOffMs
Intent mIntent
Detailed Description
Created by Drawn on 2015-03-25.
Definition at line 19 of file colorPickerActivity.java.
Member Function Documentation
onCreate()
void com.gtfp.workingmemory.colorPicker.colorPickerActivity.onCreate (Bundle savedInstanceState) protected
Definition at line 29 of file colorPickerActivity.java.
References com.gtfp.workingmemory.colorPicker.colorPickerActivity.setLEDSettings().
setLEDSettings()
void com.gtfp.workingmemory.colorPicker.colorPickerActivity.setLEDSettings () private
Definition at line 46 of file colorPickerActivity.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerActivity.onCreate().
getLEDRates()
static Intent com.gtfp.workingmemory.colorPicker.colorPickerActivity.getLEDRates () static
Definition at line 103 of file colorPickerActivity.java.
References com.gtfp.workingmemory.settings.appSettings.getInt().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorWheel().
OnActivityResult()
static void com.gtfp.workingmemory.colorPicker.colorPickerActivity.OnActivityResult (Intent data, SharedPreferences.Editor editor) static
Definition at line 115 of file colorPickerActivity.java.
colorChanged()
void com.gtfp.workingmemory.colorPicker.colorPickerActivity.colorChanged (int colour)
Implements com.gtfp.workingmemory.colorPicker.colorPickerView.OnColorChangedListener.
Definition at line 138 of file colorPickerActivity.java.
onItemSelected()
void com.gtfp.workingmemory.colorPicker.colorPickerActivity.onItemSelected (AdapterView<?> parent, View view, int pos, long id)
Definition at line 151 of file colorPickerActivity.java.
onNothingSelected()
void com.gtfp.workingmemory.colorPicker.colorPickerActivity.onNothingSelected (AdapterView<?> parent)
Definition at line 185 of file colorPickerActivity.java.
Member Data Documentation
mLedOnMs
Spinner com.gtfp.workingmemory.colorPicker.colorPickerActivity.mLedOnMs private
Definition at line 22 of file colorPickerActivity.java.
mLedOffMs
Spinner com.gtfp.workingmemory.colorPicker.colorPickerActivity.mLedOffMs private
Definition at line 24 of file colorPickerActivity.java.
mIntent
Intent com.gtfp.workingmemory.colorPicker.colorPickerActivity.mIntent private
Definition at line 26 of file colorPickerActivity.java.