Working Memory: com.gtfp.workingmemory.utils.dialog Class Reference
com.gtfp.workingmemory.utils.dialog Class Reference
Created by Drawn on 2015-03-01.
Classes
interface DialogBoxListener
class Dialogue
Public Member Functions
dialog ()
dialog (Context context)
void show (CharSequence message)
void showBox (CharSequence message)
void show (CharSequence message, int buttons)
void onDestroy ()
DialogBoxListener setDialogBoxListener (DialogBoxListener listener)
Static Public Attributes
static final int REQUEST_CODE = dialog.class.hashCode()
static final int YESNO = 1
Private Attributes
Dialogue mDialogue
DialogBoxListener mListener
Context mContext
Detailed Description
Created by Drawn on 2015-03-01.
Definition at line 16 of file dialog.java.
Constructor & Destructor Documentation
dialog() [1/2]
com.gtfp.workingmemory.utils.dialog.dialog ()
Definition at line 31 of file dialog.java.
dialog() [2/2]
com.gtfp.workingmemory.utils.dialog.dialog (Context context)
Definition at line 34 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.setDialogBoxListener().
Member Function Documentation
show() [1/2]
void com.gtfp.workingmemory.utils.dialog.show (CharSequence message)
Definition at line 45 of file dialog.java.
Referenced by com.gtfp.workingmemory.app.appView.delete(), com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick(), and com.gtfp.workingmemory.utils.dialog.showBox().
showBox()
void com.gtfp.workingmemory.utils.dialog.showBox (CharSequence message)
Definition at line 51 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.show().
Referenced by com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
show() [2/2]
void com.gtfp.workingmemory.utils.dialog.show (CharSequence message, int buttons)
Definition at line 57 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.Dialogue.setMessage(), and com.gtfp.workingmemory.utils.dialog.Dialogue.show().
onDestroy()
void com.gtfp.workingmemory.utils.dialog.onDestroy ()
Definition at line 71 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.Dialogue.onDestroy().
Referenced by com.gtfp.workingmemory.edit.appCRUD.onDestroy(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onDestroy().
setDialogBoxListener()
DialogBoxListener com.gtfp.workingmemory.utils.dialog.setDialogBoxListener (DialogBoxListener listener)
Definition at line 93 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.mListener.
Referenced by com.gtfp.workingmemory.edit.appCRUD.appCRUD(), com.gtfp.workingmemory.app.appView.appView(), com.gtfp.workingmemory.utils.dialog.dialog(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
Member Data Documentation
REQUEST_CODE
final int com.gtfp.workingmemory.utils.dialog.REQUEST_CODE = dialog.class.hashCode() static
Definition at line 21 of file dialog.java.
mDialogue
Dialogue com.gtfp.workingmemory.utils.dialog.mDialogue private
Definition at line 23 of file dialog.java.
mListener
DialogBoxListener com.gtfp.workingmemory.utils.dialog.mListener private
Definition at line 25 of file dialog.java.
Referenced by com.gtfp.workingmemory.utils.dialog.setDialogBoxListener().
mContext
Context com.gtfp.workingmemory.utils.dialog.mContext private
Definition at line 27 of file dialog.java.
YESNO
final int com.gtfp.workingmemory.utils.dialog.YESNO = 1 static
Definition at line 29 of file dialog.java.
Referenced by com.gtfp.workingmemory.utils.dialog.Dialogue.buildDialog().