Working Memory: com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime Class Reference
com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime Class Reference
Public Member Functions
int getYear ()
int getMonth ()
int getDay ()
int getHour ()
int getMin ()
Protected Member Functions
boolean set (long epoch)
int get (String key)
void onDestroy ()
Package Functions
ToDoDateTime ()
ToDoDateTime (long epoch)
Private Attributes
HashMap< String, Integer > mDateTime
Static Private Attributes
static final long serialVersionUID = -6506171562852065742L
Detailed Description
Definition at line 1023 of file ToDoItem.java.
Constructor & Destructor Documentation
ToDoDateTime() [1/2]
com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.ToDoDateTime () package
Definition at line 1031 of file ToDoItem.java.
ToDoDateTime() [2/2]
com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.ToDoDateTime (long epoch) package
Definition at line 1036 of file ToDoItem.java.
Member Function Documentation
set()
boolean com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.set (long epoch) protected
Definition at line 1043 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setDueDate().
get()
int com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.get (String key) protected
Definition at line 1069 of file ToDoItem.java.
getYear()
int com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getYear ()
Definition at line 1099 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getYear().
getMonth()
int com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getMonth ()
Definition at line 1103 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getMonth().
getDay()
int com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getDay ()
Definition at line 1107 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDay().
getHour()
int com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getHour ()
Definition at line 1111 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getHour().
getMin()
int com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getMin ()
Definition at line 1115 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getMin().
onDestroy()
void com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.onDestroy () protected
Definition at line 1119 of file ToDoItem.java.
Member Data Documentation
serialVersionUID
final long com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.serialVersionUID = -6506171562852065742L static private
Definition at line 1025 of file ToDoItem.java.
mDateTime
HashMap<String, Integer> com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.mDateTime private
Definition at line 1027 of file ToDoItem.java.