Working Memory: com.gtfp.workingmemory.wallpaper.Wallpaper Class Reference
com.gtfp.workingmemory.wallpaper.Wallpaper Class Reference
Created by Drawn on 2015-07-31.
Classes
class just
Public Member Functions
Wallpaper (Activity activity)
boolean set ()
Bitmap getWallpaperBitmap ()
BitmapDrawable getWallpaperBitmapDrawable ()
Drawable getWallpaper ()
Bitmap overlayWallpaperList (Bitmap wallpaper)
boolean overlayWallpaperList1 ()
boolean setWallpaper (Bitmap bitmap)
void onDestroy ()
Private Member Functions
boolean saveWallpaper (Bitmap bitmapImage)
Bitmap getSavedWallpaper ()
File getWallpaperFile ()
boolean DeleteSavedWallpaper ()
Private Attributes
Activity mActivity
File mImageFile
WallpaperManager mWallpaperManager
Static Private Attributes
static final String DIRECTORY = "imgDir"
static final String WALLPAPER_FILE = "wallpaper.png"
static boolean JUST_SET = true
Detailed Description
Created by Drawn on 2015-07-31.
Definition at line 27 of file Wallpaper.java.
Constructor & Destructor Documentation
Wallpaper()
com.gtfp.workingmemory.wallpaper.Wallpaper.Wallpaper (Activity activity)
Definition at line 43 of file Wallpaper.java.
Member Function Documentation
set()
boolean com.gtfp.workingmemory.wallpaper.Wallpaper.set ()
Definition at line 51 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmap(), com.gtfp.workingmemory.wallpaper.Wallpaper.overlayWallpaperList(), and com.gtfp.workingmemory.wallpaper.Wallpaper.setWallpaper().
Referenced by com.gtfp.workingmemory.app.appView.save().
getWallpaperBitmap()
Bitmap com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmap ()
Definition at line 82 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.getSavedWallpaper(), com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmapDrawable(), and com.gtfp.workingmemory.wallpaper.Wallpaper.saveWallpaper().
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.set().
getWallpaperBitmapDrawable()
BitmapDrawable com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmapDrawable ()
Definition at line 113 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaper().
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmap().
getWallpaper()
Drawable com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaper ()
Definition at line 135 of file Wallpaper.java.
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmapDrawable().
saveWallpaper()
boolean com.gtfp.workingmemory.wallpaper.Wallpaper.saveWallpaper (Bitmap bitmapImage) private
Definition at line 159 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperFile().
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmap().
getSavedWallpaper()
Bitmap com.gtfp.workingmemory.wallpaper.Wallpaper.getSavedWallpaper () private
Definition at line 184 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperFile().
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperBitmap().
getWallpaperFile()
File com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperFile () private
Definition at line 201 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.mImageFile.
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.DeleteSavedWallpaper(), com.gtfp.workingmemory.wallpaper.Wallpaper.getSavedWallpaper(), and com.gtfp.workingmemory.wallpaper.Wallpaper.saveWallpaper().
overlayWallpaperList()
Bitmap com.gtfp.workingmemory.wallpaper.Wallpaper.overlayWallpaperList (Bitmap wallpaper)
Definition at line 220 of file Wallpaper.java.
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.set().
overlayWallpaperList1()
boolean com.gtfp.workingmemory.wallpaper.Wallpaper.overlayWallpaperList1 ()
Definition at line 247 of file Wallpaper.java.
setWallpaper()
boolean com.gtfp.workingmemory.wallpaper.Wallpaper.setWallpaper (Bitmap bitmap)
Definition at line 293 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.just.set().
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.set().
DeleteSavedWallpaper()
boolean com.gtfp.workingmemory.wallpaper.Wallpaper.DeleteSavedWallpaper () private
Definition at line 312 of file Wallpaper.java.
References com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperFile().
onDestroy()
void com.gtfp.workingmemory.wallpaper.Wallpaper.onDestroy ()
Definition at line 323 of file Wallpaper.java.
Member Data Documentation
DIRECTORY
final String com.gtfp.workingmemory.wallpaper.Wallpaper.DIRECTORY = "imgDir" static private
Definition at line 29 of file Wallpaper.java.
WALLPAPER_FILE
final String com.gtfp.workingmemory.wallpaper.Wallpaper.WALLPAPER_FILE = "wallpaper.png" static private
Definition at line 31 of file Wallpaper.java.
mActivity
Activity com.gtfp.workingmemory.wallpaper.Wallpaper.mActivity private
Definition at line 33 of file Wallpaper.java.
mImageFile
File com.gtfp.workingmemory.wallpaper.Wallpaper.mImageFile private
Definition at line 35 of file Wallpaper.java.
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.getWallpaperFile().
mWallpaperManager
WallpaperManager com.gtfp.workingmemory.wallpaper.Wallpaper.mWallpaperManager private
Definition at line 37 of file Wallpaper.java.
JUST_SET
boolean com.gtfp.workingmemory.wallpaper.Wallpaper.JUST_SET = true static private
Definition at line 39 of file Wallpaper.java.
Referenced by com.gtfp.workingmemory.wallpaper.Wallpaper.just.set().