Working Memory: com.gtfp.workingmemory.todo.ToDoAlarm.Manager Class Reference
com.gtfp.workingmemory.todo.ToDoAlarm.Manager Class Reference
Public Member Functions
Manager (Context context)
void setAlarm (ToDoItem itemToDo)
void cancelAlarm (ToDoItem itemToDo)
void cancelAlarm (long id)
void cancelNotification (ToDoItem itemToDo)
void colorChanged (int color)
void onDestroy ()
Static Public Member Functions
static boolean copyOver (ToDoItem itemToDo)
static void cancelNotification (int id)
static void cancelNotification (Context context, ToDoItem itemToDo)
static Uri getAlarmUri ()
Package Functions
void cancelAlarm (int id)
Static Package Functions
static void initAlarmManager (Context context)
static void repeatAlarm (Context context, ToDoItem itemToDo)
static void cancelAlarm (PendingIntent pendingIntent)
static PendingIntent getPendingIntent (int id)
static Intent getAlarmIntent (ToDoItem itemToDo)
static Intent getAlarmIntent (int id)
Return the Intent for PendingIntent.
Static Package Attributes
static Intent mAlarmIntent
static int mLedArgb = 0xFF0000FF
static int mLedOnMs = 100
static int mLedOffMs = 2000
Static Private Member Functions
static void Notification (Context context, Intent intent)
Private Attributes
appController mApp
Static Private Attributes
static NotificationManager mNotificationManager
static Context mContext
static AlarmManager mAlarmManager
Detailed Description
Definition at line 132 of file ToDoAlarm.java.
Constructor & Destructor Documentation
Manager()
com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Manager (Context context)
Definition at line 151 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.initAlarmManager(), and com.gtfp.workingmemory.colorPicker.colorPickerView.setOnColorChangedListener().
Member Function Documentation
initAlarmManager()
static void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.initAlarmManager (Context context) static package
Definition at line 159 of file ToDoAlarm.java.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Manager(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm().
setAlarm()
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm (ToDoItem itemToDo)
Definition at line 179 of file ToDoAlarm.java.
References com.gtfp.workingmemory.app.appView.clearNotification(), com.gtfp.workingmemory.todo.ToDoItem.clearNotification(), com.gtfp.workingmemory.todo.ToDoItem.EpochToCalendar(), com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.app.appView.showDialogue(), and com.gtfp.workingmemory.todo.ToDoItem.showDialogue().
repeatAlarm()
static void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm (Context context, ToDoItem itemToDo) static package
Definition at line 229 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm(), com.gtfp.workingmemory.todo.ToDoItem.EpochToCalendar(), com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getPendingIntent(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.initAlarmManager(), and com.gtfp.workingmemory.todo.ToDoItem.reminderInterval().
cancelAlarm() [1/4]
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm (ToDoItem itemToDo)
Definition at line 275 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm().
cancelAlarm() [2/4]
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm (long id)
Definition at line 281 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm().
cancelAlarm() [3/4]
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm (int id) package
Definition at line 287 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getPendingIntent().
cancelAlarm() [4/4]
static void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm (PendingIntent pendingIntent) static package
Definition at line 301 of file ToDoAlarm.java.
getPendingIntent()
static PendingIntent com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getPendingIntent (int id) static package
Definition at line 307 of file ToDoAlarm.java.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmIntent(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm().
getAlarmIntent() [1/2]
static Intent com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmIntent (ToDoItem itemToDo) static package
Definition at line 321 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver().
getAlarmIntent() [2/2]
static Intent com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmIntent (int id) static package
Return the Intent for PendingIntent.
Return null in case of some errors: see Android source.
Exceptions
IllegalStateException in case of something goes wrong. See Throwable#getCause() for more details.
Definition at line 334 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getPendingIntent().
copyOver()
static boolean com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver (ToDoItem itemToDo) static
Definition at line 369 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoItem.clearNotification(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmIntent(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmUri(), com.gtfp.workingmemory.todo.ToDoItem.setClearNotification(), com.gtfp.workingmemory.todo.ToDoItem.setShowDialogue(), com.gtfp.workingmemory.todo.ToDoItem.setSound(), com.gtfp.workingmemory.todo.ToDoItem.setUseLED(), com.gtfp.workingmemory.todo.ToDoItem.setUseVibrate(), com.gtfp.workingmemory.todo.ToDoItem.showDialogue(), com.gtfp.workingmemory.todo.ToDoItem.Sound(), com.gtfp.workingmemory.todo.ToDoItem.useLED(), and com.gtfp.workingmemory.todo.ToDoItem.useVibrate().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.settings().
cancelNotification() [1/3]
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification (ToDoItem itemToDo)
Definition at line 395 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.utils.Dialogue.Cancel(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification(), and com.gtfp.workingmemory.utils.Dialogue.Edit().
cancelNotification() [2/3]
static void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification (int id) static
Definition at line 401 of file ToDoAlarm.java.
cancelNotification() [3/3]
static void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification (Context context, ToDoItem itemToDo) static
Definition at line 409 of file ToDoAlarm.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification(), and com.gtfp.workingmemory.todo.ToDoItem.getId().
Notification()
static void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification (Context context, Intent intent) static private
Definition at line 420 of file ToDoAlarm.java.
References com.gtfp.workingmemory.settings.appSettings.get(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmUri(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOn(), com.gtfp.workingmemory.settings.appSettings.getString(), com.gtfp.workingmemory.todo.ToDoItem.itemToDisplay(), com.gtfp.workingmemory.todo.ToDoItem.Sound(), com.gtfp.workingmemory.todo.ToDoItem.useLED(), and com.gtfp.workingmemory.todo.ToDoItem.useVibrate().
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.onReceive().
getAlarmUri()
static Uri com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmUri () static
Definition at line 497 of file ToDoAlarm.java.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
colorChanged()
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.colorChanged (int color)
Implements com.gtfp.workingmemory.colorPicker.colorPickerView.OnColorChangedListener.
Definition at line 518 of file ToDoAlarm.java.
onDestroy()
void com.gtfp.workingmemory.todo.ToDoAlarm.Manager.onDestroy ()
Definition at line 524 of file ToDoAlarm.java.
Member Data Documentation
mNotificationManager
NotificationManager com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mNotificationManager static private
Definition at line 135 of file ToDoAlarm.java.
mApp
appController com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mApp private
Definition at line 137 of file ToDoAlarm.java.
mContext
Context com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mContext static private
Definition at line 139 of file ToDoAlarm.java.
mAlarmManager
AlarmManager com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mAlarmManager static private
Definition at line 141 of file ToDoAlarm.java.
mAlarmIntent
Intent com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mAlarmIntent static package
Definition at line 143 of file ToDoAlarm.java.
mLedArgb
int com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mLedArgb = 0xFF0000FF static package
Definition at line 145 of file ToDoAlarm.java.
mLedOnMs
int com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mLedOnMs = 100 static package
Definition at line 147 of file ToDoAlarm.java.
mLedOffMs
int com.gtfp.workingmemory.todo.ToDoAlarm.Manager.mLedOffMs = 2000 static package
Definition at line 149 of file ToDoAlarm.java.