Working Memory: com.gtfp.workingmemory.db.dbSQLlite Class Reference
com.gtfp.workingmemory.db.dbSQLlite Class Reference
Created by Drawn on 2015-02-10.
Classes
interface OnConfigureListener
interface OnCreateListener
interface OnOpenListener
Public Member Functions
boolean createCurrentRecs ()
dbSQLlite open ()
boolean isOpen ()
void close ()
SQLiteDatabase getDatabase ()
void clearResultSet ()
Cursor getResultSet ()
boolean showDeleted (boolean showDeleted)
Cursor runQuery (String sqlStmt)
Cursor getRecs ()
Cursor getCurrentRecs ()
Cursor getDeletedRecs ()
Long getLastRowID ()
Cursor getRec (String keyID)
long getRecID (String keyID)
ArrayList< ToDoItem > ToDoList (ArrayList< HashMap< String, String >> todoItems)
ArrayList< HashMap< String, String > > getDataArrayList ()
int deleteRec (Long rowID)
boolean markRec (Long rowID)
boolean save (ToDoItem itemToDo)
int updateRec (ToDoItem itemToDo)
int updateRec (ContentValues recValues, long id)
long insertRec (ToDoItem itemToDo)
long insertRec (ContentValues recValues)
ContentValues bindRecValues (ToDoItem itemToDo)
void bindRecValues (String columnName, String value)
ContentValues recValues ()
boolean importRec ()
boolean ifNewRec ()
Cursor getRecs (String whereClause)
Cursor getRecord (int rowId)
boolean createEmptyTemp ()
long insertTempRec ()
Cursor getNewTempRecs ()
boolean dropTable ()
boolean dropTable (SQLiteDatabase db)
void onConfigure (SQLiteDatabase db)
void onOpen (SQLiteDatabase db)
void onCreate (SQLiteDatabase db)
void onDowngrade (SQLiteDatabase db, int oldVersion, int newVersion)
void onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion)
void setOnCreateListener (OnCreateListener listener)
void setOnOpenListener (OnOpenListener listener)
void setOnConfigureListener (OnConfigureListener listener)
void onDestroy ()
Static Public Member Functions
static dbInterface getInstance (Context controller)
static int setBindRecInt (String value)
static long setBindRecLong (String value)
Public Attributes
Cursor mDataRecs
Protected Member Functions
void execSqlFile (String sqlFile, SQLiteDatabase db) throws SQLException, IOException
Private Member Functions
dbSQLlite (Context controller)
boolean createTemp (String whereClause)
long insertTemptRec (ContentValues recValues)
void setTheGrade (SQLiteDatabase db, int oldVersion, int newVersion)
Private Attributes
final String ALTER_TABLE
final String SELECT_ALL = "SELECT " + DBKEY_FIELD + " AS _id, * FROM " + DATABASE_NAME
SQLiteDatabase mDB
Context mContext
Cursor mResultSet
ContentValues mRecValues
boolean mUseView
Set< OnCreateListener > mOnCreateListeners = new HashSet<>()
Set< OnOpenListener > mOnOpenListeners = new HashSet<>()
Set< OnConfigureListener > mOnConfigureListeners = new HashSet<>()
Static Private Attributes
static final String DATABASE_NAME = "working"
static final String DATABASE_FILE = DATABASE_NAME + ".db"
static final String DBKEY_FIELD = "rowid"
static final int DATABASE_VERSION = 14
static final String DATABASE_CREATE
static final String DROP_TABLE = "DROP TABLE IF EXISTS " + DATABASE_NAME
static final String CREATE_NOT_DELETED
static final String CREATE_DELETED
static final String DROP_DELETED = "DROP VIEW IF EXISTS temp.deleted"
static final String SELECT_NOT_DELETED
static final String SELECT_DELETED
static final String SQL_DIR = "sql"
static final String CREATEFILE = "create.sql"
static final String UPGRADEFILE_PREFIX = "upgrade-"
static final String UPGRADEFILE_SUFFIX = ".sql"
static dbInterface mDBHelper
Detailed Description
Created by Drawn on 2015-02-10.
Definition at line 23 of file dbSQLlite.java.
Constructor & Destructor Documentation
dbSQLlite()
com.gtfp.workingmemory.db.dbSQLlite.dbSQLlite (Context controller) private
Definition at line 94 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getInstance().
Member Function Documentation
getInstance()
static dbInterface com.gtfp.workingmemory.db.dbSQLlite.getInstance (Context controller) static
Definition at line 105 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.dbSQLlite(), and com.gtfp.workingmemory.db.dbSQLlite.mDBHelper.
Referenced by com.gtfp.workingmemory.app.appModel.appModel(), and com.gtfp.workingmemory.app.appModel.getDBHelper().
setBindRecInt()
static int com.gtfp.workingmemory.db.dbSQLlite.setBindRecInt (String value) static
Definition at line 117 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), and com.gtfp.workingmemory.db.dbFireBase.bindRecValues().
setBindRecLong()
static long com.gtfp.workingmemory.db.dbSQLlite.setBindRecLong (String value) static
Definition at line 135 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), and com.gtfp.workingmemory.db.dbFireBase.bindRecValues().
createCurrentRecs()
boolean com.gtfp.workingmemory.db.dbSQLlite.createCurrentRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 153 of file dbSQLlite.java.
open()
dbSQLlite com.gtfp.workingmemory.db.dbSQLlite.open ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 171 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.isOpen().
isOpen()
boolean com.gtfp.workingmemory.db.dbSQLlite.isOpen ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 198 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.open().
close()
void com.gtfp.workingmemory.db.dbSQLlite.close ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 205 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.onDestroy().
getDatabase()
SQLiteDatabase com.gtfp.workingmemory.db.dbSQLlite.getDatabase ()
Definition at line 226 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.mDB.
clearResultSet()
void com.gtfp.workingmemory.db.dbSQLlite.clearResultSet ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 233 of file dbSQLlite.java.
getResultSet()
Cursor com.gtfp.workingmemory.db.dbSQLlite.getResultSet ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 240 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.getCurrentRecs(), com.gtfp.workingmemory.db.dbSQLlite.getRecs(), and com.gtfp.workingmemory.db.dbSQLlite.mResultSet.
showDeleted()
boolean com.gtfp.workingmemory.db.dbSQLlite.showDeleted (boolean showDeleted)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 258 of file dbSQLlite.java.
runQuery()
Cursor com.gtfp.workingmemory.db.dbSQLlite.runQuery (String sqlStmt)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 268 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getCurrentRecs(), com.gtfp.workingmemory.db.dbSQLlite.getDeletedRecs(), com.gtfp.workingmemory.db.dbSQLlite.getLastRowID(), com.gtfp.workingmemory.db.dbSQLlite.getNewTempRecs(), com.gtfp.workingmemory.db.dbSQLlite.getRec(), and com.gtfp.workingmemory.db.dbSQLlite.getRecs().
getRecs() [1/2]
Cursor com.gtfp.workingmemory.db.dbSQLlite.getRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 287 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.runQuery().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getRecord(), com.gtfp.workingmemory.db.dbSQLlite.getResultSet(), and com.gtfp.workingmemory.db.dbSQLlite.ifNewRec().
getCurrentRecs()
Cursor com.gtfp.workingmemory.db.dbSQLlite.getCurrentRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 294 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.runQuery().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getResultSet().
getDeletedRecs()
Cursor com.gtfp.workingmemory.db.dbSQLlite.getDeletedRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 301 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.runQuery().
getLastRowID()
Long com.gtfp.workingmemory.db.dbSQLlite.getLastRowID ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 308 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.runQuery().
getRec()
Cursor com.gtfp.workingmemory.db.dbSQLlite.getRec (String keyID)
Definition at line 337 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.runQuery().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getRecID().
getRecID()
long com.gtfp.workingmemory.db.dbSQLlite.getRecID (String keyID)
Definition at line 351 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.getRec().
Referenced by com.gtfp.workingmemory.db.dbCloud.dbLocal.save().
ToDoList()
ArrayList<ToDoItem> com.gtfp.workingmemory.db.dbSQLlite.ToDoList (ArrayList< HashMap< String, String >> todoItems)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 375 of file dbSQLlite.java.
References com.gtfp.workingmemory.todo.ToDoItem.hasFired(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.todo.ToDoItem.setAlarm(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.todo.ToDoItem.setId(), com.gtfp.workingmemory.todo.ToDoItem.setItemName(), com.gtfp.workingmemory.todo.ToDoItem.setKey(), com.gtfp.workingmemory.todo.ToDoItem.setLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.setReminderChk(), and com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch().
getDataArrayList()
ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbSQLlite.getDataArrayList ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 462 of file dbSQLlite.java.
deleteRec()
int com.gtfp.workingmemory.db.dbSQLlite.deleteRec (Long rowID)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 469 of file dbSQLlite.java.
markRec()
boolean com.gtfp.workingmemory.db.dbSQLlite.markRec (Long rowID)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 489 of file dbSQLlite.java.
save()
boolean com.gtfp.workingmemory.db.dbSQLlite.save (ToDoItem itemToDo)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 512 of file dbSQLlite.java.
References com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.db.dbSQLlite.insertRec(), com.gtfp.workingmemory.todo.ToDoItem.newItem(), com.gtfp.workingmemory.todo.ToDoItem.setId(), and com.gtfp.workingmemory.db.dbSQLlite.updateRec().
updateRec() [1/2]
int com.gtfp.workingmemory.db.dbSQLlite.updateRec (ToDoItem itemToDo)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 541 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), and com.gtfp.workingmemory.todo.ToDoItem.getId().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.save().
updateRec() [2/2]
int com.gtfp.workingmemory.db.dbSQLlite.updateRec (ContentValues recValues, long id)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 548 of file dbSQLlite.java.
insertRec() [1/2]
long com.gtfp.workingmemory.db.dbSQLlite.insertRec (ToDoItem itemToDo)
Definition at line 568 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.bindRecValues().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.importRec(), com.gtfp.workingmemory.db.dbSQLlite.save(), and com.gtfp.workingmemory.db.dbCloud.dbLocal.save().
insertRec() [2/2]
long com.gtfp.workingmemory.db.dbSQLlite.insertRec (ContentValues recValues)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 575 of file dbSQLlite.java.
bindRecValues() [1/2]
ContentValues com.gtfp.workingmemory.db.dbSQLlite.bindRecValues (ToDoItem itemToDo)
Definition at line 593 of file dbSQLlite.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getKey(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.hasFired(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.db.dbSQLlite.mRecValues, and com.gtfp.workingmemory.todo.ToDoItem.setAlarm().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.insertRec(), and com.gtfp.workingmemory.db.dbSQLlite.updateRec().
bindRecValues() [2/2]
void com.gtfp.workingmemory.db.dbSQLlite.bindRecValues (String columnName, String value)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 623 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.setBindRecInt(), and com.gtfp.workingmemory.db.dbSQLlite.setBindRecLong().
recValues()
ContentValues com.gtfp.workingmemory.db.dbSQLlite.recValues ()
Definition at line 673 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.mRecValues.
importRec()
boolean com.gtfp.workingmemory.db.dbSQLlite.importRec ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 680 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.insertRec().
ifNewRec()
boolean com.gtfp.workingmemory.db.dbSQLlite.ifNewRec ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 687 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.getRecs().
getRecs() [2/2]
Cursor com.gtfp.workingmemory.db.dbSQLlite.getRecs (String whereClause)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 707 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.DATABASE_NAME.
getRecord()
Cursor com.gtfp.workingmemory.db.dbSQLlite.getRecord (int rowId)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 730 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.getRecs().
createTemp()
boolean com.gtfp.workingmemory.db.dbSQLlite.createTemp (String whereClause) private
Definition at line 739 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.SELECT_ALL.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.createEmptyTemp().
createEmptyTemp()
boolean com.gtfp.workingmemory.db.dbSQLlite.createEmptyTemp ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 761 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.createTemp().
insertTempRec()
long com.gtfp.workingmemory.db.dbSQLlite.insertTempRec ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 768 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.insertTemptRec().
getNewTempRecs()
Cursor com.gtfp.workingmemory.db.dbSQLlite.getNewTempRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 775 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.runQuery().
insertTemptRec()
long com.gtfp.workingmemory.db.dbSQLlite.insertTemptRec (ContentValues recValues) private
Definition at line 790 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.insertTempRec().
dropTable() [1/2]
boolean com.gtfp.workingmemory.db.dbSQLlite.dropTable ()
Definition at line 808 of file dbSQLlite.java.
dropTable() [2/2]
boolean com.gtfp.workingmemory.db.dbSQLlite.dropTable (SQLiteDatabase db)
Definition at line 815 of file dbSQLlite.java.
onConfigure()
void com.gtfp.workingmemory.db.dbSQLlite.onConfigure (SQLiteDatabase db)
Definition at line 837 of file dbSQLlite.java.
onOpen()
void com.gtfp.workingmemory.db.dbSQLlite.onOpen (SQLiteDatabase db)
Definition at line 857 of file dbSQLlite.java.
execSqlFile()
void com.gtfp.workingmemory.db.dbSQLlite.execSqlFile (String sqlFile, SQLiteDatabase db) throws SQLException, IOException protected
Definition at line 876 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.onCreate(), and com.gtfp.workingmemory.db.dbSQLlite.setTheGrade().
onCreate()
void com.gtfp.workingmemory.db.dbSQLlite.onCreate (SQLiteDatabase db)
Definition at line 898 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.execSqlFile().
onDowngrade()
void com.gtfp.workingmemory.db.dbSQLlite.onDowngrade (SQLiteDatabase db, int oldVersion, int newVersion)
Definition at line 921 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.setTheGrade().
onUpgrade()
void com.gtfp.workingmemory.db.dbSQLlite.onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion)
Definition at line 927 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.setTheGrade().
setTheGrade()
void com.gtfp.workingmemory.db.dbSQLlite.setTheGrade (SQLiteDatabase db, int oldVersion, int newVersion) private
Definition at line 932 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.execSqlFile(), and com.gtfp.workingmemory.db.dbSQLParser.list().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.onDowngrade(), and com.gtfp.workingmemory.db.dbSQLlite.onUpgrade().
setOnCreateListener()
void com.gtfp.workingmemory.db.dbSQLlite.setOnCreateListener (OnCreateListener listener)
Definition at line 1005 of file dbSQLlite.java.
setOnOpenListener()
void com.gtfp.workingmemory.db.dbSQLlite.setOnOpenListener (OnOpenListener listener)
Definition at line 1013 of file dbSQLlite.java.
setOnConfigureListener()
void com.gtfp.workingmemory.db.dbSQLlite.setOnConfigureListener (OnConfigureListener listener)
Definition at line 1021 of file dbSQLlite.java.
onDestroy()
void com.gtfp.workingmemory.db.dbSQLlite.onDestroy ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 1029 of file dbSQLlite.java.
References com.gtfp.workingmemory.db.dbSQLlite.close().
Member Data Documentation
DATABASE_NAME
final String com.gtfp.workingmemory.db.dbSQLlite.DATABASE_NAME = "working" static private
Definition at line 25 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getRecs().
DATABASE_FILE
final String com.gtfp.workingmemory.db.dbSQLlite.DATABASE_FILE = DATABASE_NAME + ".db" static private
Definition at line 27 of file dbSQLlite.java.
DBKEY_FIELD
final String com.gtfp.workingmemory.db.dbSQLlite.DBKEY_FIELD = "rowid" static private
Definition at line 30 of file dbSQLlite.java.
DATABASE_VERSION
final int com.gtfp.workingmemory.db.dbSQLlite.DATABASE_VERSION = 14 static private
Definition at line 32 of file dbSQLlite.java.
DATABASE_CREATE
final String com.gtfp.workingmemory.db.dbSQLlite.DATABASE_CREATE static private
Initial value:
= "CREATE TABLE IF NOT EXISTS " + DATABASE_NAME
            + "(ToDoItem VARCHAR, ToDoKey VARCHAR, ToDoDateTime VARCHAR, ToDoDateTimeEpoch Long, ToDoTimeZone VARCHAR, ToDoReminderEpoch Long, ToDoReminderChk integer default 0, ToDoLEDColor integer default 0, ToDoFired integer default 0, deleted integer default 0);"
Definition at line 35 of file dbSQLlite.java.
DROP_TABLE
final String com.gtfp.workingmemory.db.dbSQLlite.DROP_TABLE = "DROP TABLE IF EXISTS " + DATABASE_NAME static private
Definition at line 38 of file dbSQLlite.java.
CREATE_NOT_DELETED
final String com.gtfp.workingmemory.db.dbSQLlite.CREATE_NOT_DELETED static private
Initial value:
=
            "CREATE TEMP VIEW IF NOT EXISTS temp.notdeleted AS SELECT " + DBKEY_FIELD
                    + " AS _id, * FROM " + DATABASE_NAME
                    + " WHERE deleted = 0"
Definition at line 40 of file dbSQLlite.java.
CREATE_DELETED
final String com.gtfp.workingmemory.db.dbSQLlite.CREATE_DELETED static private
Initial value:
=
            "CREATE TEMP VIEW IF NOT EXISTS temp.deleted AS SELECT " + DBKEY_FIELD
                    + " AS _id, * FROM " + DATABASE_NAME
                    + " WHERE deleted = 1"
Definition at line 45 of file dbSQLlite.java.
DROP_DELETED
final String com.gtfp.workingmemory.db.dbSQLlite.DROP_DELETED = "DROP VIEW IF EXISTS temp.deleted" static private
Definition at line 50 of file dbSQLlite.java.
SELECT_NOT_DELETED
final String com.gtfp.workingmemory.db.dbSQLlite.SELECT_NOT_DELETED static private
Initial value:
= "SELECT " + DBKEY_FIELD
            + " AS _id, * FROM temp.notdeleted"
Definition at line 52 of file dbSQLlite.java.
SELECT_DELETED
final String com.gtfp.workingmemory.db.dbSQLlite.SELECT_DELETED static private
Initial value:
= "SELECT " + DBKEY_FIELD
            + " AS _id, * FROM temp.deleted"
Definition at line 55 of file dbSQLlite.java.
SQL_DIR
final String com.gtfp.workingmemory.db.dbSQLlite.SQL_DIR = "sql" static private
Definition at line 58 of file dbSQLlite.java.
CREATEFILE
final String com.gtfp.workingmemory.db.dbSQLlite.CREATEFILE = "create.sql" static private
Definition at line 60 of file dbSQLlite.java.
UPGRADEFILE_PREFIX
final String com.gtfp.workingmemory.db.dbSQLlite.UPGRADEFILE_PREFIX = "upgrade-" static private
Definition at line 62 of file dbSQLlite.java.
UPGRADEFILE_SUFFIX
final String com.gtfp.workingmemory.db.dbSQLlite.UPGRADEFILE_SUFFIX = ".sql" static private
Definition at line 65 of file dbSQLlite.java.
mDBHelper
dbInterface com.gtfp.workingmemory.db.dbSQLlite.mDBHelper static private
Definition at line 67 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getInstance().
ALTER_TABLE
final String com.gtfp.workingmemory.db.dbSQLlite.ALTER_TABLE private
Initial value:
= "ALTER TABLE " + DATABASE_NAME
            + " ADD COLUMN ToDoFired integer default 0;"
Definition at line 70 of file dbSQLlite.java.
SELECT_ALL
final String com.gtfp.workingmemory.db.dbSQLlite.SELECT_ALL = "SELECT " + DBKEY_FIELD + " AS _id, * FROM " + DATABASE_NAME private
Definition at line 73 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.createTemp().
mDataRecs
Cursor com.gtfp.workingmemory.db.dbSQLlite.mDataRecs
Definition at line 75 of file dbSQLlite.java.
mDB
SQLiteDatabase com.gtfp.workingmemory.db.dbSQLlite.mDB private
Definition at line 77 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getDatabase().
mContext
Context com.gtfp.workingmemory.db.dbSQLlite.mContext private
Definition at line 79 of file dbSQLlite.java.
mResultSet
Cursor com.gtfp.workingmemory.db.dbSQLlite.mResultSet private
Definition at line 81 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.getResultSet().
mRecValues
ContentValues com.gtfp.workingmemory.db.dbSQLlite.mRecValues private
Definition at line 83 of file dbSQLlite.java.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), and com.gtfp.workingmemory.db.dbSQLlite.recValues().
mUseView
boolean com.gtfp.workingmemory.db.dbSQLlite.mUseView private
Definition at line 85 of file dbSQLlite.java.
mOnCreateListeners
Set<OnCreateListener> com.gtfp.workingmemory.db.dbSQLlite.mOnCreateListeners = new HashSet<>() private
Definition at line 87 of file dbSQLlite.java.
mOnOpenListeners
Set<OnOpenListener> com.gtfp.workingmemory.db.dbSQLlite.mOnOpenListeners = new HashSet<>() private
Definition at line 89 of file dbSQLlite.java.
mOnConfigureListeners
Set<OnConfigureListener> com.gtfp.workingmemory.db.dbSQLlite.mOnConfigureListeners = new HashSet<>() private
Definition at line 91 of file dbSQLlite.java.