Working Memory: com.gtfp.workingmemory.db.dbInterface Interface Reference
com.gtfp.workingmemory.db.dbInterface Interface Reference
Created by Drawn on 9/26/2016.
Public Member Functions
dbInterface open ()
boolean isOpen ()
void close ()
boolean createCurrentRecs ()
void clearResultSet ()
Cursor getResultSet ()
boolean showDeleted (boolean showDeleted)
Cursor runQuery (String sqlStmt)
Cursor getRecs ()
Cursor getCurrentRecs ()
Cursor getDeletedRecs ()
< T > T getLastRowID ()
ArrayList< ToDoItem > ToDoList (ArrayList< HashMap< String, String >> recs)
ArrayList< HashMap< String, String > > getDataArrayList ()
int deleteRec (Long rowID)
boolean save (ToDoItem itemToDo)
boolean markRec (Long rowID)
int updateRec (ToDoItem itemToDo)
int updateRec (ContentValues recValues, long id)
long insertRec (ContentValues recValues)
boolean createEmptyTemp ()
long insertTempRec ()
Cursor getNewTempRecs ()
boolean ifNewRec ()
void bindRecValues (String columnName, String value)
boolean importRec ()
Cursor getRecs (String whereClause)
Cursor getRecord (int rowId)
void onDestroy ()
Detailed Description
Created by Drawn on 9/26/2016.
Definition at line 15 of file dbInterface.java.
Member Function Documentation
open()
dbInterface com.gtfp.workingmemory.db.dbInterface.open ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.open().
isOpen()
boolean com.gtfp.workingmemory.db.dbInterface.isOpen ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.delete(), com.gtfp.workingmemory.app.appModel.open(), and com.gtfp.workingmemory.app.appModel.save().
close()
void com.gtfp.workingmemory.db.dbInterface.close ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.close(), and com.gtfp.workingmemory.app.appModel.open().
createCurrentRecs()
boolean com.gtfp.workingmemory.db.dbInterface.createCurrentRecs ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.open().
clearResultSet()
void com.gtfp.workingmemory.db.dbInterface.clearResultSet ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.ToDoList().
getResultSet()
Cursor com.gtfp.workingmemory.db.dbInterface.getResultSet ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.ToDoList().
showDeleted()
boolean com.gtfp.workingmemory.db.dbInterface.showDeleted (boolean showDeleted)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.ToDoList().
runQuery()
Cursor com.gtfp.workingmemory.db.dbInterface.runQuery (String sqlStmt)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
getRecs() [1/2]
Cursor com.gtfp.workingmemory.db.dbInterface.getRecs ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.getRecs(), and com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
getCurrentRecs()
Cursor com.gtfp.workingmemory.db.dbInterface.getCurrentRecs ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave().
getDeletedRecs()
Cursor com.gtfp.workingmemory.db.dbInterface.getDeletedRecs ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
getLastRowID()
<T> T com.gtfp.workingmemory.db.dbInterface.getLastRowID ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.getLastRowID().
ToDoList()
ArrayList<ToDoItem> com.gtfp.workingmemory.db.dbInterface.ToDoList (ArrayList< HashMap< String, String >> recs)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.ToDoList(), com.gtfp.workingmemory.db.dbCloud.dbLocal.toToDoItem(), and com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
getDataArrayList()
ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbInterface.getDataArrayList ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
deleteRec()
int com.gtfp.workingmemory.db.dbInterface.deleteRec (Long rowID)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.db.dbCloud.dbLocal.delete(), and com.gtfp.workingmemory.app.appModel.trueDelete().
save()
boolean com.gtfp.workingmemory.db.dbInterface.save (ToDoItem itemToDo)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.save(), and com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
markRec()
boolean com.gtfp.workingmemory.db.dbInterface.markRec (Long rowID)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.delete().
updateRec() [1/2]
int com.gtfp.workingmemory.db.dbInterface.updateRec (ToDoItem itemToDo)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.db.dbCloud.dbLocal.save().
updateRec() [2/2]
int com.gtfp.workingmemory.db.dbInterface.updateRec (ContentValues recValues, long id)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
insertRec()
long com.gtfp.workingmemory.db.dbInterface.insertRec (ContentValues recValues)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
createEmptyTemp()
boolean com.gtfp.workingmemory.db.dbInterface.createEmptyTemp ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.createEmptyTemp().
insertTempRec()
long com.gtfp.workingmemory.db.dbInterface.insertTempRec ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.insertTempRec().
getNewTempRecs()
Cursor com.gtfp.workingmemory.db.dbInterface.getNewTempRecs ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.getNewTempRecs().
ifNewRec()
boolean com.gtfp.workingmemory.db.dbInterface.ifNewRec ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.insertIfNewRec().
bindRecValues()
void com.gtfp.workingmemory.db.dbInterface.bindRecValues (String columnName, String value)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.importRec().
importRec()
boolean com.gtfp.workingmemory.db.dbInterface.importRec ()
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
Referenced by com.gtfp.workingmemory.app.appModel.importRec(), and com.gtfp.workingmemory.app.appModel.insertIfNewRec().
getRecs() [2/2]
Cursor com.gtfp.workingmemory.db.dbInterface.getRecs (String whereClause)
Implemented in com.gtfp.workingmemory.db.dbFireBase, and com.gtfp.workingmemory.db.dbSQLlite.
getRecord()
Cursor com.gtfp.workingmemory.db.dbInterface.getRecord (int rowId)
Implemented in com.gtfp.workingmemory.db.dbSQLlite, and com.gtfp.workingmemory.db.dbFireBase.
Referenced by com.gtfp.workingmemory.app.appModel.getRecord().
onDestroy()
void com.gtfp.workingmemory.db.dbInterface.onDestroy ()
Implemented in com.gtfp.workingmemory.db.dbSQLlite, and com.gtfp.workingmemory.db.dbFireBase.
Referenced by com.gtfp.workingmemory.app.appModel.onDestroy(), and com.gtfp.workingmemory.app.appModel.resetDBHelper().