Working Memory: com.gtfp.workingmemory.db.dbSQLParser Class Reference
com.gtfp.workingmemory.db.dbSQLParser Class Reference
Static Public Member Functions
static List< String > parseSqlFile (String sqlFile, AssetManager assetManager) throws IOException
static List< String > parseSqlFile (InputStream is) throws IOException
static boolean exists (String fileName, String path, AssetManager assetManager) throws IOException
static String [] list (String path, AssetManager assetManager) throws IOException
Static Private Member Functions
static String removeComments (InputStream is) throws IOException
static List< String > splitSqlScript (String script, char delim)
Detailed Description
Definition at line 17 of file dbSQLParser.java.
Member Function Documentation
parseSqlFile() [1/2]
static List<String> com.gtfp.workingmemory.db.dbSQLParser.parseSqlFile (String sqlFile, AssetManager assetManager) throws IOException static
Definition at line 19 of file dbSQLParser.java.
parseSqlFile() [2/2]
static List<String> com.gtfp.workingmemory.db.dbSQLParser.parseSqlFile (InputStream is) throws IOException static
Definition at line 37 of file dbSQLParser.java.
References com.gtfp.workingmemory.db.dbSQLParser.removeComments(), and com.gtfp.workingmemory.db.dbSQLParser.splitSqlScript().
removeComments()
static String com.gtfp.workingmemory.db.dbSQLParser.removeComments (InputStream is) throws IOException static private
Definition at line 44 of file dbSQLParser.java.
Referenced by com.gtfp.workingmemory.db.dbSQLParser.parseSqlFile().
splitSqlScript()
static List<String> com.gtfp.workingmemory.db.dbSQLParser.splitSqlScript (String script, char delim) static private
Definition at line 110 of file dbSQLParser.java.
Referenced by com.gtfp.workingmemory.db.dbSQLParser.parseSqlFile().
exists()
static boolean com.gtfp.workingmemory.db.dbSQLParser.exists (String fileName, String path, AssetManager assetManager) throws IOException static
Definition at line 149 of file dbSQLParser.java.
list()
static String [] com.gtfp.workingmemory.db.dbSQLParser.list (String path, AssetManager assetManager) throws IOException static
Definition at line 161 of file dbSQLParser.java.
Referenced by com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.SQLHelper.setTheGrade(), and com.gtfp.workingmemory.db.dbSQLlite.setTheGrade().