Working Memory: com.gtfp.workingmemory.utils.Dialogue Class Reference
com.gtfp.workingmemory.utils.Dialogue Class Reference
Created by Drawn on 2015-08-04.
Public Member Functions
Dialogue (Activity activity)
void show ()
void onDestroy ()
Private Member Functions
AlertDialog buildDialog ()
void Delete ()
void Edit ()
void Cancel ()
Private Attributes
final String mMessage
final int mId
final ToDoItem mItemToDo
Activity mActivity
AlertDialog mDialog
Intent mIntent
ToDoAlarm.Manager mAlarmManager
Detailed Description
Created by Drawn on 2015-08-04.
Definition at line 17 of file Dialogue.java.
Constructor & Destructor Documentation
Dialogue()
com.gtfp.workingmemory.utils.Dialogue.Dialogue (Activity activity)
Definition at line 35 of file Dialogue.java.
References com.gtfp.workingmemory.utils.Dialogue.buildDialog(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay(), com.gtfp.workingmemory.todo.ToDoItem.getId(), and com.gtfp.workingmemory.todo.ToDoItem.itemToDisplay().
Member Function Documentation
show()
void com.gtfp.workingmemory.utils.Dialogue.show ()
Definition at line 59 of file Dialogue.java.
Referenced by com.gtfp.workingmemory.edit.AlarmActivity.onCreate().
buildDialog()
AlertDialog com.gtfp.workingmemory.utils.Dialogue.buildDialog () private
Definition at line 66 of file Dialogue.java.
References com.gtfp.workingmemory.utils.Dialogue.Cancel(), com.gtfp.workingmemory.utils.Dialogue.Delete(), and com.gtfp.workingmemory.utils.Dialogue.Edit().
Referenced by com.gtfp.workingmemory.utils.Dialogue.Dialogue().
Delete()
void com.gtfp.workingmemory.utils.Dialogue.Delete () private
Definition at line 113 of file Dialogue.java.
References com.gtfp.workingmemory.app.appView.close(), com.gtfp.workingmemory.app.appView.delete(), and com.gtfp.workingmemory.app.appView.open().
Referenced by com.gtfp.workingmemory.utils.Dialogue.buildDialog().
Edit()
void com.gtfp.workingmemory.utils.Dialogue.Edit () private
Definition at line 128 of file Dialogue.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification().
Referenced by com.gtfp.workingmemory.utils.Dialogue.buildDialog().
Cancel()
void com.gtfp.workingmemory.utils.Dialogue.Cancel () private
Definition at line 143 of file Dialogue.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification().
Referenced by com.gtfp.workingmemory.utils.Dialogue.buildDialog().
onDestroy()
void com.gtfp.workingmemory.utils.Dialogue.onDestroy ()
Definition at line 155 of file Dialogue.java.
References com.gtfp.workingmemory.utils.Dialogue.mAlarmManager.
Referenced by com.gtfp.workingmemory.edit.AlarmActivity.onDestroy().
Member Data Documentation
mMessage
final String com.gtfp.workingmemory.utils.Dialogue.mMessage private
Definition at line 19 of file Dialogue.java.
mId
final int com.gtfp.workingmemory.utils.Dialogue.mId private
Definition at line 21 of file Dialogue.java.
mItemToDo
final ToDoItem com.gtfp.workingmemory.utils.Dialogue.mItemToDo private
Definition at line 23 of file Dialogue.java.
mActivity
Activity com.gtfp.workingmemory.utils.Dialogue.mActivity private
Definition at line 25 of file Dialogue.java.
mDialog
AlertDialog com.gtfp.workingmemory.utils.Dialogue.mDialog private
Definition at line 27 of file Dialogue.java.
mIntent
Intent com.gtfp.workingmemory.utils.Dialogue.mIntent private
Definition at line 29 of file Dialogue.java.
mAlarmManager
ToDoAlarm.Manager com.gtfp.workingmemory.utils.Dialogue.mAlarmManager private
Definition at line 31 of file Dialogue.java.
Referenced by com.gtfp.workingmemory.utils.Dialogue.onDestroy().