Working Memory: com.gtfp.workingmemory.edit.editToDoItem Class Reference
com.gtfp.workingmemory.edit.editToDoItem Class Reference
Created by Drawn on 2015-02-19.
Public Member Functions
void setupDateTimePicker ()
void saveToDoItem (View SaveBtn)
boolean testPastDue (Calendar cal, boolean toast)
void onTimeChanged (TimePicker timePicker, int hour, int minute)
void onTimeSet (RadialTimePickerDialogFragment dialog, int hourOfDay, int minute)
void settings (View view)
void colorWheel (View colorWheelBtn)
void colorChanged (int color)
void onDateChanged (DatePicker datePicker, int year, int month, int day)
void showSoftKeyboard (View view)
Public Attributes
TextView editDueDate
Calendar mOldDate
Calendar mDateTime
TimePicker mTP
boolean mCanSnooze = false
Static Public Attributes
static final String FRAG_TAG_TIME_PICKER = "fragTimePicker"
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onActivityResult (int requestCode, int resultCode, Intent data)
void onResume ()
void onDestroy ()
Private Member Functions
void setDialogTitle ()
String getDateString (Calendar cal)
boolean isDateChanged ()
void advanceDate (int step)
int getLEDColor ()
boolean runActivity (Class<?> cls)
Private Attributes
int mREQUEST_CODE
Intent mIntent
EditedText mEditItem
ToDoItem mToDoItem
RadioGroupTableLayout editReminder
Calendar mToday
DatePicker mDP
Dialog mDialog
boolean mIgnoreCall = false
boolean mDateChanged = false
int mOldMin = 0
int mOldHour = 0
int mCrossMidNight = 0
boolean mPastDue = false
InputMethodManager mInputMnger
ImageButton mImageButton
Static Private Attributes
static final String TODOITEM = "item"
Detailed Description
Created by Drawn on 2015-02-19.
Definition at line 37 of file editToDoItem.java.
Member Function Documentation
onCreate()
void com.gtfp.workingmemory.edit.editToDoItem.onCreate (Bundle savedInstanceState) protected
Definition at line 44 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.check(), com.gtfp.workingmemory.todo.ToDoItem.displayDueDate(), com.gtfp.workingmemory.todo.ToDoItem.displayTime(), com.gtfp.workingmemory.edit.editToDoItem.editDueDate, com.gtfp.workingmemory.edit.editToDoItem.editReminder, com.gtfp.workingmemory.edit.RadioGroupTableLayout.enableButtons(), com.gtfp.workingmemory.settings.appSettings.getBoolean(), com.gtfp.workingmemory.todo.ToDoItem.getCalendar(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.edit.editToDoItem.mCanSnooze, com.gtfp.workingmemory.edit.editToDoItem.mDateTime, com.gtfp.workingmemory.edit.editToDoItem.mDialog, com.gtfp.workingmemory.edit.editToDoItem.mEditItem, com.gtfp.workingmemory.edit.editToDoItem.mImageButton, com.gtfp.workingmemory.edit.editToDoItem.mIntent, com.gtfp.workingmemory.edit.editToDoItem.mOldDate, com.gtfp.workingmemory.edit.editToDoItem.mPastDue, com.gtfp.workingmemory.edit.editToDoItem.mREQUEST_CODE, com.gtfp.workingmemory.edit.editToDoItem.mToday, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, com.gtfp.workingmemory.edit.EditedText.setText(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.edit.editToDoItem.testPastDue(), and com.gtfp.workingmemory.edit.editToDoItem.TODOITEM.
setupDateTimePicker()
void com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker ()
Definition at line 148 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.editDueDate, com.gtfp.workingmemory.edit.editToDoItem.editReminder, com.gtfp.workingmemory.edit.RadioGroupTableLayout.enableButtons(), com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.getCheckedRadioButtonId(), com.gtfp.workingmemory.edit.editToDoItem.getDateString(), com.gtfp.workingmemory.todo.ToDoItem.getDay(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getHour(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getMin(), com.gtfp.workingmemory.todo.ToDoItem.getMonth(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.settings.appSettings.getString(), com.gtfp.workingmemory.todo.ToDoItem.getYear(), com.gtfp.workingmemory.todo.ToDoItem.hasFired(), com.gtfp.workingmemory.edit.editToDoItem.mCanSnooze, com.gtfp.workingmemory.edit.editToDoItem.mDateTime, com.gtfp.workingmemory.edit.editToDoItem.mDialog, com.gtfp.workingmemory.edit.editToDoItem.mDP, com.gtfp.workingmemory.edit.editToDoItem.mOldDate, com.gtfp.workingmemory.edit.editToDoItem.mOldHour, com.gtfp.workingmemory.edit.editToDoItem.mOldMin, com.gtfp.workingmemory.edit.editToDoItem.mPastDue, com.gtfp.workingmemory.edit.editToDoItem.mToday, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, com.gtfp.workingmemory.edit.editToDoItem.mTP, com.gtfp.workingmemory.todo.ToDoItem.newItem(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.setCheckedStateForView(), com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch(), com.gtfp.workingmemory.edit.editToDoItem.testPastDue(), and com.gtfp.workingmemory.todo.ToDoItem.TodayInEpoch().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate().
setDialogTitle()
void com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle () private
Definition at line 319 of file editToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D_12H(), com.gtfp.workingmemory.edit.editToDoItem.mDialog, com.gtfp.workingmemory.edit.editToDoItem.mDP, com.gtfp.workingmemory.edit.editToDoItem.mOldHour, com.gtfp.workingmemory.edit.editToDoItem.mOldMin, and com.gtfp.workingmemory.todo.ToDoItem.toEpoch().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
saveToDoItem()
void com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem (View SaveBtn)
Definition at line 326 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.editReminder, com.gtfp.workingmemory.edit.RadioGroupTableLayout.getCheckedRadioButtonId(), com.gtfp.workingmemory.edit.editToDoItem.getDateString(), com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.edit.EditedText.isChanged(), com.gtfp.workingmemory.edit.editToDoItem.isDateChanged(), com.gtfp.workingmemory.todo.ToDoItem.LEDColorChanged(), com.gtfp.workingmemory.todo.ToDoItem.LEDOffChanged(), com.gtfp.workingmemory.todo.ToDoItem.LEDOnChanged(), com.gtfp.workingmemory.edit.editToDoItem.mCanSnooze, com.gtfp.workingmemory.edit.editToDoItem.mDateTime, com.gtfp.workingmemory.edit.editToDoItem.mEditItem, com.gtfp.workingmemory.edit.editToDoItem.mIntent, com.gtfp.workingmemory.edit.editToDoItem.mPastDue, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, com.gtfp.workingmemory.todo.ToDoItem.setAlarm(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.todo.ToDoItem.setItemName(), com.gtfp.workingmemory.todo.ToDoItem.setReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.settingsChanged(), and com.gtfp.workingmemory.edit.editToDoItem.testPastDue().
testPastDue()
boolean com.gtfp.workingmemory.edit.editToDoItem.testPastDue (Calendar cal, boolean toast)
Definition at line 468 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.getDateString(), com.gtfp.workingmemory.todo.ToDoItem.isSameDay(), and com.gtfp.workingmemory.edit.editToDoItem.mToday.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getDateString()
String com.gtfp.workingmemory.edit.editToDoItem.getDateString (Calendar cal) private
Definition at line 508 of file editToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), and com.gtfp.workingmemory.edit.editToDoItem.testPastDue().
isDateChanged()
boolean com.gtfp.workingmemory.edit.editToDoItem.isDateChanged () private
Definition at line 514 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mDateTime, and com.gtfp.workingmemory.edit.editToDoItem.mOldDate.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem().
onTimeChanged()
void com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged (TimePicker timePicker, int hour, int minute)
Definition at line 520 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.advanceDate(), com.gtfp.workingmemory.edit.editToDoItem.mCanSnooze, com.gtfp.workingmemory.edit.editToDoItem.mCrossMidNight, com.gtfp.workingmemory.edit.editToDoItem.mDateChanged, com.gtfp.workingmemory.edit.editToDoItem.mIgnoreCall, com.gtfp.workingmemory.edit.editToDoItem.mOldHour, com.gtfp.workingmemory.edit.editToDoItem.mOldMin, and com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onTimeSet().
onTimeSet()
void com.gtfp.workingmemory.edit.editToDoItem.onTimeSet (RadialTimePickerDialogFragment dialog, int hourOfDay, int minute)
Definition at line 593 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mTP, and com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged().
advanceDate()
void com.gtfp.workingmemory.edit.editToDoItem.advanceDate (int step) private
Definition at line 603 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mDateTime, and com.gtfp.workingmemory.edit.editToDoItem.mDP.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged().
settings()
void com.gtfp.workingmemory.edit.editToDoItem.settings (View view)
Definition at line 619 of file editToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.mIntent, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, com.gtfp.workingmemory.edit.editToDoItem.runActivity(), and com.gtfp.workingmemory.edit.editToDoItem.TODOITEM.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.getLEDColor().
colorWheel()
void com.gtfp.workingmemory.edit.editToDoItem.colorWheel (View colorWheelBtn)
Definition at line 634 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOn(), com.gtfp.workingmemory.colorPicker.colorPickerActivity.getLEDRates(), com.gtfp.workingmemory.colorPicker.colorPickerView.init(), com.gtfp.workingmemory.edit.editToDoItem.mREQUEST_CODE, and com.gtfp.workingmemory.edit.editToDoItem.mToDoItem.
getLEDColor()
int com.gtfp.workingmemory.edit.editToDoItem.getLEDColor () private
Definition at line 660 of file editToDoItem.java.
References com.gtfp.workingmemory.settings.appSettings.get(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, com.gtfp.workingmemory.todo.ToDoItem.setLEDColor(), and com.gtfp.workingmemory.edit.editToDoItem.settings().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorWheel().
colorChanged()
void com.gtfp.workingmemory.edit.editToDoItem.colorChanged (int color)
Implements com.gtfp.workingmemory.colorPicker.colorPickerView.OnColorChangedListener.
Definition at line 679 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mImageButton, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, and com.gtfp.workingmemory.todo.ToDoItem.setLEDColor().
runActivity()
boolean com.gtfp.workingmemory.edit.editToDoItem.runActivity (Class<?> cls) private
Definition at line 687 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mIntent, and com.gtfp.workingmemory.edit.editToDoItem.mREQUEST_CODE.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.settings().
onActivityResult()
void com.gtfp.workingmemory.edit.editToDoItem.onActivityResult (int requestCode, int resultCode, Intent data) protected
Definition at line 713 of file editToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.clearNotification(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmUri(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOn(), com.gtfp.workingmemory.edit.editToDoItem.mREQUEST_CODE, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, com.gtfp.workingmemory.todo.ToDoItem.setClearNotification(), com.gtfp.workingmemory.todo.ToDoItem.setLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.setLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.setLEDOn(), com.gtfp.workingmemory.todo.ToDoItem.setShowDialogue(), com.gtfp.workingmemory.todo.ToDoItem.setSound(), com.gtfp.workingmemory.todo.ToDoItem.setUseLED(), com.gtfp.workingmemory.todo.ToDoItem.setUseVibrate(), com.gtfp.workingmemory.todo.ToDoItem.showDialogue(), com.gtfp.workingmemory.todo.ToDoItem.Sound(), com.gtfp.workingmemory.edit.editToDoItem.TODOITEM, com.gtfp.workingmemory.todo.ToDoItem.useLED(), and com.gtfp.workingmemory.todo.ToDoItem.useVibrate().
onDateChanged()
void com.gtfp.workingmemory.edit.editToDoItem.onDateChanged (DatePicker datePicker, int year, int month, int day)
Definition at line 753 of file editToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D_12H(), com.gtfp.workingmemory.edit.editToDoItem.mCrossMidNight, com.gtfp.workingmemory.edit.editToDoItem.mDateChanged, com.gtfp.workingmemory.edit.editToDoItem.mDateTime, com.gtfp.workingmemory.edit.editToDoItem.mDialog, com.gtfp.workingmemory.edit.editToDoItem.mOldDate, com.gtfp.workingmemory.edit.editToDoItem.mOldHour, com.gtfp.workingmemory.edit.editToDoItem.mOldMin, and com.gtfp.workingmemory.todo.ToDoItem.toEpoch().
showSoftKeyboard()
void com.gtfp.workingmemory.edit.editToDoItem.showSoftKeyboard (View view)
Definition at line 774 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mInputMnger.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onResume().
onResume()
void com.gtfp.workingmemory.edit.editToDoItem.onResume () protected
Definition at line 820 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mEditItem, and com.gtfp.workingmemory.edit.editToDoItem.showSoftKeyboard().
onDestroy()
void com.gtfp.workingmemory.edit.editToDoItem.onDestroy () protected
Definition at line 837 of file editToDoItem.java.
References com.gtfp.workingmemory.edit.editToDoItem.mDateTime, com.gtfp.workingmemory.edit.editToDoItem.mDP, com.gtfp.workingmemory.edit.editToDoItem.mIntent, com.gtfp.workingmemory.edit.editToDoItem.mToday, com.gtfp.workingmemory.edit.editToDoItem.mToDoItem, and com.gtfp.workingmemory.edit.editToDoItem.mTP.
Member Data Documentation
FRAG_TAG_TIME_PICKER
final String com.gtfp.workingmemory.edit.editToDoItem.FRAG_TAG_TIME_PICKER = "fragTimePicker" static
Definition at line 41 of file editToDoItem.java.
mREQUEST_CODE
int com.gtfp.workingmemory.edit.editToDoItem.mREQUEST_CODE private
Definition at line 855 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorWheel(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), and com.gtfp.workingmemory.edit.editToDoItem.runActivity().
TODOITEM
final String com.gtfp.workingmemory.edit.editToDoItem.TODOITEM = "item" static private
Definition at line 857 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), and com.gtfp.workingmemory.edit.editToDoItem.settings().
mIntent
Intent com.gtfp.workingmemory.edit.editToDoItem.mIntent private
Definition at line 859 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onDestroy(), com.gtfp.workingmemory.edit.editToDoItem.runActivity(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.settings().
mEditItem
EditedText com.gtfp.workingmemory.edit.editToDoItem.mEditItem private
Definition at line 861 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onResume(), and com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem().
mToDoItem
ToDoItem com.gtfp.workingmemory.edit.editToDoItem.mToDoItem private
Definition at line 863 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorChanged(), com.gtfp.workingmemory.edit.editToDoItem.colorWheel(), com.gtfp.workingmemory.edit.editToDoItem.getLEDColor(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onDestroy(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.edit.editToDoItem.settings(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
editDueDate
TextView com.gtfp.workingmemory.edit.editToDoItem.editDueDate
Definition at line 865 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
editReminder
RadioGroupTableLayout com.gtfp.workingmemory.edit.editToDoItem.editReminder private
Definition at line 867 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mToday
Calendar com.gtfp.workingmemory.edit.editToDoItem.mToday private
Definition at line 869 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onDestroy(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), and com.gtfp.workingmemory.edit.editToDoItem.testPastDue().
mOldDate
Calendar com.gtfp.workingmemory.edit.editToDoItem.mOldDate
Definition at line 871 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.isDateChanged(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mDateTime
Calendar com.gtfp.workingmemory.edit.editToDoItem.mDateTime
Definition at line 873 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.advanceDate(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.enableButtons(), com.gtfp.workingmemory.edit.editToDoItem.isDateChanged(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), com.gtfp.workingmemory.edit.editToDoItem.onDestroy(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mDP
DatePicker com.gtfp.workingmemory.edit.editToDoItem.mDP private
Definition at line 875 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.advanceDate(), com.gtfp.workingmemory.edit.editToDoItem.onDestroy(), com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mTP
TimePicker com.gtfp.workingmemory.edit.editToDoItem.mTP
Definition at line 877 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onDestroy(), com.gtfp.workingmemory.edit.editToDoItem.onTimeSet(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mDialog
Dialog com.gtfp.workingmemory.edit.editToDoItem.mDialog private
Definition at line 879 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mIgnoreCall
boolean com.gtfp.workingmemory.edit.editToDoItem.mIgnoreCall = false private
Definition at line 881 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged().
mDateChanged
boolean com.gtfp.workingmemory.edit.editToDoItem.mDateChanged = false private
Definition at line 883 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), and com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged().
mOldMin
int com.gtfp.workingmemory.edit.editToDoItem.mOldMin = 0 private
Definition at line 885 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged(), com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mOldHour
int com.gtfp.workingmemory.edit.editToDoItem.mOldHour = 0 private
Definition at line 887 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged(), com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mCrossMidNight
int com.gtfp.workingmemory.edit.editToDoItem.mCrossMidNight = 0 private
Definition at line 889 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), and com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged().
mCanSnooze
boolean com.gtfp.workingmemory.edit.editToDoItem.mCanSnooze = false
Definition at line 891 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.onTimeChanged(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mPastDue
boolean com.gtfp.workingmemory.edit.editToDoItem.mPastDue = false private
Definition at line 893 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
mInputMnger
InputMethodManager com.gtfp.workingmemory.edit.editToDoItem.mInputMnger private
Definition at line 895 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.showSoftKeyboard().
mImageButton
ImageButton com.gtfp.workingmemory.edit.editToDoItem.mImageButton private
Definition at line 897 of file editToDoItem.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorChanged(), and com.gtfp.workingmemory.edit.editToDoItem.onCreate().