Working Memory: com.gtfp.workingmemory.frmwrk.frmwrkDate Class Reference
com.gtfp.workingmemory.frmwrk.frmwrkDate Class Reference
Created by Drawn on 2015-03-12.
Classes
class DateParts
Public Member Functions
frmwrkDate (TimeZone m_timeZone)
void fastDate (final String date)
long parse (final String dateTime)
Private Member Functions
void checkDate (final String date)
void checkDateTime (final String dateTime)
long [] prepareDate (final DateParts dp)
Static Private Member Functions
static boolean allDigits (final String s, final int[] positions)
static int two (final String s, final int from)
static int four (final String s)
static DateParts parseDate (final String s)
static void checkDateParts (final int year, final int month, final int day)
static void checkTimeParts (final int hour, final int min, final int sec)
Private Attributes
final Map< String, long[]> m_cache = new HashMap<String, long[]>(20)
final TimeZone m_timeZone
Static Private Attributes
static final int [] DATE_DIGITS = { 0, 1, 2, 3, 5, 6, 8, 9 }
static final int [] DATETIME_DIGITS = { 0, 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18 }
static final int [] MAX_DAY = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
static final int TWO_SUBTRACT = '0' * 11
Detailed Description
Created by Drawn on 2015-03-12.
Definition at line 12 of file frmwrkDate.java.
Constructor & Destructor Documentation
frmwrkDate()
com.gtfp.workingmemory.frmwrk.frmwrkDate.frmwrkDate (TimeZone m_timeZone)
Definition at line 21 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.m_timeZone.
Member Function Documentation
allDigits()
static boolean com.gtfp.workingmemory.frmwrk.frmwrkDate.allDigits (final String s, final int [] positions) static private
Definition at line 39 of file frmwrkDate.java.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDate(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDateTime().
two()
static int com.gtfp.workingmemory.frmwrk.frmwrkDate.two (final String s, final int from) static private
Definition at line 52 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.TWO_SUBTRACT.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.four(), com.gtfp.workingmemory.frmwrk.frmwrkDate.parse(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.parseDate().
four()
static int com.gtfp.workingmemory.frmwrk.frmwrkDate.four (final String s) static private
Definition at line 57 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.two().
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.parse(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.parseDate().
parseDate()
static DateParts com.gtfp.workingmemory.frmwrk.frmwrkDate.parseDate (final String s) static private
Definition at line 62 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.DateParts(), com.gtfp.workingmemory.frmwrk.frmwrkDate.four(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.two().
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.fastDate().
fastDate()
void com.gtfp.workingmemory.frmwrk.frmwrkDate.fastDate (final String date)
Definition at line 67 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDate(), com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDateParts(), com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.day, com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.month, com.gtfp.workingmemory.frmwrk.frmwrkDate.parseDate(), com.gtfp.workingmemory.frmwrk.frmwrkDate.prepareDate(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.year.
checkDateParts()
static void com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDateParts (final int year, final int month, final int day) static private
Definition at line 75 of file frmwrkDate.java.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.fastDate(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.parse().
checkTimeParts()
static void com.gtfp.workingmemory.frmwrk.frmwrkDate.checkTimeParts (final int hour, final int min, final int sec) static private
Definition at line 95 of file frmwrkDate.java.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.parse().
checkDate()
void com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDate (final String date) private
Definition at line 105 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.allDigits().
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.fastDate().
checkDateTime()
void com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDateTime (final String dateTime) private
Definition at line 112 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.allDigits().
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.parse().
prepareDate()
long [] com.gtfp.workingmemory.frmwrk.frmwrkDate.prepareDate (final DateParts dp) private
Definition at line 120 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.day, com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.month, and com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.year.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.fastDate().
parse()
long com.gtfp.workingmemory.frmwrk.frmwrkDate.parse (final String dateTime)
Definition at line 132 of file frmwrkDate.java.
References com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDateParts(), com.gtfp.workingmemory.frmwrk.frmwrkDate.checkDateTime(), com.gtfp.workingmemory.frmwrk.frmwrkDate.checkTimeParts(), com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.day, com.gtfp.workingmemory.frmwrk.frmwrkDate.four(), com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.month, com.gtfp.workingmemory.frmwrk.frmwrkDate.two(), and com.gtfp.workingmemory.frmwrk.frmwrkDate.DateParts.year.
Member Data Documentation
DATE_DIGITS
final int [] com.gtfp.workingmemory.frmwrk.frmwrkDate.DATE_DIGITS = { 0, 1, 2, 3, 5, 6, 8, 9 } static private
Definition at line 14 of file frmwrkDate.java.
DATETIME_DIGITS
final int [] com.gtfp.workingmemory.frmwrk.frmwrkDate.DATETIME_DIGITS = { 0, 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18 } static private
Definition at line 15 of file frmwrkDate.java.
MAX_DAY
final int [] com.gtfp.workingmemory.frmwrk.frmwrkDate.MAX_DAY = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static private
Definition at line 16 of file frmwrkDate.java.
m_cache
final Map<String, long[]> com.gtfp.workingmemory.frmwrk.frmwrkDate.m_cache = new HashMap<String, long[]>(20) private
Definition at line 18 of file frmwrkDate.java.
m_timeZone
final TimeZone com.gtfp.workingmemory.frmwrk.frmwrkDate.m_timeZone private
Definition at line 19 of file frmwrkDate.java.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.frmwrkDate().
TWO_SUBTRACT
final int com.gtfp.workingmemory.frmwrk.frmwrkDate.TWO_SUBTRACT = '0' * 11 static private
Definition at line 50 of file frmwrkDate.java.
Referenced by com.gtfp.workingmemory.frmwrk.frmwrkDate.two().