Working Memory: com.gtfp.workingmemory.edit.rowView Class Reference
com.gtfp.workingmemory.edit.rowView Class Reference
Public Member Functions
rowView ()
void setTextOriginal ()
void markAsDeleted ()
void highLightHolder (Context context)
boolean setFont (Context context)
void unHighLightHolder ()
Public Attributes
TextView mTextView
TextView itemDueDateView
ImageView priorityImage
LinearLayout container
int position
Private Attributes
int mOriginalPaintFlags
Typeface mTypeface
ColorStateList mTextColor
Detailed Description
Definition at line 14 of file rowView.java.
Constructor & Destructor Documentation
rowView()
com.gtfp.workingmemory.edit.rowView.rowView ()
Definition at line 32 of file rowView.java.
Member Function Documentation
setTextOriginal()
void com.gtfp.workingmemory.edit.rowView.setTextOriginal ()
Definition at line 37 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
markAsDeleted()
void com.gtfp.workingmemory.edit.rowView.markAsDeleted ()
Definition at line 51 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
highLightHolder()
void com.gtfp.workingmemory.edit.rowView.highLightHolder (Context context)
Definition at line 70 of file rowView.java.
setFont()
boolean com.gtfp.workingmemory.edit.rowView.setFont (Context context)
Definition at line 83 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
unHighLightHolder()
void com.gtfp.workingmemory.edit.rowView.unHighLightHolder ()
Definition at line 106 of file rowView.java.
Member Data Documentation
mTextView
TextView com.gtfp.workingmemory.edit.rowView.mTextView
Definition at line 16 of file rowView.java.
Referenced by com.gtfp.workingmemory.app.appView.getRowTitle(), and com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
itemDueDateView
TextView com.gtfp.workingmemory.edit.rowView.itemDueDateView
Definition at line 18 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
priorityImage
ImageView com.gtfp.workingmemory.edit.rowView.priorityImage
Definition at line 20 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
container
LinearLayout com.gtfp.workingmemory.edit.rowView.container
Definition at line 22 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
position
int com.gtfp.workingmemory.edit.rowView.position
Definition at line 24 of file rowView.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getView().
mOriginalPaintFlags
int com.gtfp.workingmemory.edit.rowView.mOriginalPaintFlags private
Definition at line 26 of file rowView.java.
mTypeface
Typeface com.gtfp.workingmemory.edit.rowView.mTypeface private
Definition at line 28 of file rowView.java.
mTextColor
ColorStateList com.gtfp.workingmemory.edit.rowView.mTextColor private
Definition at line 30 of file rowView.java.