Working Memory: com.gtfp.workingmemory.db.dbFireBase Class Reference
com.gtfp.workingmemory.db.dbFireBase Class Reference
Created by Drawn on 9/27/2016.
Classes
class dbTasksData
interface DesiredField
interface OnDataListener
class Sync
class Tasks
Public Member Functions
void onAuthStateChanged (@NonNull FirebaseAuth auth)
dbInterface open ()
dbInterface open (OnDataListener listener)
boolean isOpen ()
void close ()
void goOffline ()
boolean createCurrentRecs ()
void clearResultSet ()
Cursor getResultSet ()
boolean showDeleted (boolean showDeleted)
Cursor runQuery (String sqlStmt)
Cursor getRecs ()
Cursor getRecord (int rowId)
Cursor getCurrentRecs ()
Cursor getDeletedRecs ()
String getLastRowID ()
int deleteRec (Long rowID)
boolean save (ToDoItem itemToDo)
boolean markRec (Long id)
boolean markRec (final String key)
int updateRec (ToDoItem itemToDo)
int updateRec (ContentValues recValues, long id)
long insertRec (ContentValues recValues)
ContentValues bindRecValues (ToDoItem itemToDo)
void bindRecValues (String columnName, String value)
boolean createEmptyTemp ()
long insertTempRec ()
Cursor getNewTempRecs ()
boolean ifNewRec ()
boolean importRec ()
Cursor getRecs (String whereClause)
ArrayList< HashMap< String, String > > getDataArrayList ()
ArrayList< ToDoItem > ToDoList (ArrayList< HashMap< String, String >> recs)
boolean setOnDataListener (OnDataListener listener)
boolean removeOnDataListener (OnDataListener listener)
void onDestroy ()
Static Public Member Functions
static dbInterface getInstance (appView mVc)
static ArrayList< HashMap< String, String > > recArrayList (DataSnapshot snapshot, boolean showDeleted)
static FirebaseDatabase getDatabase ()
static void sync ()
Static Package Functions
static DatabaseReference prevUserIdDBRef ()
Private Member Functions
dbFireBase (appView mVc)
String insertRec (ToDoItem itemToDo)
Tasks setTask (ToDoItem item)
Map< String, Object > toMap (ToDoItem item)
Static Private Member Functions
static ArrayList< HashMap< String, String > > recArrayList (DataSnapshot snapshot)
static DatabaseReference tasksRef ()
static DatabaseReference tasksRef (String id)
static boolean isOnline ()
Private Attributes
appView mAppView
FirebaseApp mApp
Context mContext
ContentValues mRecValues
String mLastRowID
Set< OnDataListener > mOnDataListeners = new HashSet<>()
dbTasksData mTaskData
Static Private Attributes
static dbFireBase mThis
static FirebaseDatabase mDatabase
static boolean mShowDeleted
static ArrayList< HashMap< String, String > > mDataArrayList
static Cursor mResultSet
static String [] mDataFields
Detailed Description
Created by Drawn on 9/27/2016.
Definition at line 40 of file dbFireBase.java.
Constructor & Destructor Documentation
dbFireBase()
com.gtfp.workingmemory.db.dbFireBase.dbFireBase (appView mVc) private
Definition at line 72 of file dbFireBase.java.
References com.gtfp.workingmemory.Auth.Auth.addAuthStateListener(), and com.gtfp.workingmemory.app.appView.getContext().
Referenced by com.gtfp.workingmemory.db.dbFireBase.getInstance().
Member Function Documentation
getInstance()
static dbInterface com.gtfp.workingmemory.db.dbFireBase.getInstance (appView mVc) static
Definition at line 93 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.dbFireBase(), and com.gtfp.workingmemory.db.dbFireBase.mThis.
Referenced by com.gtfp.workingmemory.app.appModel.appModel().
recArrayList() [1/2]
static ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbFireBase.recArrayList (DataSnapshot snapshot) static private
Definition at line 106 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.createCurrentRecs(), and com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange().
recArrayList() [2/2]
static ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbFireBase.recArrayList (DataSnapshot snapshot, boolean showDeleted) static
Definition at line 115 of file dbFireBase.java.
getDatabase()
static FirebaseDatabase com.gtfp.workingmemory.db.dbFireBase.getDatabase () static
Definition at line 185 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.mDatabase.
Referenced by com.gtfp.workingmemory.db.dbFireBase.prevUserIdDBRef(), and com.gtfp.workingmemory.db.dbFireBase.tasksRef().
prevUserIdDBRef()
static DatabaseReference com.gtfp.workingmemory.db.dbFireBase.prevUserIdDBRef () static package
Definition at line 198 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.getDatabase(), and com.gtfp.workingmemory.Auth.Auth.getPrevUid().
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave().
tasksRef() [1/2]
static DatabaseReference com.gtfp.workingmemory.db.dbFireBase.tasksRef () static private
Definition at line 219 of file dbFireBase.java.
References com.gtfp.workingmemory.Auth.Auth.getUid().
Referenced by com.gtfp.workingmemory.db.dbFireBase.createCurrentRecs(), com.gtfp.workingmemory.db.dbFireBase.insertRec(), com.gtfp.workingmemory.db.dbFireBase.markRec(), com.gtfp.workingmemory.db.dbFireBase.onAuthStateChanged(), and com.gtfp.workingmemory.db.dbFireBase.updateRec().
tasksRef() [2/2]
static DatabaseReference com.gtfp.workingmemory.db.dbFireBase.tasksRef (String id) static private
Definition at line 228 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.getDatabase().
isOnline()
static boolean com.gtfp.workingmemory.db.dbFireBase.isOnline () static private
Definition at line 246 of file dbFireBase.java.
References com.gtfp.workingmemory.app.appView.getController(), com.gtfp.workingmemory.db.dbFireBase.mAppView, and com.gtfp.workingmemory.app.appController.NoConnectivity().
Referenced by com.gtfp.workingmemory.db.dbFireBase.isOpen().
onAuthStateChanged()
void com.gtfp.workingmemory.db.dbFireBase.onAuthStateChanged (@NonNull FirebaseAuth auth)
Definition at line 263 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.tasksRef().
open() [1/2]
dbInterface com.gtfp.workingmemory.db.dbFireBase.open ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 302 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.isOpen().
Referenced by com.gtfp.workingmemory.db.dbFireBase.open().
open() [2/2]
dbInterface com.gtfp.workingmemory.db.dbFireBase.open (OnDataListener listener)
Definition at line 322 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.open(), and com.gtfp.workingmemory.db.dbFireBase.setOnDataListener().
isOpen()
boolean com.gtfp.workingmemory.db.dbFireBase.isOpen ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 333 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.isOnline().
Referenced by com.gtfp.workingmemory.db.dbFireBase.open().
close()
void com.gtfp.workingmemory.db.dbFireBase.close ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 341 of file dbFireBase.java.
goOffline()
void com.gtfp.workingmemory.db.dbFireBase.goOffline ()
Definition at line 347 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.onDestroy().
createCurrentRecs()
boolean com.gtfp.workingmemory.db.dbFireBase.createCurrentRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 358 of file dbFireBase.java.
References com.gtfp.workingmemory.db.Semaphore.got(), com.gtfp.workingmemory.app.appView.onCancelled(), com.gtfp.workingmemory.app.appView.onDataChange(), com.gtfp.workingmemory.db.dbFireBase.recArrayList(), and com.gtfp.workingmemory.db.dbFireBase.tasksRef().
clearResultSet()
void com.gtfp.workingmemory.db.dbFireBase.clearResultSet ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 403 of file dbFireBase.java.
getResultSet()
Cursor com.gtfp.workingmemory.db.dbFireBase.getResultSet ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 411 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.mResultSet.
showDeleted()
boolean com.gtfp.workingmemory.db.dbFireBase.showDeleted (boolean showDeleted)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 468 of file dbFireBase.java.
runQuery()
Cursor com.gtfp.workingmemory.db.dbFireBase.runQuery (String sqlStmt)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 479 of file dbFireBase.java.
getRecs() [1/2]
Cursor com.gtfp.workingmemory.db.dbFireBase.getRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 487 of file dbFireBase.java.
getRecord()
Cursor com.gtfp.workingmemory.db.dbFireBase.getRecord (int rowId)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 495 of file dbFireBase.java.
getCurrentRecs()
Cursor com.gtfp.workingmemory.db.dbFireBase.getCurrentRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 500 of file dbFireBase.java.
getDeletedRecs()
Cursor com.gtfp.workingmemory.db.dbFireBase.getDeletedRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 508 of file dbFireBase.java.
getLastRowID()
String com.gtfp.workingmemory.db.dbFireBase.getLastRowID ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 516 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.mLastRowID.
deleteRec()
int com.gtfp.workingmemory.db.dbFireBase.deleteRec (Long rowID)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 524 of file dbFireBase.java.
save()
boolean com.gtfp.workingmemory.db.dbFireBase.save (ToDoItem itemToDo)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 532 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.insertRec(), com.gtfp.workingmemory.todo.ToDoItem.newItem(), com.gtfp.workingmemory.todo.ToDoItem.setKey(), com.gtfp.workingmemory.db.dbFireBase.updateRec(), and com.gtfp.workingmemory.db.Semaphore.write().
markRec() [1/2]
boolean com.gtfp.workingmemory.db.dbFireBase.markRec (Long id)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 559 of file dbFireBase.java.
markRec() [2/2]
boolean com.gtfp.workingmemory.db.dbFireBase.markRec (final String key)
Definition at line 563 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.tasksRef(), and com.gtfp.workingmemory.db.Semaphore.write().
updateRec() [1/2]
int com.gtfp.workingmemory.db.dbFireBase.updateRec (ToDoItem itemToDo)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 613 of file dbFireBase.java.
References com.gtfp.workingmemory.todo.ToDoItem.getKey(), com.gtfp.workingmemory.db.dbFireBase.insertRec(), com.gtfp.workingmemory.db.dbFireBase.tasksRef(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
Referenced by com.gtfp.workingmemory.db.dbFireBase.save().
updateRec() [2/2]
int com.gtfp.workingmemory.db.dbFireBase.updateRec (ContentValues recValues, long id)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 659 of file dbFireBase.java.
insertRec() [1/2]
String com.gtfp.workingmemory.db.dbFireBase.insertRec (ToDoItem itemToDo) private
Definition at line 668 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.tasksRef(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
Referenced by com.gtfp.workingmemory.db.dbFireBase.save(), and com.gtfp.workingmemory.db.dbFireBase.updateRec().
insertRec() [2/2]
long com.gtfp.workingmemory.db.dbFireBase.insertRec (ContentValues recValues)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 709 of file dbFireBase.java.
bindRecValues() [1/2]
ContentValues com.gtfp.workingmemory.db.dbFireBase.bindRecValues (ToDoItem itemToDo)
Definition at line 717 of file dbFireBase.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.hasFired(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.db.dbFireBase.mRecValues, and com.gtfp.workingmemory.todo.ToDoItem.setAlarm().
bindRecValues() [2/2]
void com.gtfp.workingmemory.db.dbFireBase.bindRecValues (String columnName, String value)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 746 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbSQLlite.setBindRecInt(), and com.gtfp.workingmemory.db.dbSQLlite.setBindRecLong().
setTask()
Tasks com.gtfp.workingmemory.db.dbFireBase.setTask (ToDoItem item) private
Definition at line 796 of file dbFireBase.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.hasFired(), and com.gtfp.workingmemory.todo.ToDoItem.isDeleted().
toMap()
Map<String, Object> com.gtfp.workingmemory.db.dbFireBase.toMap (ToDoItem item) private
Definition at line 815 of file dbFireBase.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.hasFired(), and com.gtfp.workingmemory.todo.ToDoItem.isDeleted().
Referenced by com.gtfp.workingmemory.db.dbFireBase.insertRec(), and com.gtfp.workingmemory.db.dbFireBase.updateRec().
createEmptyTemp()
boolean com.gtfp.workingmemory.db.dbFireBase.createEmptyTemp ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 847 of file dbFireBase.java.
insertTempRec()
long com.gtfp.workingmemory.db.dbFireBase.insertTempRec ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 855 of file dbFireBase.java.
getNewTempRecs()
Cursor com.gtfp.workingmemory.db.dbFireBase.getNewTempRecs ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 863 of file dbFireBase.java.
ifNewRec()
boolean com.gtfp.workingmemory.db.dbFireBase.ifNewRec ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 871 of file dbFireBase.java.
importRec()
boolean com.gtfp.workingmemory.db.dbFireBase.importRec ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 876 of file dbFireBase.java.
getRecs() [2/2]
Cursor com.gtfp.workingmemory.db.dbFireBase.getRecs (String whereClause)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 884 of file dbFireBase.java.
getDataArrayList()
ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbFireBase.getDataArrayList ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 891 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.mDataArrayList.
ToDoList()
ArrayList<ToDoItem> com.gtfp.workingmemory.db.dbFireBase.ToDoList (ArrayList< HashMap< String, String >> recs)
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 898 of file dbFireBase.java.
References com.gtfp.workingmemory.db.Semaphore.got(), com.gtfp.workingmemory.todo.ToDoItem.hasFired(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.todo.ToDoItem.setAlarm(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.todo.ToDoItem.setId(), com.gtfp.workingmemory.todo.ToDoItem.setItemName(), com.gtfp.workingmemory.todo.ToDoItem.setKey(), com.gtfp.workingmemory.todo.ToDoItem.setLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.setReminderChk(), and com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch().
setOnDataListener()
boolean com.gtfp.workingmemory.db.dbFireBase.setOnDataListener (OnDataListener listener)
Definition at line 993 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.open().
removeOnDataListener()
boolean com.gtfp.workingmemory.db.dbFireBase.removeOnDataListener (OnDataListener listener)
Definition at line 1001 of file dbFireBase.java.
sync()
static void com.gtfp.workingmemory.db.dbFireBase.sync () static
Definition at line 1009 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.Sync.data().
Referenced by com.gtfp.workingmemory.app.appView.syncData().
onDestroy()
void com.gtfp.workingmemory.db.dbFireBase.onDestroy ()
Implements com.gtfp.workingmemory.db.dbInterface.
Definition at line 1018 of file dbFireBase.java.
References com.gtfp.workingmemory.db.dbFireBase.goOffline().
Member Data Documentation
mAppView
appView com.gtfp.workingmemory.db.dbFireBase.mAppView private
Definition at line 43 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.isOnline(), com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onCancelled(), and com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange().
mThis
dbFireBase com.gtfp.workingmemory.db.dbFireBase.mThis static private
Definition at line 45 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.getInstance().
mApp
FirebaseApp com.gtfp.workingmemory.db.dbFireBase.mApp private
Definition at line 47 of file dbFireBase.java.
mDatabase
FirebaseDatabase com.gtfp.workingmemory.db.dbFireBase.mDatabase static private
Definition at line 49 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.getDatabase().
mShowDeleted
boolean com.gtfp.workingmemory.db.dbFireBase.mShowDeleted static private
Definition at line 51 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange().
mDataArrayList
ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbFireBase.mDataArrayList static private
Definition at line 53 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.getDataArrayList(), and com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange().
mResultSet
Cursor com.gtfp.workingmemory.db.dbFireBase.mResultSet static private
Definition at line 55 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.getResultSet().
mDataFields
String [] com.gtfp.workingmemory.db.dbFireBase.mDataFields static private
Definition at line 57 of file dbFireBase.java.
mContext
Context com.gtfp.workingmemory.db.dbFireBase.mContext private
Definition at line 59 of file dbFireBase.java.
mRecValues
ContentValues com.gtfp.workingmemory.db.dbFireBase.mRecValues private
Definition at line 61 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.bindRecValues().
mLastRowID
String com.gtfp.workingmemory.db.dbFireBase.mLastRowID private
Definition at line 63 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.getLastRowID().
mOnDataListeners
Set<OnDataListener> com.gtfp.workingmemory.db.dbFireBase.mOnDataListeners = new HashSet<>() private
Definition at line 65 of file dbFireBase.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange().
mTaskData
dbTasksData com.gtfp.workingmemory.db.dbFireBase.mTaskData private
Definition at line 67 of file dbFireBase.java.