Working Memory: com.gtfp.workingmemory.db.dbCloud.dbLocal Class Reference
com.gtfp.workingmemory.db.dbCloud.dbLocal Class Reference
Public Member Functions
boolean save (ToDoItem itemToDo)
Package Functions
dbLocal (dbInterface dbLocal)
boolean add (HashMap< String, String > cloudItem)
boolean update (HashMap< String, String > cloudItem)
boolean save (HashMap< String, String > cloudItem)
boolean delete (HashMap< String, String > cloudItem)
ToDoItem toToDoItem (HashMap< String, String > cloudItem)
Package Attributes
dbInterface mLocalDB
Detailed Description
Definition at line 557 of file dbCloud.java.
Constructor & Destructor Documentation
dbLocal()
com.gtfp.workingmemory.db.dbCloud.dbLocal.dbLocal (dbInterface dbLocal) package
Definition at line 563 of file dbCloud.java.
Member Function Documentation
add()
boolean com.gtfp.workingmemory.db.dbCloud.dbLocal.add (HashMap< String, String > cloudItem) package
Definition at line 570 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.save().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
update()
boolean com.gtfp.workingmemory.db.dbCloud.dbLocal.update (HashMap< String, String > cloudItem) package
Definition at line 580 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.save().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
save() [1/2]
boolean com.gtfp.workingmemory.db.dbCloud.dbLocal.save (HashMap< String, String > cloudItem) package
Definition at line 587 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.save().
save() [2/2]
boolean com.gtfp.workingmemory.db.dbCloud.dbLocal.save (ToDoItem itemToDo)
Definition at line 603 of file dbCloud.java.
References com.gtfp.workingmemory.todo.ToDoItem.getKey(), com.gtfp.workingmemory.db.dbSQLlite.getRecID(), com.gtfp.workingmemory.db.dbSQLlite.insertRec(), com.gtfp.workingmemory.todo.ToDoItem.newItem(), com.gtfp.workingmemory.todo.ToDoItem.setId(), and com.gtfp.workingmemory.db.dbInterface.updateRec().
delete()
boolean com.gtfp.workingmemory.db.dbCloud.dbLocal.delete (HashMap< String, String > cloudItem) package
Definition at line 633 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbInterface.deleteRec().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
toToDoItem()
ToDoItem com.gtfp.workingmemory.db.dbCloud.dbLocal.toToDoItem (HashMap< String, String > cloudItem) package
Definition at line 649 of file dbCloud.java.
References com.gtfp.workingmemory.todo.ToDoItem.setKey(), and com.gtfp.workingmemory.db.dbInterface.ToDoList().
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave().
Member Data Documentation
mLocalDB
dbInterface com.gtfp.workingmemory.db.dbCloud.dbLocal.mLocalDB package
Definition at line 559 of file dbCloud.java.