Working Memory: com.gtfp.workingmemory.edit.appCRUD Class Reference
com.gtfp.workingmemory.edit.appCRUD Class Reference
Created by Drawn on 2015-03-07.
Public Member Functions
appCRUD (appView mVc)
void newToDoItem ()
void edit (int position)
boolean delete (long id)
void dialogResult (boolean result)
void onDestroy ()
Private Attributes
appView mAppView
Intent mEditIntent
dialog mDialogue
boolean mTrulyDelete = false
int mToDoListID
Detailed Description
Created by Drawn on 2015-03-07.
Definition at line 15 of file appCRUD.java.
Constructor & Destructor Documentation
appCRUD()
com.gtfp.workingmemory.edit.appCRUD.appCRUD (appView mVc)
Definition at line 27 of file appCRUD.java.
References com.gtfp.workingmemory.app.appView.mController, and com.gtfp.workingmemory.utils.dialog.setDialogBoxListener().
Member Function Documentation
newToDoItem()
void com.gtfp.workingmemory.edit.appCRUD.newToDoItem ()
Definition at line 37 of file appCRUD.java.
References com.gtfp.workingmemory.edit.appCRUD.edit().
Referenced by com.gtfp.workingmemory.app.appView.onCreate().
edit()
void com.gtfp.workingmemory.edit.appCRUD.edit (int position)
Definition at line 43 of file appCRUD.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.getItem(), com.gtfp.workingmemory.app.appView.mController, com.gtfp.workingmemory.app.appView.mToDoListAdapter, com.gtfp.workingmemory.todo.ToDoItem.setListPosn(), and com.gtfp.workingmemory.app.appView.syncData().
Referenced by com.gtfp.workingmemory.app.appView.editAlarm(), com.gtfp.workingmemory.edit.appCRUD.newToDoItem(), com.gtfp.workingmemory.app.appView.onContextItemSelected(), and com.gtfp.workingmemory.app.appView.onCreate().
delete()
boolean com.gtfp.workingmemory.edit.appCRUD.delete (long id)
Definition at line 167 of file appCRUD.java.
References com.gtfp.workingmemory.app.appModel.delete(), com.gtfp.workingmemory.app.appView.mAlarmManager, and com.gtfp.workingmemory.app.appView.mAppModel.
Referenced by com.gtfp.workingmemory.app.appView.delete().
dialogResult()
void com.gtfp.workingmemory.edit.appCRUD.dialogResult (boolean result)
Implements com.gtfp.workingmemory.utils.dialog.DialogBoxListener.
Definition at line 181 of file appCRUD.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.getItem(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.app.appView.mToDoListAdapter, and com.gtfp.workingmemory.edit.appCRUD.mToDoListID.
onDestroy()
void com.gtfp.workingmemory.edit.appCRUD.onDestroy ()
Definition at line 201 of file appCRUD.java.
References com.gtfp.workingmemory.utils.dialog.onDestroy().
Referenced by com.gtfp.workingmemory.app.appView.onDestroy().
Member Data Documentation
mAppView
appView com.gtfp.workingmemory.edit.appCRUD.mAppView private
Definition at line 17 of file appCRUD.java.
mEditIntent
Intent com.gtfp.workingmemory.edit.appCRUD.mEditIntent private
Definition at line 19 of file appCRUD.java.
mDialogue
dialog com.gtfp.workingmemory.edit.appCRUD.mDialogue private
Definition at line 21 of file appCRUD.java.
mTrulyDelete
boolean com.gtfp.workingmemory.edit.appCRUD.mTrulyDelete = false private
Definition at line 23 of file appCRUD.java.
mToDoListID
int com.gtfp.workingmemory.edit.appCRUD.mToDoListID private
Definition at line 25 of file appCRUD.java.
Referenced by com.gtfp.workingmemory.edit.appCRUD.dialogResult().