Working Memory: com.gtfp.workingmemory.settings.appSettings Class Reference
com.gtfp.workingmemory.settings.appSettings Class Reference
Created by Drawn on 2015-03-13.
Classes
class appPreferences
Public Member Functions
appSettings (appView app)
void onSharedPreferenceChanged (SharedPreferences sharedPreferences, String key)
void onDestroy ()
Static Public Member Functions
static SharedPreferences get (Context context)
static SharedPreferences get ()
static String getString (String key, String defaultValue)
static String getResourceString (int key, String defaultValue)
static int getInt (String key, int defaultValue)
static boolean getBoolean (String key, boolean defaultValue)
static boolean withPermission (@NonNull String permission)
static String get (String key, String defaultValue)
static void set (String key, String value)
static void set (String key, boolean value)
static String getResource (int key, String defaultValue)
static int get (String key, int defaultValue)
static void set (String key, int value)
static boolean get (String key, boolean defaultValue)
Static Public Attributes
static final int REQUEST_PERMISSION_CODE = 0x11
Static Package Functions
static SharedPreferences.Editor getEditor ()
static Preference findPreference (CharSequence key)
static long getLong (String key, long defaultValue)
static float getFloat (String key, float defaultValue)
static long get (String key, long defaultValue)
static float get (String key, float defaultValue)
Static Private Attributes
static final String TODOITEM = "item"
static final String PACKAGE_NAME = "com.gtfp.workingmemory"
static SharedPreferences mSettings
static appView mApp
static Resources mResources
Detailed Description
Created by Drawn on 2015-03-13.
Definition at line 40 of file appSettings.java.
Constructor & Destructor Documentation
appSettings()
com.gtfp.workingmemory.settings.appSettings.appSettings (appView app)
Definition at line 57 of file appSettings.java.
References com.gtfp.workingmemory.app.appView.getActivity().
Member Function Documentation
get() [1/7]
static SharedPreferences com.gtfp.workingmemory.settings.appSettings.get (Context context) static
Definition at line 69 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.mSettings.
Referenced by com.gtfp.workingmemory.db.dbCloud.onLogin.addAuthStateListener(), com.gtfp.workingmemory.edit.editToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.db.dbCloud.onLogin.onAuthStateChanged(), and com.gtfp.workingmemory.app.appController.onCreate().
get() [2/7]
static SharedPreferences com.gtfp.workingmemory.settings.appSettings.get () static
Definition at line 87 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.mSettings.
getEditor()
static SharedPreferences.Editor com.gtfp.workingmemory.settings.appSettings.getEditor () static package
Definition at line 94 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.set().
findPreference()
static Preference com.gtfp.workingmemory.settings.appSettings.findPreference (CharSequence key) static package
Definition at line 101 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.mPreferenceManager.
getString()
static String com.gtfp.workingmemory.settings.appSettings.getString (String key, String defaultValue) static
Definition at line 112 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.RingtonePreference.getPersistedString(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getResourceString()
static String com.gtfp.workingmemory.settings.appSettings.getResourceString (int key, String defaultValue) static
Definition at line 127 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.hidePreferences().
getInt()
static int com.gtfp.workingmemory.settings.appSettings.getInt (String key, int defaultValue) static
Definition at line 149 of file appSettings.java.
Referenced by com.gtfp.workingmemory.colorPicker.colorPickerActivity.getLEDRates().
getLong()
static long com.gtfp.workingmemory.settings.appSettings.getLong (String key, long defaultValue) static package
Definition at line 163 of file appSettings.java.
getFloat()
static float com.gtfp.workingmemory.settings.appSettings.getFloat (String key, float defaultValue) static package
Definition at line 177 of file appSettings.java.
getBoolean()
static boolean com.gtfp.workingmemory.settings.appSettings.getBoolean (String key, boolean defaultValue) static
Definition at line 191 of file appSettings.java.
Referenced by com.gtfp.workingmemory.app.appView.appView(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate(), com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged(), com.gtfp.workingmemory.utils.dialog.Dialogue.onShow(), com.gtfp.workingmemory.app.appView.save(), com.gtfp.workingmemory.app.appView.showDialogue(), and com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate().
withPermission()
static boolean com.gtfp.workingmemory.settings.appSettings.withPermission (@NonNull String permission) static
Definition at line 205 of file appSettings.java.
References com.gtfp.workingmemory.app.appView.getActivity().
Referenced by com.gtfp.workingmemory.app.appView.createDataFile().
get() [3/7]
static String com.gtfp.workingmemory.settings.appSettings.get (String key, String defaultValue) static
Definition at line 227 of file appSettings.java.
set() [1/3]
static void com.gtfp.workingmemory.settings.appSettings.set (String key, String value) static
Definition at line 241 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.getEditor().
Referenced by com.gtfp.workingmemory.db.dbCloud.onLogin.onAuthStateChanged().
set() [2/3]
static void com.gtfp.workingmemory.settings.appSettings.set (String key, boolean value) static
Definition at line 248 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.getEditor().
getResource()
static String com.gtfp.workingmemory.settings.appSettings.getResource (int key, String defaultValue) static
Definition at line 257 of file appSettings.java.
get() [4/7]
static int com.gtfp.workingmemory.settings.appSettings.get (String key, int defaultValue) static
Definition at line 277 of file appSettings.java.
set() [3/3]
static void com.gtfp.workingmemory.settings.appSettings.set (String key, int value) static
Definition at line 291 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.getEditor().
get() [5/7]
static long com.gtfp.workingmemory.settings.appSettings.get (String key, long defaultValue) static package
Definition at line 298 of file appSettings.java.
get() [6/7]
static float com.gtfp.workingmemory.settings.appSettings.get (String key, float defaultValue) static package
Definition at line 312 of file appSettings.java.
get() [7/7]
static boolean com.gtfp.workingmemory.settings.appSettings.get (String key, boolean defaultValue) static
Definition at line 326 of file appSettings.java.
onSharedPreferenceChanged()
void com.gtfp.workingmemory.settings.appSettings.onSharedPreferenceChanged (SharedPreferences sharedPreferences, String key)
Definition at line 342 of file appSettings.java.
References com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged().
onDestroy()
void com.gtfp.workingmemory.settings.appSettings.onDestroy ()
Definition at line 360 of file appSettings.java.
Referenced by com.gtfp.workingmemory.app.appView.onDestroy().
Member Data Documentation
REQUEST_PERMISSION_CODE
final int com.gtfp.workingmemory.settings.appSettings.REQUEST_PERMISSION_CODE = 0x11 static
Definition at line 42 of file appSettings.java.
TODOITEM
final String com.gtfp.workingmemory.settings.appSettings.TODOITEM = "item" static private
Definition at line 44 of file appSettings.java.
PACKAGE_NAME
final String com.gtfp.workingmemory.settings.appSettings.PACKAGE_NAME = "com.gtfp.workingmemory" static private
Definition at line 47 of file appSettings.java.
mSettings
SharedPreferences com.gtfp.workingmemory.settings.appSettings.mSettings static private
Definition at line 49 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.get().
mApp
appView com.gtfp.workingmemory.settings.appSettings.mApp static private
Definition at line 51 of file appSettings.java.
mResources
Resources com.gtfp.workingmemory.settings.appSettings.mResources static private
Definition at line 53 of file appSettings.java.