Working Memory: com.gtfp.workingmemory.db.dbCloud Class Reference
com.gtfp.workingmemory.db.dbCloud Class Reference
Created by Drawn on 3/4/2017.
Classes
interface afterValueEventListener
class asyncData
class DataSync
class dbLocal
class onLogin
interface onLoginListener
Static Public Member Functions
static void onCreate (appController app)
static void onStart ()
static void onStop ()
static boolean save (long recId, String key)
static boolean insertNew (ContentValues recValues, long recId)
static boolean insert (String key, String action)
static boolean delete (long recId, String key)
static boolean update (ContentValues recValues, long recId)
static ArrayList< HashMap< String, String > > getDataArrayList (Cursor rec)
static Cursor getRecs ()
static boolean sync (dbInterface dbLocal, dbInterface dbCloud, appModel model)
static void addOnLoginListener (onLoginListener listener)
static void removeOnLoginListener (onLoginListener listener)
static void reSave (dbInterface dbLocal)
static boolean resync ()
static void setDeviceDirectory ()
static void onDestroy ()
Private Member Functions
dbCloud (appController app)
Static Private Member Functions
static String getAction (long recId)
static ContentValues getRec (String key)
static boolean open ()
static void recreate ()
static HashMap< String, String > getCloudItem (String key, ArrayList< HashMap< String, String >> list)
static HashMap< String, String > getRecItem (String key, ArrayList< HashMap< String, String >> list)
Private Attributes
appModel mAppModel
Static Private Attributes
static String mDBName
static SQLiteHelper mDBHelper
static dbCloud mThis
Detailed Description
Created by Drawn on 3/4/2017.
Definition at line 36 of file dbCloud.java.
Constructor & Destructor Documentation
dbCloud()
com.gtfp.workingmemory.db.dbCloud.dbCloud (appController app) private
Definition at line 47 of file dbCloud.java.
References com.gtfp.workingmemory.app.appController.getModel().
Referenced by com.gtfp.workingmemory.db.dbCloud.onCreate().
Member Function Documentation
onCreate()
static void com.gtfp.workingmemory.db.dbCloud.onCreate (appController app) static
Definition at line 54 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.dbCloud(), and com.gtfp.workingmemory.db.dbCloud.DataSync.onCreate().
Referenced by com.gtfp.workingmemory.app.appController.onCreate().
onStart()
static void com.gtfp.workingmemory.db.dbCloud.onStart () static
Definition at line 74 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.onLogin.addAuthStateListener().
Referenced by com.gtfp.workingmemory.app.appController.onStart().
onStop()
static void com.gtfp.workingmemory.db.dbCloud.onStop () static
Definition at line 81 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.onLogin.removeAuthStateListener().
Referenced by com.gtfp.workingmemory.app.appController.onStop().
save()
static boolean com.gtfp.workingmemory.db.dbCloud.save (long recId, String key) static
Definition at line 88 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.getAction(), com.gtfp.workingmemory.db.dbCloud.insertNew(), com.gtfp.workingmemory.db.dbCloud.open(), and com.gtfp.workingmemory.db.dbCloud.update().
Referenced by com.gtfp.workingmemory.db.dbCloud.dbLocal.add(), com.gtfp.workingmemory.app.appModel.save(), com.gtfp.workingmemory.db.dbCloud.dbLocal.save(), and com.gtfp.workingmemory.db.dbCloud.dbLocal.update().
insertNew()
static boolean com.gtfp.workingmemory.db.dbCloud.insertNew (ContentValues recValues, long recId) static
Definition at line 120 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getRowID(), com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.insert(), and com.gtfp.workingmemory.db.dbCloud.insert().
Referenced by com.gtfp.workingmemory.db.dbCloud.save().
insert()
static boolean com.gtfp.workingmemory.db.dbCloud.insert (String key, String action) static
Definition at line 141 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.DataSync.insert().
Referenced by com.gtfp.workingmemory.app.appModel.delete(), com.gtfp.workingmemory.db.dbCloud.DataSync.insert(), com.gtfp.workingmemory.db.dbCloud.insertNew(), com.gtfp.workingmemory.app.appModel.save(), and com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
delete()
static boolean com.gtfp.workingmemory.db.dbCloud.delete (long recId, String key) static
Definition at line 148 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.open(), and com.gtfp.workingmemory.db.dbCloud.update().
Referenced by com.gtfp.workingmemory.app.appModel.delete().
update()
static boolean com.gtfp.workingmemory.db.dbCloud.update (ContentValues recValues, long recId) static
Definition at line 173 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.getRowID(), com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.insert(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.update().
Referenced by com.gtfp.workingmemory.db.dbCloud.delete(), and com.gtfp.workingmemory.db.dbCloud.save().
getAction()
static String com.gtfp.workingmemory.db.dbCloud.getAction (long recId) static private
Definition at line 192 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery().
Referenced by com.gtfp.workingmemory.db.dbCloud.save().
getRec()
static ContentValues com.gtfp.workingmemory.db.dbCloud.getRec (String key) static private
Definition at line 218 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery().
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
open()
static boolean com.gtfp.workingmemory.db.dbCloud.open () static private
Definition at line 280 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.isOpen(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.open().
Referenced by com.gtfp.workingmemory.db.dbCloud.delete(), and com.gtfp.workingmemory.db.dbCloud.save().
getDataArrayList()
static ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbCloud.getDataArrayList (Cursor rec) static
Definition at line 308 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave(), com.gtfp.workingmemory.db.dbCloud.resync(), and com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
getRecs()
static Cursor com.gtfp.workingmemory.db.dbCloud.getRecs () static
Definition at line 349 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.runQuery().
Referenced by com.gtfp.workingmemory.db.dbCloud.asyncData.doInBackground(), com.gtfp.workingmemory.db.dbCloud.resync(), and com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud().
recreate()
static void com.gtfp.workingmemory.db.dbCloud.recreate () static private
Definition at line 356 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.drop(), and com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.setOnConfigureListener().
sync()
static boolean com.gtfp.workingmemory.db.dbCloud.sync (dbInterface dbLocal, dbInterface dbCloud, appModel model) static
Definition at line 373 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.DataSync.sync().
Referenced by com.gtfp.workingmemory.db.dbCloud.asyncData.doInBackground(), and com.gtfp.workingmemory.app.appModel.sync().
getCloudItem()
static HashMap<String, String> com.gtfp.workingmemory.db.dbCloud.getCloudItem (String key, ArrayList< HashMap< String, String >> list) static private
Definition at line 382 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
getRecItem()
static HashMap<String, String> com.gtfp.workingmemory.db.dbCloud.getRecItem (String key, ArrayList< HashMap< String, String >> list) static private
Definition at line 404 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.DataSync.syncData().
addOnLoginListener()
static void com.gtfp.workingmemory.db.dbCloud.addOnLoginListener (onLoginListener listener) static
Definition at line 424 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.onLogin.addOnLoginListener().
Referenced by com.gtfp.workingmemory.app.appModel.appModel().
removeOnLoginListener()
static void com.gtfp.workingmemory.db.dbCloud.removeOnLoginListener (onLoginListener listener) static
Definition at line 431 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.onLogin.removeOnLoginListener().
reSave()
static void com.gtfp.workingmemory.db.dbCloud.reSave (dbInterface dbLocal) static
Definition at line 438 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbInterface.getCurrentRecs(), com.gtfp.workingmemory.db.dbCloud.getDataArrayList(), com.gtfp.workingmemory.Auth.Auth.getPrevUid(), com.gtfp.workingmemory.db.dbCloud.mAppModel, com.gtfp.workingmemory.db.dbFireBase.prevUserIdDBRef(), com.gtfp.workingmemory.app.appModel.save(), com.gtfp.workingmemory.db.dbCloud.DataSync.syncRef(), and com.gtfp.workingmemory.db.dbCloud.dbLocal.toToDoItem().
Referenced by com.gtfp.workingmemory.app.appModel.onLogin().
resync()
static boolean com.gtfp.workingmemory.db.dbCloud.resync () static
Definition at line 501 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.getDataArrayList(), com.gtfp.workingmemory.db.dbCloud.getRecs(), and com.gtfp.workingmemory.db.dbCloud.DataSync.insert().
setDeviceDirectory()
static void com.gtfp.workingmemory.db.dbCloud.setDeviceDirectory () static
Definition at line 518 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.DataSync.deviceDirectory().
Referenced by com.gtfp.workingmemory.app.appModel.onDBSetup.onCreate().
onDestroy()
static void com.gtfp.workingmemory.db.dbCloud.onDestroy () static
Definition at line 526 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.close(), com.gtfp.workingmemory.db.dbCloud.DataSync.onDestroy(), and com.gtfp.workingmemory.db.dbCloud.onLogin.onDestroy().
Referenced by com.gtfp.workingmemory.app.appController.onDestroy().
Member Data Documentation
mDBName
String com.gtfp.workingmemory.db.dbCloud.mDBName static private
Definition at line 38 of file dbCloud.java.
mDBHelper
SQLiteHelper com.gtfp.workingmemory.db.dbCloud.mDBHelper static private
Definition at line 40 of file dbCloud.java.
mAppModel
appModel com.gtfp.workingmemory.db.dbCloud.mAppModel private
Definition at line 42 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave().
mThis
dbCloud com.gtfp.workingmemory.db.dbCloud.mThis static private
Definition at line 44 of file dbCloud.java.