Working Memory: com.gtfp.workingmemory.settings.appSettings.appPreferences Class Reference
com.gtfp.workingmemory.settings.appSettings.appPreferences Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
void onActivityCreated (Bundle savedInstanceState)
void onSharedPreferenceChanged (SharedPreferences sharedPreferences, String key)
boolean onPreferenceClick (Preference preference)
boolean onPreferenceChange (Preference preference, Object newValue)
void onActivityResult (int requestCode, int resultCode, Intent data)
void dialogResult (boolean result)
void onRequestPermissionsResult (int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
boolean onPreferenceTreeClick (PreferenceScreen preferenceScreen, Preference preference)
void onPause ()
void onDestroy ()
Static Public Member Functions
static void initializeActionBar (PreferenceScreen parentScreen, PreferenceScreen preferenceScreen)
Sets up the action bar for an PreferenceScreen.
static Preference openPreference (String prefKey)
Package Functions
void setupToDoItemPreferences (CharSequence key, Object itemValue)
void hidePreferences ()
void setMinutesSummary ()
boolean setItemPreferences (Intent intent, Preference preference, Object newValue)
Static Package Functions
static Preference findPreference (PreferenceGroup group, String key)
Package Attributes
Preference mLEDPreference
Preference mSoundPreference
ListPreference mMinsPreference
Preference mPreferenceClicked
Static Package Attributes
static PreferenceManager mPreferenceManager
static PreferenceScreen mPreferenceScreen
static int mPosition
Private Member Functions
void LEDSettingsResult (Intent data)
ToDoItem getItemToDo (Intent data)
Static Private Member Functions
static Preference PreferenceFind (PreferenceGroup group, String key)
Private Attributes
int mREQUEST_CODE
CharSequence mSummary
dialog mDialogue
Intent mIntent
ToDoItem mItemToDo
Detailed Description
Definition at line 369 of file appSettings.java.
Member Function Documentation
initializeActionBar()
static void com.gtfp.workingmemory.settings.appSettings.appPreferences.initializeActionBar (PreferenceScreen parentScreen, PreferenceScreen preferenceScreen) static
Sets up the action bar for an PreferenceScreen.
Definition at line 402 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceTreeClick().
openPreference()
static Preference com.gtfp.workingmemory.settings.appSettings.appPreferences.openPreference (String prefKey) static
Definition at line 469 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.SettingsActivity.onPostCreate().
findPreference()
static Preference com.gtfp.workingmemory.settings.appSettings.appPreferences.findPreference (PreferenceGroup group, String key) static package
Definition at line 539 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.PreferenceFind().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.hidePreferences(), com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.setupToDoItemPreferences().
PreferenceFind()
static Preference com.gtfp.workingmemory.settings.appSettings.appPreferences.PreferenceFind (PreferenceGroup group, String key) static private
Definition at line 548 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.findPreference().
onCreate()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate (Bundle savedInstanceState)
Definition at line 585 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.findPreference(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmUri(), com.gtfp.workingmemory.settings.appSettings.getBoolean(), com.gtfp.workingmemory.settings.appSettings.getString(), com.gtfp.workingmemory.settings.appSettings.appPreferences.hidePreferences(), com.gtfp.workingmemory.utils.dialog.setDialogBoxListener(), com.gtfp.workingmemory.settings.appSettings.appPreferences.setMinutesSummary(), com.gtfp.workingmemory.settings.appSettings.appPreferences.setupToDoItemPreferences(), com.gtfp.workingmemory.todo.ToDoItem.showDialogue(), com.gtfp.workingmemory.todo.ToDoItem.Sound(), com.gtfp.workingmemory.todo.ToDoItem.useLED(), and com.gtfp.workingmemory.todo.ToDoItem.useVibrate().
onActivityCreated()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onActivityCreated (Bundle savedInstanceState)
Definition at line 678 of file appSettings.java.
setupToDoItemPreferences()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.setupToDoItemPreferences (CharSequence key, Object itemValue) package
Definition at line 688 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.findPreference().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
hidePreferences()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.hidePreferences () package
Definition at line 715 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.findPreference(), com.gtfp.workingmemory.utils.Devices.getDeviceName(), and com.gtfp.workingmemory.settings.appSettings.getResourceString().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
onSharedPreferenceChanged()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onSharedPreferenceChanged (SharedPreferences sharedPreferences, String key)
Definition at line 743 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.setMinutesSummary().
setMinutesSummary()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.setMinutesSummary () package
Definition at line 754 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onSharedPreferenceChanged().
onPreferenceClick()
boolean com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick (Preference preference)
Definition at line 766 of file appSettings.java.
References com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.getLEDOn(), com.gtfp.workingmemory.app.appView.onPreferenceClick(), com.gtfp.workingmemory.colorPicker.colorPickerView.setColor(), and com.gtfp.workingmemory.utils.dialog.show().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.dialogResult().
onPreferenceChange()
boolean com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceChange (Preference preference, Object newValue)
Definition at line 910 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences().
setItemPreferences()
boolean com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences (Intent intent, Preference preference, Object newValue) package
Definition at line 929 of file appSettings.java.
References com.gtfp.workingmemory.todo.ToDoItem.getKey(), com.gtfp.workingmemory.todo.ToDoItem.setClearNotification(), com.gtfp.workingmemory.todo.ToDoItem.setShowDialogue(), com.gtfp.workingmemory.todo.ToDoItem.setSound(), com.gtfp.workingmemory.todo.ToDoItem.settingsChanged(), com.gtfp.workingmemory.todo.ToDoItem.setUseLED(), and com.gtfp.workingmemory.todo.ToDoItem.setUseVibrate().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceChange().
onActivityResult()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onActivityResult (int requestCode, int resultCode, Intent data)
Definition at line 978 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.LEDSettingsResult().
LEDSettingsResult()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.LEDSettingsResult (Intent data) private
Definition at line 997 of file appSettings.java.
References com.gtfp.workingmemory.todo.ToDoItem.setLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.setLEDOff(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDOn().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onActivityResult().
getItemToDo()
ToDoItem com.gtfp.workingmemory.settings.appSettings.appPreferences.getItemToDo (Intent data) private
Definition at line 1074 of file appSettings.java.
dialogResult()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.dialogResult (boolean result)
Implements com.gtfp.workingmemory.utils.dialog.DialogBoxListener.
Definition at line 1088 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick().
onRequestPermissionsResult()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onRequestPermissionsResult (int requestCode, @NonNull String [] permissions, @NonNull int [] grantResults)
Definition at line 1102 of file appSettings.java.
onCreateView()
View com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 1124 of file appSettings.java.
onPreferenceTreeClick()
boolean com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceTreeClick (PreferenceScreen preferenceScreen, Preference preference)
Definition at line 1133 of file appSettings.java.
References com.gtfp.workingmemory.settings.appSettings.appPreferences.initializeActionBar().
onPause()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onPause ()
Definition at line 1175 of file appSettings.java.
onDestroy()
void com.gtfp.workingmemory.settings.appSettings.appPreferences.onDestroy ()
Definition at line 1183 of file appSettings.java.
References com.gtfp.workingmemory.utils.dialog.onDestroy().
Member Data Documentation
mPreferenceManager
PreferenceManager com.gtfp.workingmemory.settings.appSettings.appPreferences.mPreferenceManager static package
Definition at line 377 of file appSettings.java.
Referenced by com.gtfp.workingmemory.settings.appSettings.findPreference().
mPreferenceScreen
PreferenceScreen com.gtfp.workingmemory.settings.appSettings.appPreferences.mPreferenceScreen static package
Definition at line 379 of file appSettings.java.
mPosition
int com.gtfp.workingmemory.settings.appSettings.appPreferences.mPosition static package
Definition at line 381 of file appSettings.java.
mLEDPreference
Preference com.gtfp.workingmemory.settings.appSettings.appPreferences.mLEDPreference package
Definition at line 383 of file appSettings.java.
mSoundPreference
Preference com.gtfp.workingmemory.settings.appSettings.appPreferences.mSoundPreference package
Definition at line 383 of file appSettings.java.
mMinsPreference
ListPreference com.gtfp.workingmemory.settings.appSettings.appPreferences.mMinsPreference package
Definition at line 385 of file appSettings.java.
mPreferenceClicked
Preference com.gtfp.workingmemory.settings.appSettings.appPreferences.mPreferenceClicked package
Definition at line 387 of file appSettings.java.
mREQUEST_CODE
int com.gtfp.workingmemory.settings.appSettings.appPreferences.mREQUEST_CODE private
Definition at line 389 of file appSettings.java.
mSummary
CharSequence com.gtfp.workingmemory.settings.appSettings.appPreferences.mSummary private
Definition at line 391 of file appSettings.java.
mDialogue
dialog com.gtfp.workingmemory.settings.appSettings.appPreferences.mDialogue private
Definition at line 393 of file appSettings.java.
mIntent
Intent com.gtfp.workingmemory.settings.appSettings.appPreferences.mIntent private
Definition at line 395 of file appSettings.java.
mItemToDo
ToDoItem com.gtfp.workingmemory.settings.appSettings.appPreferences.mItemToDo private
Definition at line 397 of file appSettings.java.