Working Memory: com.gtfp.workingmemory.edit.RadioGroupTableLayout Class Reference
com.gtfp.workingmemory.edit.RadioGroupTableLayout Class Reference
Public Member Functions
RadioGroupTableLayout (Context context)
RadioGroupTableLayout (Context context, AttributeSet attrs)
void onClick (View v)
boolean check (int id)
void enableButtons ()
void setCheckedStateForView (int radioId, boolean checked)
void addView (View child, int index, android.view.ViewGroup.LayoutParams params)
void addView (View child, android.view.ViewGroup.LayoutParams params)
int getCheckedRadioButtonId ()
int getStep ()
Private Member Functions
void initTime (Context context)
void stepTime (Calendar original, int increment)
void setChecked (RadioButton rb)
void setChildrenOnClickListener (TableRow tr)
ArrayList< RadioButton > getRadioButtons ()
Private Attributes
RadioButton mActiveButton
final int mCheckedId = -1
boolean mProtectFromCheckedChange = false
editToDoItem mEditItem
final ArrayList< RadioButton > radioButtons = new ArrayList<RadioButton>()
final Calendar mToday = Calendar.getInstance()
Static Private Attributes
static final String TAG = RadioGroupTableLayout.class.getSimpleName()
static Calendar mTmpCal
Detailed Description
Definition at line 17 of file RadioGroupTableLayout.java.
Constructor & Destructor Documentation
RadioGroupTableLayout() [1/2]
com.gtfp.workingmemory.edit.RadioGroupTableLayout.RadioGroupTableLayout (Context context)
Parameters
context What is this?
Definition at line 40 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.initTime().
RadioGroupTableLayout() [2/2]
com.gtfp.workingmemory.edit.RadioGroupTableLayout.RadioGroupTableLayout (Context context, AttributeSet attrs)
Parameters
context
attrs
Definition at line 51 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.initTime().
Member Function Documentation
onClick()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick (View v)
Definition at line 58 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.todo.ToDoItem.displayDueDate(), com.gtfp.workingmemory.todo.ToDoItem.displayTime(), com.gtfp.workingmemory.edit.editToDoItem.editDueDate, com.gtfp.workingmemory.edit.RadioGroupTableLayout.enableButtons(), com.gtfp.workingmemory.edit.editToDoItem.mCanSnooze, com.gtfp.workingmemory.edit.editToDoItem.mDateTime, com.gtfp.workingmemory.edit.editToDoItem.mOldDate, com.gtfp.workingmemory.edit.editToDoItem.mTP, com.gtfp.workingmemory.edit.RadioGroupTableLayout.setChecked(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.stepTime(), and com.gtfp.workingmemory.edit.editToDoItem.testPastDue().
initTime()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.initTime (Context context) private
Definition at line 91 of file RadioGroupTableLayout.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.RadioGroupTableLayout().
stepTime()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.stepTime (Calendar original, int increment) private
Definition at line 97 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime().
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick().
check()
boolean com.gtfp.workingmemory.edit.RadioGroupTableLayout.check (int id)
Definition at line 121 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.setCheckedStateForView().
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate().
enableButtons()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.enableButtons ()
Definition at line 146 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.getRadioButtons(), and com.gtfp.workingmemory.edit.editToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
setCheckedStateForView()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.setCheckedStateForView (int radioId, boolean checked)
Definition at line 167 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.setChecked().
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.check(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
setChecked()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.setChecked (RadioButton rb) private
Definition at line 189 of file RadioGroupTableLayout.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), and com.gtfp.workingmemory.edit.RadioGroupTableLayout.setCheckedStateForView().
addView() [1/2]
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.addView (View child, int index, android.view.ViewGroup.LayoutParams params)
Definition at line 212 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.setChildrenOnClickListener().
addView() [2/2]
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.addView (View child, android.view.ViewGroup.LayoutParams params)
Definition at line 223 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.setChildrenOnClickListener().
setChildrenOnClickListener()
void com.gtfp.workingmemory.edit.RadioGroupTableLayout.setChildrenOnClickListener (TableRow tr) private
Definition at line 230 of file RadioGroupTableLayout.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.addView().
getRadioButtons()
ArrayList<RadioButton> com.gtfp.workingmemory.edit.RadioGroupTableLayout.getRadioButtons () private
Definition at line 248 of file RadioGroupTableLayout.java.
References com.gtfp.workingmemory.edit.RadioGroupTableLayout.radioButtons.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.enableButtons().
getCheckedRadioButtonId()
int com.gtfp.workingmemory.edit.RadioGroupTableLayout.getCheckedRadioButtonId ()
Definition at line 254 of file RadioGroupTableLayout.java.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getStep()
int com.gtfp.workingmemory.edit.RadioGroupTableLayout.getStep ()
Definition at line 265 of file RadioGroupTableLayout.java.
Member Data Documentation
TAG
final String com.gtfp.workingmemory.edit.RadioGroupTableLayout.TAG = RadioGroupTableLayout.class.getSimpleName() static private
Definition at line 19 of file RadioGroupTableLayout.java.
mActiveButton
RadioButton com.gtfp.workingmemory.edit.RadioGroupTableLayout.mActiveButton private
Definition at line 21 of file RadioGroupTableLayout.java.
mCheckedId
final int com.gtfp.workingmemory.edit.RadioGroupTableLayout.mCheckedId = -1 private
Definition at line 24 of file RadioGroupTableLayout.java.
mProtectFromCheckedChange
boolean com.gtfp.workingmemory.edit.RadioGroupTableLayout.mProtectFromCheckedChange = false private
Definition at line 27 of file RadioGroupTableLayout.java.
mEditItem
editToDoItem com.gtfp.workingmemory.edit.RadioGroupTableLayout.mEditItem private
Definition at line 29 of file RadioGroupTableLayout.java.
radioButtons
final ArrayList<RadioButton> com.gtfp.workingmemory.edit.RadioGroupTableLayout.radioButtons = new ArrayList<RadioButton>() private
Definition at line 31 of file RadioGroupTableLayout.java.
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.getRadioButtons().
mTmpCal
Calendar com.gtfp.workingmemory.edit.RadioGroupTableLayout.mTmpCal static private
Definition at line 33 of file RadioGroupTableLayout.java.
mToday
final Calendar com.gtfp.workingmemory.edit.RadioGroupTableLayout.mToday = Calendar.getInstance() private
Definition at line 35 of file RadioGroupTableLayout.java.