Working Memory: com.gtfp.workingmemory.db.dbCloud.DataSync Class Reference
com.gtfp.workingmemory.db.dbCloud.DataSync Class Reference
Static Public Member Functions
static boolean insert (final String key, final String action)
Static Package Functions
static void onCreate (appController app)
static DatabaseReference syncRef (String userId)
static DatabaseReference getDevRef (String userId)
static void sync (final dbInterface dbLocal, final dbInterface dbCloud, final appModel AppModel)
static void deviceDirectory (final long timestamp)
static String insert (ContentValues recValues)
static String insert (DatabaseReference DBRef, ContentValues recValues)
static void replace (String key, final afterValueEventListener listener)
static HashMap< String, Object > toMap (ContentValues recValues)
static ArrayList< HashMap< String, String > > recArrayList (DataSnapshot snapshot)
static boolean isOnline ()
static void onDestroy ()
Static Package Attributes
static DatabaseReference mDevRef
Static Private Member Functions
static void syncData (DataSnapshot snapshot, dbInterface dbLocal, dbInterface dbCloud)
static void updateCloud (dbInterface dbLocal, dbInterface dbCloud)
Update the FireBase database now that there is online access.
Static Private Attributes
static String mInstallNum
static FirebaseDatabase mDatabase
static appModel mAppModel
Detailed Description
Definition at line 678 of file dbCloud.java.
Member Function Documentation
onCreate()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.onCreate (appController app) static package
Definition at line 690 of file dbCloud.java.
References com.gtfp.workingmemory.app.appController.getInstallNum(), and com.gtfp.workingmemory.app.appController.getModel().
Referenced by com.gtfp.workingmemory.db.dbCloud.onCreate().
syncRef()
static DatabaseReference com.gtfp.workingmemory.db.dbCloud.DataSync.syncRef (String userId) static package
Definition at line 701 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.reSave().
getDevRef()
static DatabaseReference com.gtfp.workingmemory.db.dbCloud.DataSync.getDevRef (String userId) static package
Definition at line 735 of file dbCloud.java.
sync()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.sync (final dbInterface dbLocal, final dbInterface dbCloud, final appModel AppModel) static package
Definition at line 764 of file dbCloud.java.
References com.gtfp.workingmemory.Auth.Auth.getUid(), and com.gtfp.workingmemory.db.dbCloud.asyncData.isRunning().
Referenced by com.gtfp.workingmemory.db.dbCloud.sync().
syncData()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.syncData (DataSnapshot snapshot, dbInterface dbLocal, dbInterface dbCloud) static private
Definition at line 830 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.dbLocal.add(), com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.delete(), com.gtfp.workingmemory.db.dbCloud.dbLocal.delete(), com.gtfp.workingmemory.db.dbCloud.getCloudItem(), com.gtfp.workingmemory.db.dbInterface.getDataArrayList(), com.gtfp.workingmemory.db.dbCloud.getRec(), com.gtfp.workingmemory.db.dbCloud.getRecItem(), com.gtfp.workingmemory.db.dbInterface.getRecs(), com.gtfp.workingmemory.Auth.Auth.getUid(), com.gtfp.workingmemory.app.appModel.recArrayList(), and com.gtfp.workingmemory.db.dbCloud.dbLocal.update().
Referenced by com.gtfp.workingmemory.db.dbCloud.asyncData.doInBackground().
updateCloud()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.updateCloud (dbInterface dbLocal, dbInterface dbCloud) static private
Update the FireBase database now that there is online access.
Definition at line 953 of file dbCloud.java.
References com.gtfp.workingmemory.frmwrk.db.SQLiteHelper.delete(), com.gtfp.workingmemory.db.dbCloud.getDataArrayList(), com.gtfp.workingmemory.app.appModel.getRecord(), com.gtfp.workingmemory.db.dbCloud.getRecs(), com.gtfp.workingmemory.db.dbCloud.insert(), com.gtfp.workingmemory.db.dbInterface.save(), and com.gtfp.workingmemory.db.dbInterface.ToDoList().
Referenced by com.gtfp.workingmemory.db.dbCloud.asyncData.doInBackground().
deviceDirectory()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.deviceDirectory (final long timestamp) static package
Definition at line 996 of file dbCloud.java.
References com.gtfp.workingmemory.Auth.Auth.getUid().
Referenced by com.gtfp.workingmemory.db.dbCloud.setDeviceDirectory().
insert() [1/3]
static boolean com.gtfp.workingmemory.db.dbCloud.DataSync.insert (final String key, final String action) static
Definition at line 1047 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.afterValueEventListener.afterDataChange(), and com.gtfp.workingmemory.db.dbCloud.insert().
Referenced by com.gtfp.workingmemory.db.dbCloud.insert(), and com.gtfp.workingmemory.db.dbCloud.resync().
insert() [2/3]
static String com.gtfp.workingmemory.db.dbCloud.DataSync.insert (ContentValues recValues) static package
Definition at line 1079 of file dbCloud.java.
References com.gtfp.workingmemory.Auth.Auth.getUid(), and com.gtfp.workingmemory.db.dbCloud.insert().
insert() [3/3]
static String com.gtfp.workingmemory.db.dbCloud.DataSync.insert (DatabaseReference DBRef, ContentValues recValues) static package
Definition at line 1086 of file dbCloud.java.
replace()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.replace (String key, final afterValueEventListener listener) static package
Definition at line 1118 of file dbCloud.java.
References com.gtfp.workingmemory.db.dbCloud.afterValueEventListener.afterDataChange(), and com.gtfp.workingmemory.Auth.Auth.getUid().
toMap()
static HashMap<String, Object> com.gtfp.workingmemory.db.dbCloud.DataSync.toMap (ContentValues recValues) static package
Definition at line 1157 of file dbCloud.java.
recArrayList()
static ArrayList<HashMap<String, String> > com.gtfp.workingmemory.db.dbCloud.DataSync.recArrayList (DataSnapshot snapshot) static package
Definition at line 1194 of file dbCloud.java.
isOnline()
static boolean com.gtfp.workingmemory.db.dbCloud.DataSync.isOnline () static package
Definition at line 1256 of file dbCloud.java.
References com.gtfp.workingmemory.app.appModel.getController(), and com.gtfp.workingmemory.app.appController.NoConnectivity().
onDestroy()
static void com.gtfp.workingmemory.db.dbCloud.DataSync.onDestroy () static package
Definition at line 1264 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.onDestroy().
Member Data Documentation
mDevRef
DatabaseReference com.gtfp.workingmemory.db.dbCloud.DataSync.mDevRef static package
Definition at line 680 of file dbCloud.java.
mInstallNum
String com.gtfp.workingmemory.db.dbCloud.DataSync.mInstallNum static private
Definition at line 682 of file dbCloud.java.
mDatabase
FirebaseDatabase com.gtfp.workingmemory.db.dbCloud.DataSync.mDatabase static private
Definition at line 684 of file dbCloud.java.
mAppModel
appModel com.gtfp.workingmemory.db.dbCloud.DataSync.mAppModel static private
Definition at line 686 of file dbCloud.java.