Working Memory: com.gtfp.workingmemory.todo.ToDoListAdapter Class Reference
com.gtfp.workingmemory.todo.ToDoListAdapter Class Reference
Created by Drawn on 2015-02-10.
Public Member Functions
ToDoListAdapter (List< ToDoItem > listToDos)
void setItems (List< ToDoItem > listToDos)
boolean add (ToDoItem itemToDo)
boolean save (ToDoItem itemToDo)
boolean remove (ToDoItem itemToDo)
void refresh (List< ToDoItem > listToDos)
void sort ()
int getListId (ToDoItem itemId)
void Iterate (ToDoItemsList.ToDoIterator iterateObj)
View getView (int position, View convertView, ViewGroup parent)
int getCount ()
Object getItem (int index)
long getItemId (int index)
boolean hasStableIds ()
void onDestroy ()
Package Functions
List< ToDoItem > ToDoList ()
boolean update (ToDoItem itemToDo)
Private Member Functions
boolean remove (int index)
Private Attributes
ToDoItemsList mToDoItemsList
int mModItemId = -1
int mCount = 0
Detailed Description
Created by Drawn on 2015-02-10.
Definition at line 20 of file ToDoListAdapter.java.
Constructor & Destructor Documentation
ToDoListAdapter()
com.gtfp.workingmemory.todo.ToDoListAdapter.ToDoListAdapter (List< ToDoItem > listToDos)
Definition at line 30 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.setItems(), and com.gtfp.workingmemory.todo.ToDoItemsList.size().
Member Function Documentation
setItems()
void com.gtfp.workingmemory.todo.ToDoListAdapter.setItems (List< ToDoItem > listToDos)
Definition at line 44 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.setItems(), com.gtfp.workingmemory.todo.ToDoItemsList.size(), and com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate().
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.refresh(), and com.gtfp.workingmemory.app.appView.refreshList().
ToDoList()
List<ToDoItem> com.gtfp.workingmemory.todo.ToDoListAdapter.ToDoList () package
Definition at line 53 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.ToDoList().
add()
boolean com.gtfp.workingmemory.todo.ToDoListAdapter.add (ToDoItem itemToDo)
Definition at line 59 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.add(), com.gtfp.workingmemory.todo.ToDoItemsList.size(), and com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate().
Referenced by com.gtfp.workingmemory.app.appView.save().
save()
boolean com.gtfp.workingmemory.todo.ToDoListAdapter.save (ToDoItem itemToDo)
Definition at line 78 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate(), and com.gtfp.workingmemory.todo.ToDoItemsList.update().
Referenced by com.gtfp.workingmemory.app.appView.delete(), and com.gtfp.workingmemory.app.appView.save().
update()
boolean com.gtfp.workingmemory.todo.ToDoListAdapter.update (ToDoItem itemToDo) package
Definition at line 94 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.update().
remove() [1/2]
boolean com.gtfp.workingmemory.todo.ToDoListAdapter.remove (ToDoItem itemToDo)
Definition at line 101 of file ToDoListAdapter.java.
Referenced by com.gtfp.workingmemory.app.appView.delete().
remove() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoListAdapter.remove (int index) private
Definition at line 107 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.mCount, com.gtfp.workingmemory.todo.ToDoItemsList.remove(), and com.gtfp.workingmemory.todo.ToDoItemsList.size().
refresh()
void com.gtfp.workingmemory.todo.ToDoListAdapter.refresh (List< ToDoItem > listToDos)
Definition at line 122 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.setItems().
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick(), and com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged().
sort()
void com.gtfp.workingmemory.todo.ToDoListAdapter.sort ()
Definition at line 130 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.sortByDueDate().
Referenced by com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged().
getListId()
int com.gtfp.workingmemory.todo.ToDoListAdapter.getListId (ToDoItem itemId)
Definition at line 138 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.getListId().
Referenced by com.gtfp.workingmemory.app.appView.editAlarm().
Iterate()
void com.gtfp.workingmemory.todo.ToDoListAdapter.Iterate (ToDoItemsList.ToDoIterator iterateObj)
Definition at line 144 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.iterateToDoItems(), and com.gtfp.workingmemory.todo.ToDoItemsList.setIterator().
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick().
getView()
View com.gtfp.workingmemory.todo.ToDoListAdapter.getView (int position, View convertView, ViewGroup parent)
Definition at line 156 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.edit.rowView.container, com.gtfp.workingmemory.todo.ToDoItemsList.get(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.edit.rowView.itemDueDateView, com.gtfp.workingmemory.edit.rowView.markAsDeleted(), com.gtfp.workingmemory.edit.rowView.mTextView, com.gtfp.workingmemory.edit.rowView.position, com.gtfp.workingmemory.edit.rowView.priorityImage, com.gtfp.workingmemory.edit.rowView.setFont(), and com.gtfp.workingmemory.edit.rowView.setTextOriginal().
getCount()
int com.gtfp.workingmemory.todo.ToDoListAdapter.getCount ()
Definition at line 224 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.mCount.
getItem()
Object com.gtfp.workingmemory.todo.ToDoListAdapter.getItem (int index)
Definition at line 230 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.get().
Referenced by com.gtfp.workingmemory.app.appView.delete(), com.gtfp.workingmemory.app.appView.deleteResult(), com.gtfp.workingmemory.edit.appCRUD.dialogResult(), and com.gtfp.workingmemory.edit.appCRUD.edit().
getItemId()
long com.gtfp.workingmemory.todo.ToDoListAdapter.getItemId (int index)
Definition at line 239 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.getId().
hasStableIds()
boolean com.gtfp.workingmemory.todo.ToDoListAdapter.hasStableIds ()
Definition at line 245 of file ToDoListAdapter.java.
onDestroy()
void com.gtfp.workingmemory.todo.ToDoListAdapter.onDestroy ()
Definition at line 251 of file ToDoListAdapter.java.
References com.gtfp.workingmemory.todo.ToDoItemsList.onDestroy().
Referenced by com.gtfp.workingmemory.app.appView.onDestroy().
Member Data Documentation
mToDoItemsList
ToDoItemsList com.gtfp.workingmemory.todo.ToDoListAdapter.mToDoItemsList private
Definition at line 22 of file ToDoListAdapter.java.
mModItemId
int com.gtfp.workingmemory.todo.ToDoListAdapter.mModItemId = -1 private
Definition at line 24 of file ToDoListAdapter.java.
mCount
int com.gtfp.workingmemory.todo.ToDoListAdapter.mCount = 0 private
Definition at line 27 of file ToDoListAdapter.java.
Referenced by com.gtfp.workingmemory.todo.ToDoListAdapter.getCount(), and com.gtfp.workingmemory.todo.ToDoListAdapter.remove().