Working Memory: com.gtfp.workingmemory.google.googleAPI.ApiClientTask Interface Reference
com.gtfp.workingmemory.google.googleAPI.ApiClientTask Interface Reference
Public Member Functions
String onExecute (DriveId... params)
void onPostExecute (String result)
void onCancelled (String result)
Detailed Description
Definition at line 715 of file googleAPI.java.
Member Function Documentation
onExecute()
String com.gtfp.workingmemory.google.googleAPI.ApiClientTask.onExecute (DriveId... params)
Referenced by com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.doInBackgroundConnected().
onPostExecute()
void com.gtfp.workingmemory.google.googleAPI.ApiClientTask.onPostExecute (String result)
Referenced by com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.onPostExecute().
onCancelled()
void com.gtfp.workingmemory.google.googleAPI.ApiClientTask.onCancelled (String result)
Referenced by com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.onCancelled().