Working Memory: com.gtfp.workingmemory.utils.dialog.Dialogue Class Reference
com.gtfp.workingmemory.utils.dialog.Dialogue Class Reference
Public Member Functions
void onShow (DialogInterface dialog)
void onCancel (DialogInterface dialog)
Package Functions
Dialogue (CharSequence message, int buttons)
void show ()
void switchButtons (boolean switchButtons)
void setMessage (CharSequence message)
Private Member Functions
AlertDialog buildDialog (int buttons)
void runListener (DialogInterface dialog, int id, boolean result)
void onDestroy ()
Private Attributes
AlertDialog mDialog
CharSequence mMessage = ""
Detailed Description
Definition at line 103 of file dialog.java.
Constructor & Destructor Documentation
Dialogue()
com.gtfp.workingmemory.utils.dialog.Dialogue.Dialogue (CharSequence message, int buttons) package
Definition at line 109 of file dialog.java.
Member Function Documentation
show()
void com.gtfp.workingmemory.utils.dialog.Dialogue.show () package
Definition at line 131 of file dialog.java.
Referenced by com.gtfp.workingmemory.utils.dialog.show().
onShow()
void com.gtfp.workingmemory.utils.dialog.Dialogue.onShow (DialogInterface dialog)
Definition at line 137 of file dialog.java.
References com.gtfp.workingmemory.settings.appSettings.getBoolean().
switchButtons()
void com.gtfp.workingmemory.utils.dialog.Dialogue.switchButtons (boolean switchButtons) package
Definition at line 143 of file dialog.java.
setMessage()
void com.gtfp.workingmemory.utils.dialog.Dialogue.setMessage (CharSequence message) package
Definition at line 179 of file dialog.java.
Referenced by com.gtfp.workingmemory.utils.dialog.show().
buildDialog()
AlertDialog com.gtfp.workingmemory.utils.dialog.Dialogue.buildDialog (int buttons) private
Definition at line 184 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.YESNO.
runListener()
void com.gtfp.workingmemory.utils.dialog.Dialogue.runListener (DialogInterface dialog, int id, boolean result) private
Definition at line 215 of file dialog.java.
References com.gtfp.workingmemory.utils.dialog.DialogBoxListener.dialogResult().
onCancel()
void com.gtfp.workingmemory.utils.dialog.Dialogue.onCancel (DialogInterface dialog)
Definition at line 225 of file dialog.java.
onDestroy()
void com.gtfp.workingmemory.utils.dialog.Dialogue.onDestroy () private
Definition at line 231 of file dialog.java.
Referenced by com.gtfp.workingmemory.utils.dialog.onDestroy().
Member Data Documentation
mDialog
AlertDialog com.gtfp.workingmemory.utils.dialog.Dialogue.mDialog private
Definition at line 105 of file dialog.java.
mMessage
CharSequence com.gtfp.workingmemory.utils.dialog.Dialogue.mMessage = "" private
Definition at line 107 of file dialog.java.