Working Memory: com.gtfp.workingmemory.app.appView Class Reference
com.gtfp.workingmemory.app.appView Class Reference
Classes
class signInApp
Public Member Functions
appView (appController app)
appView (Context context)
boolean save (ToDoItem itemToDo)
boolean delete (int todoListID)
void refreshList ()
boolean open ()
void close ()
void resetAlarms ()
boolean delete (long id)
void onAuthStateChanged (@NonNull FirebaseAuth firebaseAuth)
void onDataChange (DataSnapshot snapshot)
void onCancelled (DatabaseError databaseError)
void onSharedPreferenceChanged (SharedPreferences sharedPreferences, String key)
boolean onPreferenceClick (Preference preference)
void dialogResult (boolean result)
appController getController ()
Activity getActivity ()
Context getContext ()
appModel getModel ()
String getPackageName ()
void syncData ()
void restoreSync ()
boolean insertTempRec ()
boolean createEmptyTemp ()
void importRec (String columnName, String value)
ArrayList< ToDoItem > ToDoList (Cursor recs)
Cursor getNewTempRecs ()
Method getPImethod ()
Object getPI ()
String syncFile ()
void onDestroy ()
Static Public Member Functions
static boolean showDialogue ()
static boolean clearNotification ()
Public Attributes
appController mController
appModel mAppModel
ToDoListAdapter mToDoListAdapter
ToDoAlarm.Manager mAlarmManager
Wallpaper mItemsOnWallpaper
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onNewIntent (Intent intent)
void onSaveInstanceState (Bundle savedInstanceState)
void onRestoreInstanceState (Bundle savedInstanceState)
void onPause ()
void onStop ()
void onStart ()
void onRestart ()
Package Functions
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
boolean onPrepareOptionsMenu (Menu menu)
void onErrorMenu (Menu menu)
void onThrowError (Menu menu)
void onActivityResult (int requestCode, int resultCode, Intent data)
boolean saveEdit (ToDoItem itemToDo)
void onCreateContextMenu (ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo)
boolean onContextItemSelected (MenuItem item)
boolean showDeleted ()
void deleteResult (boolean result)
void listErrors ()
String syncFileName ()
void showMessage (String message)
Shows a toast message.
Package Attributes
FragmentManager mFragMngr
Context mContext
Private Member Functions
ArrayList< ToDoItem > listToDos ()
String getRowTitle (AdapterView.AdapterContextMenuInfo info)
void setAlarms (List< ToDoItem > todoList)
Calendar getThreshold ()
boolean editAlarm (Intent intent)
boolean hideActionBar ()
boolean runActivity (Class<?> cls)
boolean runFragment (Fragment newFragment, int layoutID)
boolean deleteSync ()
void syncData (String param)
String versionOfApp ()
boolean exportData ()
File getSyncFile ()
boolean createDataFile (File file)
boolean importData ()
File appDir ()
boolean isDebuggable ()
Returns true if the application is debuggable.
File exportDir ()
File exportDataFile ()
Private Attributes
final int REQUEST_CODE = 1
final int GOOGLE_REQUEST = 2
final int ERROR_REQUEST = 3
boolean mFirstCall = true
appCRUD mAppCRUD
ListView mTaskList
int mToDoListID = -1
Intent mIntent
boolean mTrulyDelete = false
boolean mSigMatch
File mSyncFile
appSettings mAppSettings
dialog mDialogue
Calendar mToday
MenuItem mMenuItem
MenuItem mErrorMenuItem
MenuItem mThrowErrorMenu
CharSequence mItemTitle
FrameLayout mFrameLayout
Static Private Attributes
static final String ALARM_ID = "id"
static final int CONTENT_VIEW_ID = View.generateViewId()
static String PACKAGE_NAME
static boolean mClearNotification
static boolean mSyncData
static boolean mRestoreSync
static boolean mDeleteSync = false
Detailed Description
Definition at line 67 of file appView.java.
Constructor & Destructor Documentation
appView() [1/2]
com.gtfp.workingmemory.app.appView.appView (appController app)
Definition at line 140 of file appView.java.
References com.gtfp.workingmemory.settings.appSettings.getBoolean().
appView() [2/2]
com.gtfp.workingmemory.app.appView.appView (Context context)
Definition at line 164 of file appView.java.
References com.gtfp.workingmemory.app.appView.mAlarmManager, com.gtfp.workingmemory.utils.dialog.setDialogBoxListener(), com.gtfp.workingmemory.app.App.setLabel(), com.gtfp.workingmemory.app.App.setModel(), and com.gtfp.workingmemory.app.App.setView().
Member Function Documentation
showDialogue()
static boolean com.gtfp.workingmemory.app.appView.showDialogue () static
Definition at line 189 of file appView.java.
References com.gtfp.workingmemory.settings.appSettings.getBoolean().
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm().
clearNotification()
static boolean com.gtfp.workingmemory.app.appView.clearNotification () static
Definition at line 195 of file appView.java.
References com.gtfp.workingmemory.app.appView.mClearNotification.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm().
onCreate()
void com.gtfp.workingmemory.app.appView.onCreate (Bundle savedInstanceState) protected
Definition at line 201 of file appView.java.
References com.gtfp.workingmemory.edit.appCRUD.edit(), com.gtfp.workingmemory.app.appView.editAlarm(), and com.gtfp.workingmemory.edit.appCRUD.newToDoItem().
Referenced by com.gtfp.workingmemory.app.appController.onCreate().
onCreateOptionsMenu()
boolean com.gtfp.workingmemory.app.appView.onCreateOptionsMenu (Menu menu) package
Definition at line 250 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appController.onCreateOptionsMenu().
onOptionsItemSelected()
boolean com.gtfp.workingmemory.app.appView.onOptionsItemSelected (MenuItem item) package
Definition at line 263 of file appView.java.
References com.gtfp.workingmemory.Auth.Auth.addAuthStateListener(), com.gtfp.workingmemory.app.appView.runActivity(), com.gtfp.workingmemory.app.appView.runFragment(), com.gtfp.workingmemory.utils.dialog.showBox(), com.gtfp.workingmemory.Auth.Auth.signOut(), com.gtfp.workingmemory.app.appView.syncData(), and com.gtfp.workingmemory.app.appView.versionOfApp().
Referenced by com.gtfp.workingmemory.app.appView.dialogResult(), and com.gtfp.workingmemory.app.appController.onOptionsItemSelected().
onPrepareOptionsMenu()
boolean com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu (Menu menu) package
Definition at line 342 of file appView.java.
References com.gtfp.workingmemory.app.appController.getSignature(), com.gtfp.workingmemory.app.App.inDebugger(), com.gtfp.workingmemory.Auth.Auth.isLoggedIn(), com.gtfp.workingmemory.app.appView.onErrorMenu(), and com.gtfp.workingmemory.app.appView.onThrowError().
Referenced by com.gtfp.workingmemory.app.appController.onPrepareOptionsMenu().
onErrorMenu()
void com.gtfp.workingmemory.app.appView.onErrorMenu (Menu menu) package
Definition at line 366 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu().
onThrowError()
void com.gtfp.workingmemory.app.appView.onThrowError (Menu menu) package
Definition at line 403 of file appView.java.
References com.gtfp.workingmemory.app.App.inDebugger().
Referenced by com.gtfp.workingmemory.app.appView.onPrepareOptionsMenu().
onActivityResult()
void com.gtfp.workingmemory.app.appView.onActivityResult (int requestCode, int resultCode, Intent data) package
Definition at line 441 of file appView.java.
References com.gtfp.workingmemory.app.appView.saveEdit().
Referenced by com.gtfp.workingmemory.app.appController.onActivityResult().
saveEdit()
boolean com.gtfp.workingmemory.app.appView.saveEdit (ToDoItem itemToDo) package
Definition at line 462 of file appView.java.
References com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), and com.gtfp.workingmemory.app.appView.save().
Referenced by com.gtfp.workingmemory.app.appView.onActivityResult().
save()
boolean com.gtfp.workingmemory.app.appView.save (ToDoItem itemToDo)
Definition at line 470 of file appView.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.add(), com.gtfp.workingmemory.settings.appSettings.getBoolean(), com.gtfp.workingmemory.app.appView.mAlarmManager, com.gtfp.workingmemory.todo.ToDoItem.newItem(), com.gtfp.workingmemory.app.appView.restoreSync(), com.gtfp.workingmemory.todo.ToDoListAdapter.save(), com.gtfp.workingmemory.app.appModel.save(), com.gtfp.workingmemory.wallpaper.Wallpaper.set(), and com.gtfp.workingmemory.todo.ToDoItem.setAlarm().
Referenced by com.gtfp.workingmemory.app.appView.saveEdit().
delete() [1/2]
boolean com.gtfp.workingmemory.app.appView.delete (int todoListID)
Definition at line 516 of file appView.java.
References com.gtfp.workingmemory.app.appModel.delete(), com.gtfp.workingmemory.todo.ToDoListAdapter.getItem(), com.gtfp.workingmemory.app.appView.mAlarmManager, com.gtfp.workingmemory.todo.ToDoListAdapter.remove(), com.gtfp.workingmemory.todo.ToDoListAdapter.save(), com.gtfp.workingmemory.utils.dialog.show(), com.gtfp.workingmemory.app.appView.showDeleted(), com.gtfp.workingmemory.app.appModel.ToDoList(), and com.gtfp.workingmemory.app.appModel.trueDelete().
Referenced by com.gtfp.workingmemory.utils.Dialogue.Delete().
refreshList()
void com.gtfp.workingmemory.app.appView.refreshList ()
Definition at line 579 of file appView.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.setItems(), and com.gtfp.workingmemory.app.appModel.ToDoList().
Referenced by com.gtfp.workingmemory.db.dbCloud.asyncData.onPostExecute().
onCreateContextMenu()
void com.gtfp.workingmemory.app.appView.onCreateContextMenu (ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo) package
Definition at line 591 of file appView.java.
References com.gtfp.workingmemory.app.appView.getRowTitle().
Referenced by com.gtfp.workingmemory.app.appController.onCreateContextMenu().
onContextItemSelected()
boolean com.gtfp.workingmemory.app.appView.onContextItemSelected (MenuItem item) package
Definition at line 612 of file appView.java.
References com.gtfp.workingmemory.edit.appCRUD.edit(), com.gtfp.workingmemory.app.appView.mToDoListID, and com.gtfp.workingmemory.app.appController.onContextItemSelected().
Referenced by com.gtfp.workingmemory.app.appController.onContextItemSelected().
open()
boolean com.gtfp.workingmemory.app.appView.open ()
Definition at line 637 of file appView.java.
References com.gtfp.workingmemory.app.appModel.open().
Referenced by com.gtfp.workingmemory.utils.Dialogue.Delete(), com.gtfp.workingmemory.app.appView.importData(), and com.gtfp.workingmemory.todo.ToDoAlarm.resetAlarms().
close()
void com.gtfp.workingmemory.app.appView.close ()
Definition at line 645 of file appView.java.
References com.gtfp.workingmemory.app.appModel.close().
Referenced by com.gtfp.workingmemory.utils.Dialogue.Delete().
listToDos()
ArrayList<ToDoItem> com.gtfp.workingmemory.app.appView.listToDos () private
Definition at line 653 of file appView.java.
References com.gtfp.workingmemory.app.appModel.ToDoList().
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick(), com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged(), and com.gtfp.workingmemory.app.appView.onStart().
getRowTitle()
String com.gtfp.workingmemory.app.appView.getRowTitle (AdapterView.AdapterContextMenuInfo info) private
Definition at line 661 of file appView.java.
References com.gtfp.workingmemory.edit.rowView.mTextView.
Referenced by com.gtfp.workingmemory.app.appView.onCreateContextMenu().
resetAlarms()
void com.gtfp.workingmemory.app.appView.resetAlarms ()
Definition at line 676 of file appView.java.
References com.gtfp.workingmemory.app.appView.setAlarms(), and com.gtfp.workingmemory.app.appModel.ToDoList().
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.resetAlarms().
setAlarms()
void com.gtfp.workingmemory.app.appView.setAlarms (List< ToDoItem > todoList) private
Definition at line 685 of file appView.java.
References com.gtfp.workingmemory.app.appView.getThreshold(), and com.gtfp.workingmemory.app.appView.mAlarmManager.
Referenced by com.gtfp.workingmemory.app.appView.resetAlarms().
getThreshold()
Calendar com.gtfp.workingmemory.app.appView.getThreshold () private
Definition at line 702 of file appView.java.
References com.gtfp.workingmemory.app.appView.mToday.
Referenced by com.gtfp.workingmemory.app.appView.setAlarms().
editAlarm()
boolean com.gtfp.workingmemory.app.appView.editAlarm (Intent intent) private
Definition at line 716 of file appView.java.
References com.gtfp.workingmemory.edit.appCRUD.edit(), and com.gtfp.workingmemory.todo.ToDoListAdapter.getListId().
Referenced by com.gtfp.workingmemory.app.appView.onCreate(), and com.gtfp.workingmemory.app.appView.onNewIntent().
delete() [2/2]
boolean com.gtfp.workingmemory.app.appView.delete (long id)
Definition at line 745 of file appView.java.
References com.gtfp.workingmemory.edit.appCRUD.delete().
showDeleted()
boolean com.gtfp.workingmemory.app.appView.showDeleted () package
Definition at line 751 of file appView.java.
References com.gtfp.workingmemory.app.appModel.showDeleted().
Referenced by com.gtfp.workingmemory.app.appView.delete().
hideActionBar()
boolean com.gtfp.workingmemory.app.appView.hideActionBar () private
Definition at line 757 of file appView.java.
runActivity()
boolean com.gtfp.workingmemory.app.appView.runActivity (Class<?> cls) private
Definition at line 769 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.signInApp.onAuthStateChanged(), and com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
runFragment()
boolean com.gtfp.workingmemory.app.appView.runFragment (Fragment newFragment, int layoutID) private
Definition at line 794 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.listErrors(), and com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
onAuthStateChanged()
void com.gtfp.workingmemory.app.appView.onAuthStateChanged (@NonNull FirebaseAuth firebaseAuth)
Definition at line 821 of file appView.java.
References com.gtfp.workingmemory.app.appController.NoConnectivity().
onDataChange()
void com.gtfp.workingmemory.app.appView.onDataChange (DataSnapshot snapshot)
Definition at line 835 of file appView.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.createCurrentRecs(), and com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onDataChange().
onCancelled()
void com.gtfp.workingmemory.app.appView.onCancelled (DatabaseError databaseError)
Definition at line 845 of file appView.java.
Referenced by com.gtfp.workingmemory.db.dbFireBase.createCurrentRecs(), and com.gtfp.workingmemory.db.dbFireBase.dbTasksData.onCancelled().
onSharedPreferenceChanged()
void com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged (SharedPreferences sharedPreferences, String key)
Definition at line 855 of file appView.java.
References com.gtfp.workingmemory.settings.appSettings.getBoolean(), com.gtfp.workingmemory.app.appView.listToDos(), com.gtfp.workingmemory.app.appModel.open(), com.gtfp.workingmemory.todo.ToDoListAdapter.refresh(), com.gtfp.workingmemory.app.appModel.resetDBHelper(), com.gtfp.workingmemory.todo.ToDoListAdapter.sort(), and com.gtfp.workingmemory.app.appView.syncData().
Referenced by com.gtfp.workingmemory.settings.appSettings.onSharedPreferenceChanged().
onPreferenceClick()
boolean com.gtfp.workingmemory.app.appView.onPreferenceClick (Preference preference)
Definition at line 895 of file appView.java.
References com.gtfp.workingmemory.app.appModel.delete(), com.gtfp.workingmemory.app.appView.exportData(), com.gtfp.workingmemory.app.appView.importData(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), com.gtfp.workingmemory.todo.ToDoItem.isPastDue(), com.gtfp.workingmemory.todo.ToDoListAdapter.Iterate(), com.gtfp.workingmemory.app.appView.listToDos(), com.gtfp.workingmemory.app.appModel.open(), com.gtfp.workingmemory.todo.ToDoListAdapter.refresh(), and com.gtfp.workingmemory.app.appModel.trueDelete().
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick().
dialogResult()
void com.gtfp.workingmemory.app.appView.dialogResult (boolean result)
Implements com.gtfp.workingmemory.utils.dialog.DialogBoxListener.
Definition at line 961 of file appView.java.
References com.gtfp.workingmemory.app.appView.deleteResult(), and com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
deleteResult()
void com.gtfp.workingmemory.app.appView.deleteResult (boolean result) package
Definition at line 979 of file appView.java.
References com.gtfp.workingmemory.todo.ToDoListAdapter.getItem(), com.gtfp.workingmemory.todo.ToDoItem.isDeleted(), and com.gtfp.workingmemory.app.appView.mToDoListID.
Referenced by com.gtfp.workingmemory.app.appView.dialogResult().
getController()
appController com.gtfp.workingmemory.app.appView.getController ()
Definition at line 999 of file appView.java.
References com.gtfp.workingmemory.app.appView.mController.
Referenced by com.gtfp.workingmemory.app.appModel.getController(), and com.gtfp.workingmemory.db.dbFireBase.isOnline().
getActivity()
Activity com.gtfp.workingmemory.app.appView.getActivity ()
Definition at line 1004 of file appView.java.
References com.gtfp.workingmemory.app.appView.mController.
Referenced by com.gtfp.workingmemory.settings.appSettings.appSettings(), and com.gtfp.workingmemory.settings.appSettings.withPermission().
getContext()
Context com.gtfp.workingmemory.app.appView.getContext ()
Definition at line 1009 of file appView.java.
References com.gtfp.workingmemory.app.appView.mContext.
Referenced by com.gtfp.workingmemory.app.appModel.appModel(), com.gtfp.workingmemory.db.dbFireBase.dbFireBase(), and com.gtfp.workingmemory.app.appModel.getDBHelper().
getModel()
appModel com.gtfp.workingmemory.app.appView.getModel ()
Definition at line 1014 of file appView.java.
References com.gtfp.workingmemory.app.appView.mAppModel.
Referenced by com.gtfp.workingmemory.app.appController.getModel(), and com.gtfp.workingmemory.app.appModel.onStart().
getPackageName()
String com.gtfp.workingmemory.app.appView.getPackageName ()
Definition at line 1019 of file appView.java.
References com.gtfp.workingmemory.app.appView.PACKAGE_NAME, and com.gtfp.workingmemory.app.App.setPackageName().
Referenced by com.gtfp.workingmemory.app.appView.getPI().
deleteSync()
boolean com.gtfp.workingmemory.app.appView.deleteSync () private
Definition at line 1028 of file appView.java.
References com.gtfp.workingmemory.app.appView.mDeleteSync, and com.gtfp.workingmemory.app.appView.syncData().
Referenced by com.gtfp.workingmemory.app.appView.restoreSync().
listErrors()
void com.gtfp.workingmemory.app.appView.listErrors () package
Definition at line 1044 of file appView.java.
References com.gtfp.workingmemory.app.appView.runFragment().
syncData() [1/2]
void com.gtfp.workingmemory.app.appView.syncData ()
Definition at line 1063 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.deleteSync(), com.gtfp.workingmemory.edit.appCRUD.edit(), com.gtfp.workingmemory.app.appView.onOptionsItemSelected(), and com.gtfp.workingmemory.app.appView.onSharedPreferenceChanged().
syncData() [2/2]
void com.gtfp.workingmemory.app.appView.syncData (String param) private
Definition at line 1072 of file appView.java.
References com.gtfp.workingmemory.db.dbFireBase.sync().
restoreSync()
void com.gtfp.workingmemory.app.appView.restoreSync ()
Definition at line 1107 of file appView.java.
References com.gtfp.workingmemory.app.appView.deleteSync(), and com.gtfp.workingmemory.app.appView.syncFile().
Referenced by com.gtfp.workingmemory.app.appView.save().
insertTempRec()
boolean com.gtfp.workingmemory.app.appView.insertTempRec ()
Definition at line 1126 of file appView.java.
References com.gtfp.workingmemory.app.appModel.insertTempRec().
createEmptyTemp()
boolean com.gtfp.workingmemory.app.appView.createEmptyTemp ()
Definition at line 1131 of file appView.java.
References com.gtfp.workingmemory.app.appModel.createEmptyTemp().
importRec()
void com.gtfp.workingmemory.app.appView.importRec (String columnName, String value)
Definition at line 1136 of file appView.java.
References com.gtfp.workingmemory.app.appModel.importRec().
ToDoList()
ArrayList<ToDoItem> com.gtfp.workingmemory.app.appView.ToDoList (Cursor recs)
Definition at line 1141 of file appView.java.
References com.gtfp.workingmemory.app.appModel.ToDoList().
getNewTempRecs()
Cursor com.gtfp.workingmemory.app.appView.getNewTempRecs ()
Definition at line 1146 of file appView.java.
References com.gtfp.workingmemory.app.appModel.getNewTempRecs().
getPImethod()
Method com.gtfp.workingmemory.app.appView.getPImethod ()
Definition at line 1151 of file appView.java.
References com.gtfp.workingmemory.app.App.getPI(), and com.gtfp.workingmemory.app.appController.getPM().
Referenced by com.gtfp.workingmemory.app.appView.getPI().
getPI()
Object com.gtfp.workingmemory.app.appView.getPI ()
Definition at line 1168 of file appView.java.
References com.gtfp.workingmemory.app.appView.getPackageName(), com.gtfp.workingmemory.app.appView.getPImethod(), and com.gtfp.workingmemory.app.appController.getPM().
Referenced by com.gtfp.workingmemory.app.appController.getSignature().
versionOfApp()
String com.gtfp.workingmemory.app.appView.versionOfApp () private
Definition at line 1184 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.onOptionsItemSelected().
exportData()
boolean com.gtfp.workingmemory.app.appView.exportData () private
Definition at line 1206 of file appView.java.
References com.gtfp.workingmemory.app.appView.createDataFile(), and com.gtfp.workingmemory.app.appView.exportDataFile().
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick().
syncFile()
String com.gtfp.workingmemory.app.appView.syncFile ()
Definition at line 1213 of file appView.java.
References com.gtfp.workingmemory.app.appView.createDataFile(), and com.gtfp.workingmemory.app.appView.getSyncFile().
Referenced by com.gtfp.workingmemory.app.appView.restoreSync().
syncFileName()
String com.gtfp.workingmemory.app.appView.syncFileName () package
Definition at line 1231 of file appView.java.
References com.gtfp.workingmemory.app.appView.getSyncFile().
getSyncFile()
File com.gtfp.workingmemory.app.appView.getSyncFile () private
Definition at line 1236 of file appView.java.
References com.gtfp.workingmemory.app.appView.appDir(), and com.gtfp.workingmemory.app.appView.mSyncFile.
Referenced by com.gtfp.workingmemory.app.appView.syncFile(), and com.gtfp.workingmemory.app.appView.syncFileName().
createDataFile()
boolean com.gtfp.workingmemory.app.appView.createDataFile (File file) private
Definition at line 1246 of file appView.java.
References com.gtfp.workingmemory.app.appModel.getRecs(), com.gtfp.workingmemory.app.appView.showMessage(), and com.gtfp.workingmemory.settings.appSettings.withPermission().
Referenced by com.gtfp.workingmemory.app.appView.exportData(), and com.gtfp.workingmemory.app.appView.syncFile().
importData()
boolean com.gtfp.workingmemory.app.appView.importData () private
Definition at line 1312 of file appView.java.
References com.gtfp.workingmemory.app.appView.exportDataFile(), com.gtfp.workingmemory.app.appModel.importRec(), and com.gtfp.workingmemory.app.appView.open().
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick().
appDir()
File com.gtfp.workingmemory.app.appView.appDir () private
Definition at line 1353 of file appView.java.
References com.gtfp.workingmemory.app.App.getFilesDir().
Referenced by com.gtfp.workingmemory.app.appView.getSyncFile().
isDebuggable()
boolean com.gtfp.workingmemory.app.appView.isDebuggable () private
Returns true if the application is debuggable.
Returns
true if the application is debuggable.
Definition at line 1363 of file appView.java.
exportDir()
File com.gtfp.workingmemory.app.appView.exportDir () private
Definition at line 1378 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.exportDataFile().
exportDataFile()
File com.gtfp.workingmemory.app.appView.exportDataFile () private
Definition at line 1390 of file appView.java.
References com.gtfp.workingmemory.app.appView.exportDir().
Referenced by com.gtfp.workingmemory.app.appView.exportData(), and com.gtfp.workingmemory.app.appView.importData().
showMessage()
void com.gtfp.workingmemory.app.appView.showMessage (String message) package
Shows a toast message.
Definition at line 1401 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.createDataFile().
onNewIntent()
void com.gtfp.workingmemory.app.appView.onNewIntent (Intent intent) protected
Definition at line 1408 of file appView.java.
References com.gtfp.workingmemory.app.appView.editAlarm().
Referenced by com.gtfp.workingmemory.app.appController.onNewIntent().
onSaveInstanceState()
void com.gtfp.workingmemory.app.appView.onSaveInstanceState (Bundle savedInstanceState) protected
Definition at line 1414 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appController.onSaveInstanceState().
onRestoreInstanceState()
void com.gtfp.workingmemory.app.appView.onRestoreInstanceState (Bundle savedInstanceState) protected
Definition at line 1420 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appController.onRestoreInstanceState().
onPause()
void com.gtfp.workingmemory.app.appView.onPause () protected
Definition at line 1426 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appController.onPause().
onStop()
void com.gtfp.workingmemory.app.appView.onStop () protected
Definition at line 1431 of file appView.java.
References com.gtfp.workingmemory.app.appModel.onStop().
Referenced by com.gtfp.workingmemory.app.appController.onStop().
onStart()
void com.gtfp.workingmemory.app.appView.onStart () protected
Definition at line 1438 of file appView.java.
References com.gtfp.workingmemory.app.appView.listToDos(), and com.gtfp.workingmemory.app.appModel.onStart().
Referenced by com.gtfp.workingmemory.app.appController.onStart().
onRestart()
void com.gtfp.workingmemory.app.appView.onRestart () protected
Definition at line 1450 of file appView.java.
References com.gtfp.workingmemory.app.appModel.onRestart().
Referenced by com.gtfp.workingmemory.app.appController.onRestart().
onDestroy()
void com.gtfp.workingmemory.app.appView.onDestroy ()
Definition at line 1455 of file appView.java.
References com.gtfp.workingmemory.app.appView.mAlarmManager, com.gtfp.workingmemory.edit.appCRUD.onDestroy(), com.gtfp.workingmemory.app.App.onDestroy(), com.gtfp.workingmemory.todo.ToDoListAdapter.onDestroy(), com.gtfp.workingmemory.settings.appSettings.onDestroy(), and com.gtfp.workingmemory.app.appModel.onDestroy().
Referenced by com.gtfp.workingmemory.app.appController.onDestroy(), and com.gtfp.workingmemory.todo.ToDoAlarm.resetAlarms().
Member Data Documentation
ALARM_ID
final String com.gtfp.workingmemory.app.appView.ALARM_ID = "id" static private
Definition at line 72 of file appView.java.
CONTENT_VIEW_ID
final int com.gtfp.workingmemory.app.appView.CONTENT_VIEW_ID = View.generateViewId() static private
Definition at line 74 of file appView.java.
PACKAGE_NAME
String com.gtfp.workingmemory.app.appView.PACKAGE_NAME static private
Definition at line 76 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.getPackageName().
mClearNotification
boolean com.gtfp.workingmemory.app.appView.mClearNotification static private
Definition at line 78 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.clearNotification().
mSyncData
boolean com.gtfp.workingmemory.app.appView.mSyncData static private
Definition at line 80 of file appView.java.
mRestoreSync
boolean com.gtfp.workingmemory.app.appView.mRestoreSync static private
Definition at line 82 of file appView.java.
mDeleteSync
boolean com.gtfp.workingmemory.app.appView.mDeleteSync = false static private
Definition at line 84 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.deleteSync().
REQUEST_CODE
final int com.gtfp.workingmemory.app.appView.REQUEST_CODE = 1 private
Definition at line 86 of file appView.java.
GOOGLE_REQUEST
final int com.gtfp.workingmemory.app.appView.GOOGLE_REQUEST = 2 private
Definition at line 88 of file appView.java.
ERROR_REQUEST
final int com.gtfp.workingmemory.app.appView.ERROR_REQUEST = 3 private
Definition at line 90 of file appView.java.
mController
appController com.gtfp.workingmemory.app.appView.mController
Definition at line 92 of file appView.java.
Referenced by com.gtfp.workingmemory.edit.appCRUD.appCRUD(), com.gtfp.workingmemory.edit.appCRUD.edit(), com.gtfp.workingmemory.app.appView.getActivity(), and com.gtfp.workingmemory.app.appView.getController().
mAppModel
appModel com.gtfp.workingmemory.app.appView.mAppModel
Definition at line 94 of file appView.java.
Referenced by com.gtfp.workingmemory.edit.appCRUD.delete(), and com.gtfp.workingmemory.app.appView.getModel().
mToDoListAdapter
ToDoListAdapter com.gtfp.workingmemory.app.appView.mToDoListAdapter
Definition at line 96 of file appView.java.
Referenced by com.gtfp.workingmemory.edit.appCRUD.dialogResult(), and com.gtfp.workingmemory.edit.appCRUD.edit().
mAlarmManager
ToDoAlarm.Manager com.gtfp.workingmemory.app.appView.mAlarmManager
Definition at line 98 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.appView(), com.gtfp.workingmemory.edit.appCRUD.delete(), com.gtfp.workingmemory.app.appView.delete(), com.gtfp.workingmemory.app.appView.onDestroy(), com.gtfp.workingmemory.app.appView.save(), and com.gtfp.workingmemory.app.appView.setAlarms().
mItemsOnWallpaper
Wallpaper com.gtfp.workingmemory.app.appView.mItemsOnWallpaper
Definition at line 100 of file appView.java.
mFragMngr
FragmentManager com.gtfp.workingmemory.app.appView.mFragMngr package
Definition at line 102 of file appView.java.
mContext
Context com.gtfp.workingmemory.app.appView.mContext package
Definition at line 104 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.getContext().
mFirstCall
boolean com.gtfp.workingmemory.app.appView.mFirstCall = true private
Definition at line 108 of file appView.java.
mAppCRUD
appCRUD com.gtfp.workingmemory.app.appView.mAppCRUD private
Definition at line 110 of file appView.java.
mTaskList
ListView com.gtfp.workingmemory.app.appView.mTaskList private
Definition at line 112 of file appView.java.
mToDoListID
int com.gtfp.workingmemory.app.appView.mToDoListID = -1 private
Definition at line 114 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.deleteResult(), and com.gtfp.workingmemory.app.appView.onContextItemSelected().
mIntent
Intent com.gtfp.workingmemory.app.appView.mIntent private
Definition at line 116 of file appView.java.
mTrulyDelete
boolean com.gtfp.workingmemory.app.appView.mTrulyDelete = false private
Definition at line 118 of file appView.java.
mSigMatch
boolean com.gtfp.workingmemory.app.appView.mSigMatch private
Definition at line 120 of file appView.java.
mSyncFile
File com.gtfp.workingmemory.app.appView.mSyncFile private
Definition at line 122 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.getSyncFile().
mAppSettings
appSettings com.gtfp.workingmemory.app.appView.mAppSettings private
Definition at line 124 of file appView.java.
mDialogue
dialog com.gtfp.workingmemory.app.appView.mDialogue private
Definition at line 126 of file appView.java.
mToday
Calendar com.gtfp.workingmemory.app.appView.mToday private
Definition at line 128 of file appView.java.
Referenced by com.gtfp.workingmemory.app.appView.getThreshold().
mMenuItem
MenuItem com.gtfp.workingmemory.app.appView.mMenuItem private
Definition at line 130 of file appView.java.
mErrorMenuItem
MenuItem com.gtfp.workingmemory.app.appView.mErrorMenuItem private
Definition at line 132 of file appView.java.
mThrowErrorMenu
MenuItem com.gtfp.workingmemory.app.appView.mThrowErrorMenu private
Definition at line 134 of file appView.java.
mItemTitle
CharSequence com.gtfp.workingmemory.app.appView.mItemTitle private
Definition at line 136 of file appView.java.
mFrameLayout
FrameLayout com.gtfp.workingmemory.app.appView.mFrameLayout private
Definition at line 138 of file appView.java.