Working Memory: com.gtfp.workingmemory.google.GoogleLogin_THROWOUT Class Reference
com.gtfp.workingmemory.google.GoogleLogin_THROWOUT Class Reference
Use this class to login with google account using the OpenId oauth method.
Static Public Member Functions
static void silent (Context appContext)
Performs a silent sign in and fetch a token.
Private Member Functions
GoogleLogin_THROWOUT (Context appContext)
void createGoogleClient ()
void silent ()
void onSilentLoginFinished (GoogleSignInResult signInResult)
Private Attributes
GoogleApiClient mGoogleApiClient
Context mContext
Static Private Attributes
static final String TAG = GoogleLogin_THROWOUT.class.getName()
static final String SERVER_CLIENT_ID = "761477102089-qihk55871jg3ck3pqbff5c3jgeut2jk9.apps.googleusercontent.com"
Detailed Description
Use this class to login with google account using the OpenId oauth method.
Definition at line 27 of file GoogleLogin_THROWOUT.java.
Constructor & Destructor Documentation
GoogleLogin_THROWOUT()
com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.GoogleLogin_THROWOUT (Context appContext) private
Definition at line 39 of file GoogleLogin_THROWOUT.java.
References com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.createGoogleClient().
Referenced by com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.silent().
Member Function Documentation
silent() [1/2]
static void com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.silent (Context appContext) static
Performs a silent sign in and fetch a token.
Parameters
appContext Application context
Definition at line 51 of file GoogleLogin_THROWOUT.java.
References com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.GoogleLogin_THROWOUT().
createGoogleClient()
void com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.createGoogleClient () private
Definition at line 57 of file GoogleLogin_THROWOUT.java.
References com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.onSilentLoginFinished().
Referenced by com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.GoogleLogin_THROWOUT().
silent() [2/2]
void com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.silent () private
Definition at line 91 of file GoogleLogin_THROWOUT.java.
References com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.onSilentLoginFinished().
onSilentLoginFinished()
void com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.onSilentLoginFinished (GoogleSignInResult signInResult) private
Definition at line 122 of file GoogleLogin_THROWOUT.java.
Referenced by com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.createGoogleClient(), and com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.silent().
Member Data Documentation
TAG
final String com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.TAG = GoogleLogin_THROWOUT.class.getName() static private
Definition at line 29 of file GoogleLogin_THROWOUT.java.
SERVER_CLIENT_ID
final String com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.SERVER_CLIENT_ID = "761477102089-qihk55871jg3ck3pqbff5c3jgeut2jk9.apps.googleusercontent.com" static private
Definition at line 32 of file GoogleLogin_THROWOUT.java.
mGoogleApiClient
GoogleApiClient com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.mGoogleApiClient private
Definition at line 34 of file GoogleLogin_THROWOUT.java.
mContext
Context com.gtfp.workingmemory.google.GoogleLogin_THROWOUT.mContext private
Definition at line 36 of file GoogleLogin_THROWOUT.java.