Working Memory: com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask Class Reference
com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask Class Reference
Protected Member Functions
String doInBackgroundConnected (DriveId... params)
void onPostExecute (String result)
void onCancelled (String result)
Protected Member Functions inherited from com.gtfp.workingmemory.google.googleAPI.ApiClientAsyncTask< DriveId, Boolean, String >
final Result doInBackground (Params... params)
abstract Result doInBackgroundConnected (Params... params)
Override this method to perform a computation on a background thread, while the client is connected.
GoogleApiClient getGoogleApiClient ()
Gets the GoogleApliClient owned by this async task.
Package Functions
RetrieveDriveFileContentsAsyncTask (GoogleApiClient apiClient, ApiClientTask obj)
Package Functions inherited from com.gtfp.workingmemory.google.googleAPI.ApiClientAsyncTask< DriveId, Boolean, String >
ApiClientAsyncTask (GoogleApiClient apiClient)
Package Attributes
ApiClientTask mDoInBackground
Detailed Description
Definition at line 725 of file googleAPI.java.
Constructor & Destructor Documentation
RetrieveDriveFileContentsAsyncTask()
com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.RetrieveDriveFileContentsAsyncTask (GoogleApiClient apiClient, ApiClientTask obj) package
Definition at line 730 of file googleAPI.java.
Member Function Documentation
doInBackgroundConnected()
String com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.doInBackgroundConnected (DriveId... params) protected
Definition at line 737 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.ApiClientTask.onExecute().
onPostExecute()
void com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.onPostExecute (String result) protected
Definition at line 757 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.ApiClientTask.onPostExecute().
onCancelled()
void com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.onCancelled (String result) protected
Definition at line 773 of file googleAPI.java.
References com.gtfp.workingmemory.google.googleAPI.ApiClientTask.onCancelled().
Member Data Documentation
mDoInBackground
ApiClientTask com.gtfp.workingmemory.google.googleAPI.RetrieveDriveFileContentsAsyncTask.mDoInBackground package
Definition at line 728 of file googleAPI.java.