Working Memory: com.gtfp.workingmemory.todo.ToDoItem Class Reference
com.gtfp.workingmemory.todo.ToDoItem Class Reference
Classes
class ToDoDateTime
Public Member Functions
ToDoItem ()
boolean setItemName (String name)
String getItemName ()
void setId (long id)
void setId (String id)
long getId ()
void setKey (String key)
String getKey ()
boolean newItem (boolean newItem)
boolean newItem ()
boolean setAlarm (boolean setAlarm)
boolean setAlarm ()
int setListPosn (int position)
int getListPosn ()
String itemToDisplay ()
boolean setDueDate (String duedate)
boolean setDueDate (Calendar cal)
boolean setDueDate (long epoch)
String getDueDate ()
Calendar getCalendar ()
boolean setReminderEpoch (long milliseconds)
Give input time in epoch.
boolean setReminderEpoch (Calendar dtReminder)
long getReminderEpoch ()
boolean setReminderChk (int chkPosn)
int getReminderChk ()
int setLEDColor (int color)
int getLEDColor ()
boolean LEDColorChanged ()
int setLEDOn (int rateOn)
int getLEDOn ()
boolean LEDOnChanged ()
int setLEDOff (int rateOff)
int getLEDOff ()
boolean LEDOffChanged ()
void hasFired (boolean fired)
boolean hasFired ()
boolean settingsChanged ()
boolean settingsChanged (boolean changed)
void setShowDialogue (boolean setting)
boolean showDialogue (boolean setting)
void setUseVibrate (boolean setting)
boolean useVibrate (boolean setting)
void setClearNotification (boolean setting)
boolean clearNotification (boolean setting)
void setUseLED (boolean setting)
boolean useLED (boolean setting)
void setSound (Uri sound)
void setSound (String sound)
Uri Sound (Uri sound)
Uri Sound (String sound)
int reminderInterval ()
boolean isDeleted ()
boolean isDeleted (boolean deleted)
int getYear ()
int getMonth ()
int getDay ()
int getHour ()
int getMin ()
void setTimestamp ()
long getTimestamp ()
long getDueDateInEpoch ()
String getDueDateToDisplay ()
String displayDueDate ()
boolean isPastDue ()
String toString ()
ToDoItem clone ()
Static Public Member Functions
static String formatW_M_D_12H (long epoch)
static String EpochToDateTime (long epoch)
static Long TodayInEpoch ()
static String displayDueDate (long epoch)
static String displayTime (long epoch)
static Long toEpoch (int year, int month, int day)
static Long toEpoch (int year, int month, int day, int hour, int min)
static Date justDate (Calendar cal)
static Date justDate (long dateTime)
static boolean isSameDay (Calendar c1, Calendar c2)
Protected Member Functions
void onDestroy ()
Static Package Functions
static String formatDateTime (long epoch)
TODO These two functions are never used.
static String formatTime (long epoch)
static String formatW_M_D (long epoch)
static Calendar EpochToCalendar (long epoch)
[static initializer]
Package Attributes
int mLEDColor = 0
int mLEDOn = 0
int mLEDOff = 0
Private Member Functions
Date DueDate ()
long convertToEpoch (String dt)
Static Private Member Functions
static String formatDisplay (long epoch)
static String formatW_Y_M_D_12H (long epoch)
static Date TodayDate ()
static Date TomorrowDate ()
Private Attributes
String mItemName = ""
boolean mNewItem = false
boolean mSetAlarm = true
String mDueDate = "None"
long mDueDateInEpoch = 0
Calendar mDueDateCalendar = null
long mReminder = -1
int mReminderChk = 0
int mOldColor
int mOldLEDOn
int mOldLEDOff
boolean mSettingsChanged = false
boolean mHasFired = false
int mShowPopup = 0
int mUseVibrate = 0
int mClearNotification = 0
int mUseLED = 0
String mUriSound = null
long mTimestamp
int mListPosn = -1
boolean mDeleted = false
final ToDoDateTime mDateTime
long mId = -1
String mKey = ""
Static Private Attributes
static final long serialVersionUID = -7507171562852085782L
static Date mTempDate = new Date()
static Calendar mTempCal = Calendar.getInstance()
static final String Y_M_D = "yyyy-MM-dd "
static final String W_M_D = "EEE, MMM d "
static final String W_Y_M_D = "EEE, yyyy-MM-dd "
static final String HOURS_12 = " h:mm a"
static final String HOURS_24 = " HH:mm"
static final DateTimeFormatter mDayFormat = DateTimeFormat.forPattern(W_M_D)
static final DateTimeFormatter mW_Y_M_D12HrFormat
static final DateFormat m12DateTimeFormat = new SimpleDateFormat(W_M_D + HOURS_12)
static final DateTimeFormatter m12TimeFormat = DateTimeFormat.forPattern(HOURS_12)
static final DateTimeFormatter mStoredFormat
static final DateFormat mEpochFormat = new SimpleDateFormat(Y_M_D + HOURS_24)
Detailed Description
Definition at line 17 of file ToDoItem.java.
Constructor & Destructor Documentation
ToDoItem()
com.gtfp.workingmemory.todo.ToDoItem.ToDoItem ()
Definition at line 19 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.clone().
Member Function Documentation
setItemName()
boolean com.gtfp.workingmemory.todo.ToDoItem.setItemName (String name)
Definition at line 32 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mItemName.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
getItemName()
String com.gtfp.workingmemory.todo.ToDoItem.getItemName ()
Definition at line 44 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mItemName.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.todo.ToDoListAdapter.getView(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.db.dbFireBase.toMap(), and com.gtfp.workingmemory.todo.ToDoItem.toString().
setId() [1/2]
void com.gtfp.workingmemory.todo.ToDoItem.setId (long id)
Definition at line 50 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mId.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.save(), com.gtfp.workingmemory.db.dbCloud.dbLocal.save(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
setId() [2/2]
void com.gtfp.workingmemory.todo.ToDoItem.setId (String id)
Definition at line 56 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mId.
getId()
long com.gtfp.workingmemory.todo.ToDoItem.getId ()
Definition at line 69 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mId.
Referenced by com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelAlarm(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.cancelNotification(), com.gtfp.workingmemory.utils.Dialogue.Dialogue(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.getAlarmIntent(), com.gtfp.workingmemory.todo.ToDoItemsList.getId(), com.gtfp.workingmemory.todo.ToDoItemsList.getListId(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm(), com.gtfp.workingmemory.app.appModel.save(), com.gtfp.workingmemory.db.dbSQLlite.save(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.db.dbFireBase.toMap(), com.gtfp.workingmemory.todo.ToDoItem.toString(), com.gtfp.workingmemory.app.appModel.trueDelete(), and com.gtfp.workingmemory.db.dbSQLlite.updateRec().
setKey()
void com.gtfp.workingmemory.todo.ToDoItem.setKey (String key)
Definition at line 76 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mKey.
Referenced by com.gtfp.workingmemory.db.dbFireBase.save(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), com.gtfp.workingmemory.db.dbFireBase.ToDoList(), and com.gtfp.workingmemory.db.dbCloud.dbLocal.toToDoItem().
getKey()
String com.gtfp.workingmemory.todo.ToDoItem.getKey ()
Definition at line 83 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mKey.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.app.appModel.save(), com.gtfp.workingmemory.db.dbCloud.dbLocal.save(), com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences(), and com.gtfp.workingmemory.db.dbFireBase.updateRec().
newItem() [1/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.newItem (boolean newItem)
Definition at line 90 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mNewItem, and com.gtfp.workingmemory.todo.ToDoItem.newItem().
Referenced by com.gtfp.workingmemory.app.appModel.save(), com.gtfp.workingmemory.app.appView.save(), com.gtfp.workingmemory.db.dbSQLlite.save(), com.gtfp.workingmemory.db.dbFireBase.save(), com.gtfp.workingmemory.db.dbCloud.dbLocal.save(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
newItem() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.newItem ()
Definition at line 97 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mNewItem.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.newItem().
setAlarm() [1/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.setAlarm (boolean setAlarm)
Definition at line 102 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mSetAlarm, and com.gtfp.workingmemory.todo.ToDoItem.setAlarm().
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.app.appView.save(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
setAlarm() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.setAlarm ()
Definition at line 113 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mSetAlarm.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setAlarm().
setListPosn()
int com.gtfp.workingmemory.todo.ToDoItem.setListPosn (int position)
Definition at line 118 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mListPosn.
Referenced by com.gtfp.workingmemory.edit.appCRUD.edit().
getListPosn()
int com.gtfp.workingmemory.todo.ToDoItem.getListPosn ()
Definition at line 127 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mListPosn.
Referenced by com.gtfp.workingmemory.todo.ToDoItemsList.update().
formatDateTime()
static String com.gtfp.workingmemory.todo.ToDoItem.formatDateTime (long epoch) static package
TODO These two functions are never used.
static String formatDate(Date dt) {
return mDateFormat.format(dt); }
static String formatDate(long epoch) {
return mDateFormat.format(new Date(epoch)); }
Definition at line 160 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mStoredFormat.
formatTime()
static String com.gtfp.workingmemory.todo.ToDoItem.formatTime (long epoch) static package
Definition at line 171 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.m12TimeFormat.
formatDisplay()
static String com.gtfp.workingmemory.todo.ToDoItem.formatDisplay (long epoch) static private
Definition at line 181 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.m12TimeFormat, and com.gtfp.workingmemory.todo.ToDoItem.mDayFormat.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay().
formatW_M_D()
static String com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D (long epoch) static package
Definition at line 192 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDayFormat.
formatW_M_D_12H()
static String com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D_12H (long epoch) static
Definition at line 203 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.m12TimeFormat, and com.gtfp.workingmemory.todo.ToDoItem.mDayFormat.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), and com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle().
formatW_Y_M_D_12H()
static String com.gtfp.workingmemory.todo.ToDoItem.formatW_Y_M_D_12H (long epoch) static private
Definition at line 214 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mW_Y_M_D12HrFormat.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.displayDueDate().
EpochToDateTime()
static String com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime (long epoch) static
Definition at line 223 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mStoredFormat.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.edit.editToDoItem.getDateString(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.stepTime(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
EpochToCalendar()
static Calendar com.gtfp.workingmemory.todo.ToDoItem.EpochToCalendar (long epoch) static package
Definition at line 235 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm().
DueDate()
Date com.gtfp.workingmemory.todo.ToDoItem.DueDate () private
Definition at line 249 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.justDate(), and com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay().
TodayDate()
static Date com.gtfp.workingmemory.todo.ToDoItem.TodayDate () static private
Definition at line 256 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.justDate().
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay().
TomorrowDate()
static Date com.gtfp.workingmemory.todo.ToDoItem.TomorrowDate () static private
Definition at line 262 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay().
TodayInEpoch()
static Long com.gtfp.workingmemory.todo.ToDoItem.TodayInEpoch () static
Definition at line 279 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.convertToEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay(), com.gtfp.workingmemory.todo.ToDoItemsList.newToDoItem(), and com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
itemToDisplay()
String com.gtfp.workingmemory.todo.ToDoItem.itemToDisplay ()
Definition at line 297 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mItemName.
Referenced by com.gtfp.workingmemory.utils.Dialogue.Dialogue(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification().
setDueDate() [1/3]
boolean com.gtfp.workingmemory.todo.ToDoItem.setDueDate (String duedate)
Definition at line 314 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.convertToEpoch(), com.gtfp.workingmemory.todo.ToDoItem.mDateTime, com.gtfp.workingmemory.todo.ToDoItem.mDueDate, com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, and com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.set().
Referenced by com.gtfp.workingmemory.todo.ToDoItemsList.newToDoItem(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.todo.ToDoItemsList.setDueDate(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
setDueDate() [2/3]
boolean com.gtfp.workingmemory.todo.ToDoItem.setDueDate (Calendar cal)
Definition at line 328 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.mDateTime, com.gtfp.workingmemory.todo.ToDoItem.mDueDate, com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, and com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.set().
setDueDate() [3/3]
boolean com.gtfp.workingmemory.todo.ToDoItem.setDueDate (long epoch)
Definition at line 347 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), com.gtfp.workingmemory.todo.ToDoItem.mDateTime, com.gtfp.workingmemory.todo.ToDoItem.mDueDate, com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, com.gtfp.workingmemory.todo.ToDoItem.mTempCal, and com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.set().
getDueDate()
String com.gtfp.workingmemory.todo.ToDoItem.getDueDate ()
Definition at line 369 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDueDate.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.toString().
getCalendar()
Calendar com.gtfp.workingmemory.todo.ToDoItem.getCalendar ()
Definition at line 375 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, and com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onCreate().
setReminderEpoch() [1/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch (long milliseconds)
Give input time in epoch.
Definition at line 388 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mReminder, and com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.todo.ToDoItemsList.newToDoItem(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
setReminderEpoch() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch (Calendar dtReminder)
Definition at line 404 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mReminder.
getReminderEpoch()
long com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch ()
Definition at line 419 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mReminder.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.db.dbFireBase.toMap(), and com.gtfp.workingmemory.todo.ToDoItem.toString().
setReminderChk()
boolean com.gtfp.workingmemory.todo.ToDoItem.setReminderChk (int chkPosn)
Definition at line 425 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mReminderChk.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
getReminderChk()
int com.gtfp.workingmemory.todo.ToDoItem.getReminderChk ()
Definition at line 436 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mReminderChk.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), com.gtfp.workingmemory.db.dbFireBase.setTask(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
setLEDColor()
int com.gtfp.workingmemory.todo.ToDoItem.setLEDColor (int color)
Definition at line 441 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDColor, and com.gtfp.workingmemory.todo.ToDoItem.mOldColor.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorChanged(), com.gtfp.workingmemory.edit.editToDoItem.getLEDColor(), com.gtfp.workingmemory.settings.appSettings.appPreferences.LEDSettingsResult(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.ToDoList().
getLEDColor()
int com.gtfp.workingmemory.todo.ToDoItem.getLEDColor ()
Definition at line 451 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDColor, and com.gtfp.workingmemory.todo.ToDoItem.mOldColor.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.edit.editToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.edit.editToDoItem.onCreate(), com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick(), com.gtfp.workingmemory.db.dbFireBase.setTask(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
LEDColorChanged()
boolean com.gtfp.workingmemory.todo.ToDoItem.LEDColorChanged ()
Definition at line 459 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDColor, and com.gtfp.workingmemory.todo.ToDoItem.mOldColor.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem().
setLEDOn()
int com.gtfp.workingmemory.todo.ToDoItem.setLEDOn (int rateOn)
Definition at line 465 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDOn, and com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOn.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.LEDSettingsResult(), and com.gtfp.workingmemory.edit.editToDoItem.onActivityResult().
getLEDOn()
int com.gtfp.workingmemory.todo.ToDoItem.getLEDOn ()
Definition at line 475 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDOn, and com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOn.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorWheel(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick().
LEDOnChanged()
boolean com.gtfp.workingmemory.todo.ToDoItem.LEDOnChanged ()
Definition at line 483 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDOn, and com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOn.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem().
setLEDOff()
int com.gtfp.workingmemory.todo.ToDoItem.setLEDOff (int rateOff)
Definition at line 489 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDOff, and com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOff.
Referenced by com.gtfp.workingmemory.settings.appSettings.appPreferences.LEDSettingsResult(), and com.gtfp.workingmemory.edit.editToDoItem.onActivityResult().
getLEDOff()
int com.gtfp.workingmemory.todo.ToDoItem.getLEDOff ()
Definition at line 499 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDOff, and com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOff.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.colorWheel(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onPreferenceClick().
LEDOffChanged()
boolean com.gtfp.workingmemory.todo.ToDoItem.LEDOffChanged ()
Definition at line 507 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mLEDOff, and com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOff.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem().
hasFired() [1/2]
void com.gtfp.workingmemory.todo.ToDoItem.hasFired (boolean fired)
Definition at line 513 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mHasFired.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), com.gtfp.workingmemory.db.dbFireBase.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
hasFired() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.hasFired ()
Definition at line 519 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mHasFired.
settingsChanged() [1/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.settingsChanged ()
Definition at line 525 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mSettingsChanged.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.saveToDoItem(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences().
settingsChanged() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.settingsChanged (boolean changed)
Definition at line 530 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mSettingsChanged.
setShowDialogue()
void com.gtfp.workingmemory.todo.ToDoItem.setShowDialogue (boolean setting)
Definition at line 539 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mShowPopup.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences().
showDialogue()
boolean com.gtfp.workingmemory.todo.ToDoItem.showDialogue (boolean setting)
Definition at line 544 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mShowPopup.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm().
setUseVibrate()
void com.gtfp.workingmemory.todo.ToDoItem.setUseVibrate (boolean setting)
Definition at line 557 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mUseVibrate.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences().
useVibrate()
boolean com.gtfp.workingmemory.todo.ToDoItem.useVibrate (boolean setting)
Definition at line 563 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mUseVibrate.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
setClearNotification()
void com.gtfp.workingmemory.todo.ToDoItem.setClearNotification (boolean setting)
Definition at line 576 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mClearNotification.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences().
clearNotification()
boolean com.gtfp.workingmemory.todo.ToDoItem.clearNotification (boolean setting)
Definition at line 582 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mClearNotification.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.setAlarm().
setUseLED()
void com.gtfp.workingmemory.todo.ToDoItem.setUseLED (boolean setting)
Definition at line 595 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mUseLED.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences().
useLED()
boolean com.gtfp.workingmemory.todo.ToDoItem.useLED (boolean setting)
Definition at line 601 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mUseLED.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
setSound() [1/2]
void com.gtfp.workingmemory.todo.ToDoItem.setSound (Uri sound)
Definition at line 614 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), com.gtfp.workingmemory.settings.appSettings.appPreferences.setItemPreferences(), and com.gtfp.workingmemory.todo.ToDoItem.Sound().
setSound() [2/2]
void com.gtfp.workingmemory.todo.ToDoItem.setSound (String sound)
Definition at line 624 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mUriSound.
Sound() [1/2]
Uri com.gtfp.workingmemory.todo.ToDoItem.Sound (Uri sound)
Definition at line 634 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.copyOver(), com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification(), com.gtfp.workingmemory.edit.editToDoItem.onActivityResult(), and com.gtfp.workingmemory.settings.appSettings.appPreferences.onCreate().
Sound() [2/2]
Uri com.gtfp.workingmemory.todo.ToDoItem.Sound (String sound)
Definition at line 644 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mUriSound, and com.gtfp.workingmemory.todo.ToDoItem.setSound().
reminderInterval()
int com.gtfp.workingmemory.todo.ToDoItem.reminderInterval ()
Definition at line 655 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, com.gtfp.workingmemory.todo.ToDoItem.mReminder, and com.gtfp.workingmemory.todo.ToDoItem.mReminderChk.
Referenced by com.gtfp.workingmemory.todo.ToDoAlarm.Manager.repeatAlarm().
isDeleted() [1/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.isDeleted ()
Definition at line 675 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDeleted.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.app.appView.deleteResult(), com.gtfp.workingmemory.edit.appCRUD.dialogResult(), com.gtfp.workingmemory.todo.ToDoListAdapter.getView(), com.gtfp.workingmemory.app.appView.onPreferenceClick(), com.gtfp.workingmemory.app.appView.saveEdit(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.db.dbSQLlite.ToDoList(), com.gtfp.workingmemory.db.dbFireBase.ToDoList(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
isDeleted() [2/2]
boolean com.gtfp.workingmemory.todo.ToDoItem.isDeleted (boolean deleted)
Definition at line 681 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDeleted.
getYear()
int com.gtfp.workingmemory.todo.ToDoItem.getYear ()
Definition at line 689 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getYear(), and com.gtfp.workingmemory.todo.ToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getMonth()
int com.gtfp.workingmemory.todo.ToDoItem.getMonth ()
Definition at line 693 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getMonth(), and com.gtfp.workingmemory.todo.ToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getDay()
int com.gtfp.workingmemory.todo.ToDoItem.getDay ()
Definition at line 697 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getDay(), and com.gtfp.workingmemory.todo.ToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getHour()
int com.gtfp.workingmemory.todo.ToDoItem.getHour ()
Definition at line 701 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getHour(), and com.gtfp.workingmemory.todo.ToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
getMin()
int com.gtfp.workingmemory.todo.ToDoItem.getMin ()
Definition at line 705 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.ToDoDateTime.getMin(), and com.gtfp.workingmemory.todo.ToDoItem.mDateTime.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker().
setTimestamp()
void com.gtfp.workingmemory.todo.ToDoItem.setTimestamp ()
Definition at line 709 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTimestamp.
getTimestamp()
long com.gtfp.workingmemory.todo.ToDoItem.getTimestamp ()
Definition at line 713 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTimestamp.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.toString().
convertToEpoch()
long com.gtfp.workingmemory.todo.ToDoItem.convertToEpoch (String dt) private
Definition at line 717 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mStoredFormat, and com.gtfp.workingmemory.todo.ToDoItem.TodayInEpoch().
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), and com.gtfp.workingmemory.todo.ToDoItem.setDueDate().
getDueDateInEpoch()
long com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch ()
Definition at line 739 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.convertToEpoch(), com.gtfp.workingmemory.todo.ToDoItem.mDueDate, and com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch.
Referenced by com.gtfp.workingmemory.db.dbSQLlite.bindRecValues(), com.gtfp.workingmemory.db.dbFireBase.bindRecValues(), com.gtfp.workingmemory.todo.ToDoItemsList.CompareDueDate.compare(), com.gtfp.workingmemory.db.dbFireBase.setTask(), com.gtfp.workingmemory.edit.editToDoItem.setupDateTimePicker(), and com.gtfp.workingmemory.db.dbFireBase.toMap().
getDueDateToDisplay()
String com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay ()
Definition at line 749 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.DueDate(), com.gtfp.workingmemory.todo.ToDoItem.formatDisplay(), com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, com.gtfp.workingmemory.todo.ToDoItem.TodayDate(), com.gtfp.workingmemory.todo.ToDoItem.TodayInEpoch(), and com.gtfp.workingmemory.todo.ToDoItem.TomorrowDate().
Referenced by com.gtfp.workingmemory.utils.Dialogue.Dialogue(), com.gtfp.workingmemory.todo.ToDoListAdapter.getView(), and com.gtfp.workingmemory.todo.ToDoAlarm.Manager.Notification().
displayDueDate() [1/2]
String com.gtfp.workingmemory.todo.ToDoItem.displayDueDate ()
Definition at line 776 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.displayTime(), com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), and com.gtfp.workingmemory.edit.editToDoItem.onCreate().
displayDueDate() [2/2]
static String com.gtfp.workingmemory.todo.ToDoItem.displayDueDate (long epoch) static
Definition at line 782 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.formatW_Y_M_D_12H().
displayTime()
static String com.gtfp.workingmemory.todo.ToDoItem.displayTime (long epoch) static
Definition at line 787 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.displayDueDate().
Referenced by com.gtfp.workingmemory.edit.RadioGroupTableLayout.onClick(), and com.gtfp.workingmemory.edit.editToDoItem.onCreate().
toEpoch() [1/2]
static Long com.gtfp.workingmemory.todo.ToDoItem.toEpoch (int year, int month, int day) static
Definition at line 795 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.onDateChanged(), and com.gtfp.workingmemory.edit.editToDoItem.setDialogTitle().
toEpoch() [2/2]
static Long com.gtfp.workingmemory.todo.ToDoItem.toEpoch (int year, int month, int day, int hour, int min) static
Definition at line 803 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
justDate() [1/2]
static Date com.gtfp.workingmemory.todo.ToDoItem.justDate (Calendar cal) static
Definition at line 811 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.DueDate(), and com.gtfp.workingmemory.todo.ToDoItem.TodayDate().
justDate() [2/2]
static Date com.gtfp.workingmemory.todo.ToDoItem.justDate (long dateTime) static
Definition at line 847 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
isSameDay()
static boolean com.gtfp.workingmemory.todo.ToDoItem.isSameDay (Calendar c1, Calendar c2) static
Definition at line 858 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mEpochFormat.
Referenced by com.gtfp.workingmemory.edit.editToDoItem.testPastDue().
isPastDue()
boolean com.gtfp.workingmemory.todo.ToDoItem.isPastDue ()
Definition at line 864 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch, and com.gtfp.workingmemory.todo.ToDoItem.mTempCal.
Referenced by com.gtfp.workingmemory.app.appView.onPreferenceClick().
toString()
String com.gtfp.workingmemory.todo.ToDoItem.toString ()
Definition at line 876 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.getDueDate(), com.gtfp.workingmemory.todo.ToDoItem.getId(), com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), and com.gtfp.workingmemory.todo.ToDoItem.getTimestamp().
Referenced by com.gtfp.workingmemory.todo.ToDoItemsList.setDueDate().
clone()
ToDoItem com.gtfp.workingmemory.todo.ToDoItem.clone ()
Definition at line 900 of file ToDoItem.java.
References com.gtfp.workingmemory.todo.ToDoItem.clone(), and com.gtfp.workingmemory.todo.ToDoItem.ToDoItem().
Referenced by com.gtfp.workingmemory.todo.ToDoItem.clone().
onDestroy()
void com.gtfp.workingmemory.todo.ToDoItem.onDestroy () protected
Definition at line 917 of file ToDoItem.java.
[static initializer]()
com.gtfp.workingmemory.todo.ToDoItem.[static initializer] () static package
Member Data Documentation
serialVersionUID
final long com.gtfp.workingmemory.todo.ToDoItem.serialVersionUID = -7507171562852085782L static private
Definition at line 923 of file ToDoItem.java.
mItemName
String com.gtfp.workingmemory.todo.ToDoItem.mItemName = "" private
Definition at line 925 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getItemName(), com.gtfp.workingmemory.todo.ToDoItem.itemToDisplay(), and com.gtfp.workingmemory.todo.ToDoItem.setItemName().
mNewItem
boolean com.gtfp.workingmemory.todo.ToDoItem.mNewItem = false private
Definition at line 927 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.newItem().
mSetAlarm
boolean com.gtfp.workingmemory.todo.ToDoItem.mSetAlarm = true private
Definition at line 929 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setAlarm().
mDueDate
String com.gtfp.workingmemory.todo.ToDoItem.mDueDate = "None" private
Definition at line 932 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDueDate(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), and com.gtfp.workingmemory.todo.ToDoItem.setDueDate().
mDueDateInEpoch
long com.gtfp.workingmemory.todo.ToDoItem.mDueDateInEpoch = 0 private
Definition at line 934 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.displayDueDate(), com.gtfp.workingmemory.todo.ToDoItem.DueDate(), com.gtfp.workingmemory.todo.ToDoItem.getCalendar(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.getDueDateToDisplay(), com.gtfp.workingmemory.todo.ToDoItem.isPastDue(), com.gtfp.workingmemory.todo.ToDoItem.reminderInterval(), and com.gtfp.workingmemory.todo.ToDoItem.setDueDate().
mDueDateCalendar
Calendar com.gtfp.workingmemory.todo.ToDoItem.mDueDateCalendar = null private
Definition at line 936 of file ToDoItem.java.
mReminder
long com.gtfp.workingmemory.todo.ToDoItem.mReminder = -1 private
Definition at line 938 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.reminderInterval(), and com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch().
mReminderChk
int com.gtfp.workingmemory.todo.ToDoItem.mReminderChk = 0 private
Definition at line 940 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getReminderChk(), com.gtfp.workingmemory.todo.ToDoItem.reminderInterval(), and com.gtfp.workingmemory.todo.ToDoItem.setReminderChk().
mOldColor
int com.gtfp.workingmemory.todo.ToDoItem.mOldColor private
Definition at line 942 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.LEDColorChanged(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDColor().
mLEDColor
int com.gtfp.workingmemory.todo.ToDoItem.mLEDColor = 0 package
Definition at line 942 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getLEDColor(), com.gtfp.workingmemory.todo.ToDoItem.LEDColorChanged(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDColor().
mOldLEDOn
int com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOn private
Definition at line 944 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getLEDOn(), com.gtfp.workingmemory.todo.ToDoItem.LEDOnChanged(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDOn().
mLEDOn
int com.gtfp.workingmemory.todo.ToDoItem.mLEDOn = 0 package
Definition at line 944 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getLEDOn(), com.gtfp.workingmemory.todo.ToDoItem.LEDOnChanged(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDOn().
mOldLEDOff
int com.gtfp.workingmemory.todo.ToDoItem.mOldLEDOff private
Definition at line 946 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.LEDOffChanged(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDOff().
mLEDOff
int com.gtfp.workingmemory.todo.ToDoItem.mLEDOff = 0 package
Definition at line 946 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getLEDOff(), com.gtfp.workingmemory.todo.ToDoItem.LEDOffChanged(), and com.gtfp.workingmemory.todo.ToDoItem.setLEDOff().
mSettingsChanged
boolean com.gtfp.workingmemory.todo.ToDoItem.mSettingsChanged = false private
Definition at line 948 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.settingsChanged().
mHasFired
boolean com.gtfp.workingmemory.todo.ToDoItem.mHasFired = false private
Definition at line 950 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.hasFired().
mShowPopup
int com.gtfp.workingmemory.todo.ToDoItem.mShowPopup = 0 private
Definition at line 952 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setShowDialogue(), and com.gtfp.workingmemory.todo.ToDoItem.showDialogue().
mUseVibrate
int com.gtfp.workingmemory.todo.ToDoItem.mUseVibrate = 0 private
Definition at line 954 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setUseVibrate(), and com.gtfp.workingmemory.todo.ToDoItem.useVibrate().
mClearNotification
int com.gtfp.workingmemory.todo.ToDoItem.mClearNotification = 0 private
Definition at line 956 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.clearNotification(), and com.gtfp.workingmemory.todo.ToDoItem.setClearNotification().
mUseLED
int com.gtfp.workingmemory.todo.ToDoItem.mUseLED = 0 private
Definition at line 958 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setUseLED(), and com.gtfp.workingmemory.todo.ToDoItem.useLED().
mUriSound
String com.gtfp.workingmemory.todo.ToDoItem.mUriSound = null private
Definition at line 960 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.setSound(), and com.gtfp.workingmemory.todo.ToDoItem.Sound().
mTimestamp
long com.gtfp.workingmemory.todo.ToDoItem.mTimestamp private
Definition at line 962 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getTimestamp(), and com.gtfp.workingmemory.todo.ToDoItem.setTimestamp().
mListPosn
int com.gtfp.workingmemory.todo.ToDoItem.mListPosn = -1 private
Definition at line 964 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getListPosn(), and com.gtfp.workingmemory.todo.ToDoItem.setListPosn().
mDeleted
boolean com.gtfp.workingmemory.todo.ToDoItem.mDeleted = false private
Definition at line 966 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.isDeleted().
mTempDate
Date com.gtfp.workingmemory.todo.ToDoItem.mTempDate = new Date() static private
Definition at line 968 of file ToDoItem.java.
mTempCal
Calendar com.gtfp.workingmemory.todo.ToDoItem.mTempCal = Calendar.getInstance() static private
Definition at line 970 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.EpochToCalendar(), com.gtfp.workingmemory.todo.ToDoItem.getCalendar(), com.gtfp.workingmemory.todo.ToDoItem.isPastDue(), com.gtfp.workingmemory.todo.ToDoItem.justDate(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), com.gtfp.workingmemory.todo.ToDoItem.setReminderEpoch(), com.gtfp.workingmemory.todo.ToDoItem.TodayInEpoch(), com.gtfp.workingmemory.todo.ToDoItem.toEpoch(), and com.gtfp.workingmemory.todo.ToDoItem.TomorrowDate().
Y_M_D
final String com.gtfp.workingmemory.todo.ToDoItem.Y_M_D = "yyyy-MM-dd " static private
Definition at line 977 of file ToDoItem.java.
W_M_D
final String com.gtfp.workingmemory.todo.ToDoItem.W_M_D = "EEE, MMM d " static private
Definition at line 979 of file ToDoItem.java.
W_Y_M_D
final String com.gtfp.workingmemory.todo.ToDoItem.W_Y_M_D = "EEE, yyyy-MM-dd " static private
Definition at line 981 of file ToDoItem.java.
HOURS_12
final String com.gtfp.workingmemory.todo.ToDoItem.HOURS_12 = " h:mm a" static private
Definition at line 983 of file ToDoItem.java.
HOURS_24
final String com.gtfp.workingmemory.todo.ToDoItem.HOURS_24 = " HH:mm" static private
Definition at line 985 of file ToDoItem.java.
mDayFormat
final DateTimeFormatter com.gtfp.workingmemory.todo.ToDoItem.mDayFormat = DateTimeFormat.forPattern(W_M_D) static private
Definition at line 989 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.formatDisplay(), com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D(), and com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D_12H().
mW_Y_M_D12HrFormat
final DateTimeFormatter com.gtfp.workingmemory.todo.ToDoItem.mW_Y_M_D12HrFormat static private
Initial value:
= DateTimeFormat
            .forPattern(W_Y_M_D + HOURS_12)
Definition at line 992 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.formatW_Y_M_D_12H().
m12DateTimeFormat
final DateFormat com.gtfp.workingmemory.todo.ToDoItem.m12DateTimeFormat = new SimpleDateFormat(W_M_D + HOURS_12) static private
Definition at line 995 of file ToDoItem.java.
m12TimeFormat
final DateTimeFormatter com.gtfp.workingmemory.todo.ToDoItem.m12TimeFormat = DateTimeFormat.forPattern(HOURS_12) static private
Definition at line 999 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.formatDisplay(), com.gtfp.workingmemory.todo.ToDoItem.formatTime(), and com.gtfp.workingmemory.todo.ToDoItem.formatW_M_D_12H().
mStoredFormat
final DateTimeFormatter com.gtfp.workingmemory.todo.ToDoItem.mStoredFormat static private
Initial value:
= DateTimeFormat
            .forPattern(Y_M_D + HOURS_12)
Definition at line 1004 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.convertToEpoch(), com.gtfp.workingmemory.todo.ToDoItem.EpochToDateTime(), and com.gtfp.workingmemory.todo.ToDoItem.formatDateTime().
mEpochFormat
final DateFormat com.gtfp.workingmemory.todo.ToDoItem.mEpochFormat = new SimpleDateFormat(Y_M_D + HOURS_24) static private
Definition at line 1008 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.isSameDay().
mDateTime
final ToDoDateTime com.gtfp.workingmemory.todo.ToDoItem.mDateTime private
Definition at line 1010 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getDay(), com.gtfp.workingmemory.todo.ToDoItem.getHour(), com.gtfp.workingmemory.todo.ToDoItem.getMin(), com.gtfp.workingmemory.todo.ToDoItem.getMonth(), com.gtfp.workingmemory.todo.ToDoItem.getYear(), com.gtfp.workingmemory.todo.ToDoItem.setDueDate(), and com.gtfp.workingmemory.todo.ToDoItem.ToDoItem().
mId
long com.gtfp.workingmemory.todo.ToDoItem.mId = -1 private
Definition at line 1016 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getId(), and com.gtfp.workingmemory.todo.ToDoItem.setId().
mKey
String com.gtfp.workingmemory.todo.ToDoItem.mKey = "" private
Definition at line 1020 of file ToDoItem.java.
Referenced by com.gtfp.workingmemory.todo.ToDoItem.getKey(), and com.gtfp.workingmemory.todo.ToDoItem.setKey().