Working Memory: com.gtfp.workingmemory.google.SignInActivity Class Reference
com.gtfp.workingmemory.google.SignInActivity Class Reference
Created by Drawn on 3/25/2017.
Public Member Functions
void onConnectionFailed (@NonNull ConnectionResult connectionResult)
void onActivityResult (int requestCode, int resultCode, Intent data)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void setGooglePlusButtonText (SignInButton signInButton, String buttonText)
Private Member Functions
void setupSignInBtns ()
void setupSignInFields ()
void authFireBase (GoogleSignInAccount acct)
void authFireBase (AccessToken token)
void signIn (AuthCredential credential)
void showProgressDialog ()
void hideProgressDialog ()
Private Attributes
GoogleApiClient mGoogleApiClient
ProgressDialog mProgressDialog
CallbackManager mFacebookCallbackManager
Static Private Attributes
static final int RC_SIGN_IN = 9001
Detailed Description
Created by Drawn on 3/25/2017.
Definition at line 40 of file SignInActivity.java.
Member Function Documentation
onCreate()
void com.gtfp.workingmemory.google.SignInActivity.onCreate (Bundle savedInstanceState) protected
Definition at line 54 of file SignInActivity.java.
References com.gtfp.workingmemory.google.SignInActivity.setupSignInBtns(), and com.gtfp.workingmemory.google.SignInActivity.setupSignInFields().
setupSignInBtns()
void com.gtfp.workingmemory.google.SignInActivity.setupSignInBtns () private
Definition at line 67 of file SignInActivity.java.
References com.gtfp.workingmemory.google.SignInActivity.authFireBase(), and com.gtfp.workingmemory.google.SignInActivity.setGooglePlusButtonText().
Referenced by com.gtfp.workingmemory.google.SignInActivity.onCreate().
setupSignInFields()
void com.gtfp.workingmemory.google.SignInActivity.setupSignInFields () private
Definition at line 149 of file SignInActivity.java.
References com.gtfp.workingmemory.Auth.Auth.userProfile().
Referenced by com.gtfp.workingmemory.google.SignInActivity.onCreate().
onConnectionFailed()
void com.gtfp.workingmemory.google.SignInActivity.onConnectionFailed (@NonNull ConnectionResult connectionResult)
Definition at line 193 of file SignInActivity.java.
onActivityResult()
void com.gtfp.workingmemory.google.SignInActivity.onActivityResult (int requestCode, int resultCode, Intent data)
Definition at line 201 of file SignInActivity.java.
References com.gtfp.workingmemory.google.SignInActivity.authFireBase().
authFireBase() [1/2]
void com.gtfp.workingmemory.google.SignInActivity.authFireBase (GoogleSignInAccount acct) private
Definition at line 228 of file SignInActivity.java.
References com.gtfp.workingmemory.google.SignInActivity.signIn().
Referenced by com.gtfp.workingmemory.google.SignInActivity.onActivityResult(), and com.gtfp.workingmemory.google.SignInActivity.setupSignInBtns().
authFireBase() [2/2]
void com.gtfp.workingmemory.google.SignInActivity.authFireBase (AccessToken token) private
Definition at line 241 of file SignInActivity.java.
References com.gtfp.workingmemory.google.SignInActivity.signIn().
signIn()
void com.gtfp.workingmemory.google.SignInActivity.signIn (AuthCredential credential) private
Definition at line 254 of file SignInActivity.java.
Referenced by com.gtfp.workingmemory.google.SignInActivity.authFireBase().
setGooglePlusButtonText()
void com.gtfp.workingmemory.google.SignInActivity.setGooglePlusButtonText (SignInButton signInButton, String buttonText) protected
Definition at line 292 of file SignInActivity.java.
Referenced by com.gtfp.workingmemory.google.SignInActivity.setupSignInBtns().
showProgressDialog()
void com.gtfp.workingmemory.google.SignInActivity.showProgressDialog () private
Definition at line 312 of file SignInActivity.java.
hideProgressDialog()
void com.gtfp.workingmemory.google.SignInActivity.hideProgressDialog () private
Definition at line 328 of file SignInActivity.java.
Member Data Documentation
RC_SIGN_IN
final int com.gtfp.workingmemory.google.SignInActivity.RC_SIGN_IN = 9001 static private
Definition at line 43 of file SignInActivity.java.
mGoogleApiClient
GoogleApiClient com.gtfp.workingmemory.google.SignInActivity.mGoogleApiClient private
Definition at line 45 of file SignInActivity.java.
mProgressDialog
ProgressDialog com.gtfp.workingmemory.google.SignInActivity.mProgressDialog private
Definition at line 47 of file SignInActivity.java.
mFacebookCallbackManager
CallbackManager com.gtfp.workingmemory.google.SignInActivity.mFacebookCallbackManager private
Definition at line 49 of file SignInActivity.java.