Working Memory: com.gtfp.workingmemory.db.dbCloud.onLogin Class Reference
com.gtfp.workingmemory.db.dbCloud.onLogin Class Reference
Public Member Functions
void onAuthStateChanged (@NonNull FirebaseAuth firebaseAuth)
Static Public Member Functions
static void onDestroy ()
Package Attributes
String mPrevProvider
Static Private Member Functions
static void addAuthStateListener ()
static void removeAuthStateListener ()
static boolean addOnLoginListener (onLoginListener listener)
static boolean removeOnLoginListener (onLoginListener listener)
Static Private Attributes
static onLogin mInstance
static Set< onLoginListener > mLoginListeners = new HashSet<>()
Detailed Description
Definition at line 1275 of file dbCloud.java.
Member Function Documentation
addAuthStateListener()
static void com.gtfp.workingmemory.db.dbCloud.onLogin.addAuthStateListener () static private
Definition at line 1285 of file dbCloud.java.
References com.gtfp.workingmemory.Auth.Auth.addAuthStateListener(), and com.gtfp.workingmemory.settings.appSettings.get().
Referenced by com.gtfp.workingmemory.db.dbCloud.onStart().
removeAuthStateListener()
static void com.gtfp.workingmemory.db.dbCloud.onLogin.removeAuthStateListener () static private
Definition at line 1299 of file dbCloud.java.
References com.gtfp.workingmemory.Auth.Auth.removeAuthStateListener().
Referenced by com.gtfp.workingmemory.db.dbCloud.onStop().
addOnLoginListener()
static boolean com.gtfp.workingmemory.db.dbCloud.onLogin.addOnLoginListener (onLoginListener listener) static private
Definition at line 1309 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.addOnLoginListener().
removeOnLoginListener()
static boolean com.gtfp.workingmemory.db.dbCloud.onLogin.removeOnLoginListener (onLoginListener listener) static private
Definition at line 1316 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.removeOnLoginListener().
onDestroy()
static void com.gtfp.workingmemory.db.dbCloud.onLogin.onDestroy () static
Definition at line 1323 of file dbCloud.java.
Referenced by com.gtfp.workingmemory.db.dbCloud.onDestroy().
onAuthStateChanged()
void com.gtfp.workingmemory.db.dbCloud.onLogin.onAuthStateChanged (@NonNull FirebaseAuth firebaseAuth)
Definition at line 1336 of file dbCloud.java.
References com.gtfp.workingmemory.settings.appSettings.get(), com.gtfp.workingmemory.Auth.Auth.isLoggedIn(), com.gtfp.workingmemory.settings.appSettings.set(), and com.gtfp.workingmemory.Auth.Auth.userProfile().
Member Data Documentation
mInstance
onLogin com.gtfp.workingmemory.db.dbCloud.onLogin.mInstance static private
Definition at line 1277 of file dbCloud.java.
mLoginListeners
Set<onLoginListener> com.gtfp.workingmemory.db.dbCloud.onLogin.mLoginListeners = new HashSet<>() static private
Definition at line 1279 of file dbCloud.java.
mPrevProvider
String com.gtfp.workingmemory.db.dbCloud.onLogin.mPrevProvider package
Definition at line 1281 of file dbCloud.java.